### ISSUE TITLE
TF 2.3 Serving | Experimental features not supported

### ISSUE THREAD

**Issue by rafiqhasan** [tensorflow/serving#1720] opened 2020-08-15 19:10 UTC
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Google Colab
- **TensorFlow Serving installed from (source or binary)**: Source
- **TensorFlow Serving version**: 2.3.0

### Describe the problem
While serving a TF 2.3 trained saved model created with **tf.keras.layers.experimental.preprocessing** features, TMS(Tensorflow model server ) gives error on prediction. However predict method on the model runs absolutely fine without any error, seems to be something specific to TMS. Does TMS currently not support the new experimental pre-processing features that were added in TF 2.3. 

I also noticed that saved_model_cli also throws error that **Op type not registered 'DenseBincount' in binary** but that could be related to saved_model_cli not yet updated in Colab with TF 2.3 support.

### Exact Steps to Reproduce
1. Run GIST - https://colab.research.google.com/gist/rafiqhasan/6f00aecf1feafd83ba9dfefef8907ee8/dl-e2e-taxi-dataset-tf2-keras.ipynb
2. Error on cell - https://colab.research.google.com/gist/rafiqhasan/6f00aecf1feafd83ba9dfefef8907ee8/dl-e2e-taxi-dataset-tf2-keras.ipynb#scrollTo=4uJvRYMmHy4N&line=15&uniqifier=1

### Source code / logs
```
import json
import requests

#Create payload
data_py = {"instances":[{'dropoff_latitude': [41.920452],
                         'dropoff_longitude': [-87.679955],
                         'pickup_latitude': [41.952823],
                         'pickup_longitude': [-87.653244],
                         'trip_start_day': ["1"],
                         'trip_start_hour': ["5"],
                         'trip_start_month': ["6"]}]}

data = json.dumps(data_py)
print("payload: ", data)

#Run request on TMS
headers = {"content-type": "application/json"}
json_response = requests.post('http://localhost:8507/v1/models/model:predict', data=data, headers=headers)
json_response.text
```

Error message:
```
{
    "error": "Missing 0-th output from {{node functional_3/category_encoding_13/bincount/DenseBincount}}"
}
```

**Comment by christisg** [comment] 2020-08-24 00:00
The error doesn't seem to be related to TF serving, it is coming from TF runtime ([here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/executor.cc#L972)), and it indicates a missing output from DenseBincount.

From your report "predict method on the model runs absolutely fine without any error" - could you give more context on how it was called and what is the result?

**Comment by rafiqhasan** [comment] 2020-08-24 07:18
Please see the code below, it is also there in the GIST:

```
# ##Prediction on model
# ## BUT HERE ALL FEATURES HAVE TO BE PASSED, EVEN THE Calculated ones
data = tf.data.Dataset.from_tensor_slices({'dropoff_latitude': [[41.920452]],
                         'dropoff_longitude': [[-87.679955]],
                         'pickup_latitude': [[41.952823]],
                         'pickup_longitude': [[-87.653244]],
                         'trip_start_day': [["1"]],
                         'trip_start_hour': [["5"]],
                         'trip_start_month': [["6"]],
                         'distance':[[0.02]]})

m_.predict(data)
```

**Comment by christisg** [comment] 2020-12-15 06:59
Sorry for the delay, @rafiqhasan. Are you able to reproduce the error with saved_model_cli?

**Comment by rafiqhasan** [comment] 2020-12-15 08:04
Hi @christisg , 

True, I get the below error when running SAVED_MODEL_CLI on the exported model.

```

MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:
  The given SavedModel SignatureDef contains the following input(s):
  The given SavedModel SignatureDef contains the following output(s):
    outputs['__saved_model_init_op'] tensor_info:
        dtype: DT_INVALID
        shape: unknown_rank
        name: NoOp
  Method name is: 

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['DIFGRIRD'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1)
        name: serving_default_DIFGRIRD:0
    inputs['DIFGRIRV'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1)
        name: serving_default_DIFGRIRV:0
    inputs['EKGRP'] tensor_info:
        dtype: DT_STRING
        shape: (-1)
        name: serving_default_EKGRP:0
    inputs['EKORG'] tensor_info:
        dtype: DT_STRING
        shape: (-1)
        name: serving_default_EKORG:0
    inputs['KTOKK'] tensor_info:
        dtype: DT_STRING
        shape: (-1)
        name: serving_default_KTOKK:0
    inputs['NODLGR'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1)
        name: serving_default_NODLGR:0
    inputs['NODLIR'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1)
        name: serving_default_NODLIR:0
    inputs['SCENARIO'] tensor_info:
        dtype: DT_STRING
        shape: (-1)
        name: serving_default_SCENARIO:0
    inputs['TOTGRQTY'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1)
        name: serving_default_TOTGRQTY:0
    inputs['TOTIRQTY'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1)
        name: serving_default_TOTIRQTY:0
    inputs['VPATD'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1)
        name: serving_default_VPATD:0
    inputs['VSTATU'] tensor_info:
        dtype: DT_STRING
        shape: (-1)
        name: serving_default_VSTATU:0
    inputs['WERKS'] tensor_info:
        dtype: DT_STRING
        shape: (-1)
        name: serving_default_WERKS:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output_0'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, 1)
        name: StatefulPartitionedCall:0
  Method name is: tensorflow/serving/predict
Traceback (most recent call last):
  File "/usr/local/bin/saved_model_cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/tools/saved_model_cli.py", line 990, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/tools/saved_model_cli.py", line 691, in show
    _show_all(args.dir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/tools/saved_model_cli.py", line 283, in _show_all
    _show_defined_functions(saved_model_dir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/tools/saved_model_cli.py", line 176, in _show_defined_functions
    trackable_object = load.load(saved_model_dir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/saved_model/load.py", line 528, in load
    return load_internal(export_dir, tags)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/saved_model/load.py", line 552, in load_internal
    export_dir)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/saved_model/load.py", line 114, in __init__
    meta_graph.graph_def.library))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/saved_model/function_deserialization.py", line 312, in load_function_def_library
    func_graph = function_def_lib.function_def_to_graph(copy)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/framework/function_def_to_graph.py", line 59, in function_def_to_graph
    fdef, input_shapes)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/framework/function_def_to_graph.py", line 218, in function_def_to_graph_def
    op_def = default_graph._get_op_def(node_def.op)  # pylint: disable=protected-access
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_core/python/framework/ops.py", line 3712, in _get_op_def
    c_api.TF_GraphGetOpDef(self._c_graph, compat.as_bytes(type), buf)
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'DenseBincount' in binary running on 5a2ad88b21cd. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
```

**Comment by rafiqhasan** [comment] 2021-01-01 15:00
@christisg  I have an update here, I think with TF 2.4 the problem has been partially fixed. The TF model load issue seems to be fixed but still there is problem in the tensorflow_model_server inference.

When I try to use the **tensorflow_model_server** to run prediction, it gives errors related to input ranks etc. which it should not ideally be giving because TF 2.4 is perfectly able to run this without any errors.

Direct inferencing works in TF 2.4 **works**:

```
#LOCAL: Predict using Keras prediction function
saved_mod = tf.saved_model.load("./exported_model/" + version)

#Get prediction function from serving
f = saved_mod.signatures['serving_default']

#Run prediction function from serving
f(dropoff_latitude=tf.convert_to_tensor([41.920452]), dropoff_longitude = tf.convert_to_tensor([-87.679955]), pickup_latitude = tf.convert_to_tensor([41.952823]), 
  pickup_longitude =tf.convert_to_tensor([-87.653244]), trip_start_day=tf.convert_to_tensor(["1"]), trip_start_hour=tf.convert_to_tensor(["5"]),
  trip_start_month=tf.convert_to_tensor(["6"]))
```

Inferencing in **tensorflow_model_server** TF 2.4 **fails**:
```
import json
import requests

#Create payload
data_py = {"instances":[{'dropoff_latitude': [41.920452],
                         'dropoff_longitude': [-87.679955],
                         'pickup_latitude': [41.952823],
                         'pickup_longitude': [-87.653244],
                         'trip_start_day': ["1"],
                         'trip_start_hour': ["5"],
                         'trip_start_month': ["6"]}]}

data = json.dumps(data_py)
print("payload: ", data)

#Run request on TMS
headers = {"content-type": "application/json"}
json_response = requests.post('http://localhost:8505/v1/models/model:predict', data=data, headers=headers)
json_response.text
```

```
payload:  {"instances": [{"dropoff_latitude": [41.920452], "dropoff_longitude": [-87.679955], "pickup_latitude": [41.952823], "pickup_longitude": [-87.653244], "trip_start_day": ["1"], "trip_start_hour": ["5"], "trip_start_month": ["6"]}]}
{\n    "error": "Shape must be at most rank 2 but is rank 3\\n\\t [[{{node model/category_encoding_2/bincount/DenseBincount}}]]"\n}
```

**Comment by DachuanZhao** [comment] 2021-02-18 09:13
You use it in a wrong way . You should use ```inputs``` instead of ```instances``` if you have multi input . Change the code to :
```python
data_py = {"inputs":{'dropoff_latitude': [41.920452],
                         'dropoff_longitude': [-87.679955],
                         'pickup_latitude': [41.952823],
                         'pickup_longitude': [-87.653244],
                         'trip_start_day': ["1"],
                         'trip_start_hour': ["5"],
                         'trip_start_month': ["6"]}}
```

**Comment by rafiqhasan** [comment] 2021-02-18 10:18
@DachuanZhao : I am afraid that's not the reason, I already have a lot of TF models which are running on TF2+ Keras with multiple inputs using "instances" and customized signatures, they work very fine without any error on TFMS. FYI: I tried it with "inputs" too and it doesn't work.

The problem comes up if we add "experimental.preprocessing" features as a layer, this clearly something related to model saving or TFMS.

**Comment by rafiqhasan** [comment] 2021-02-18 10:25
@DachuanZhao : Thanks a lot, this seems to be very strage. I have a lot of other TF2 Keras models on multiple inputs which work fine with "instances" and its only in this particular scenario where "inputs" are failing.

The problem comes up if we add "experimental.preprocessing" features as a layer, this ambiguity is clearly something related to model saving or TFMS.

**Comment by DachuanZhao** [comment] 2021-02-19 01:45
> @DachuanZhao : Thanks a lot, this seems to be very strange. I have a lot of other TF2 Keras models on multiple inputs which work fine with "instances" and its only in this particular scenario where "inputs" are failing.
> 
> The problem comes up if we add "experimental.preprocessing" features as a layer, this ambiguity is clearly something related to model saving or TFMS. Also the saved_model_cli gives error when trying to get details of the saved model.
> 
> So surely "inputs" is a good workaround but we should lookout for a fix for "instances". The difference in the results of "inputs" and "instances" is a good lead here to resolve the issue.

I can't agree you more . In fact , I think there are two serious bugs about "experimental.preprocessing" :
[https://github.com/tensorflow/tensorflow/issues/44005](https://github.com/tensorflow/tensorflow/issues/44005)
[https://github.com/tensorflow/tensorboard/issues/4530](https://github.com/tensorflow/tensorboard/issues/4530)
 
"experimental.preprocessing" is a very useful layer , I hope the two bugs will be fixed ASAP : )

**Comment by UsharaniPagadala** [comment] 2021-11-11 05:21
@rafiqhasan 

Could you please confirm if this issue can be closed as it is resolved.Thanks

**Comment by pindinagesh** [comment] 2022-06-27 11:42
Hi @rafiqhasan 

We see that you are using an old version of TF serving, We recommend that you upgrade to TF serving 2.8.0 version and let us know if the issue still persists in newer versions. Thank you!

**Comment by pindinagesh** [comment] 2022-07-12 02:09
Hi @rafiqhasan 

Closing this issue due to inactivity. Please feel free to reopen if this still exists. Thank you!

**Closed** 2022-07-12 02:11 UTC
Labels: stat:awaiting response, type:bug
