### ISSUE TITLE
Improve "INVALID_ARGUMENT: input tensor alias not found in signature"

### ISSUE THREAD

**Issue by benelot** [tensorflow/serving#435] opened 2017-05-08 15:06 UTC
Hello,

I am somehow stuck with the following exception when trying use my model in tf serving for prediction:

      "INVALID_ARGUMENT: input tensor alias not found in signature: ..."

How about improving this message with some debug information like what the model of tf serving would actually expect to have as inputs? Something like "[ModelName]:[SignatureName] requires the inputs: [InputLogicalName_1,...,_N] in order to make a prediction/classification/regression" would be Gold from the perspective of a developer.

If anybody would like to help me with my specific problem, here I describe it on stackoverflow:
[http://stackoverflow.com/questions/43849407/how-to-debug-invalid-argument-input-tensor-alias-not-found-in-signature](http://stackoverflow.com/questions/43849407/how-to-debug-invalid-argument-input-tensor-alias-not-found-in-signature)

**Comment by kirilg** [comment] 2017-05-10 23:31
Good idea, I'll update the error message with the expected list of inputs/outputs. I think the ModelName:SignatureName can already be derived from the request.

**Comment by benelot** [comment] 2017-05-11 09:16
True. At this point, ModelName:SignatureName should already be correct. Maybe the possible model names or the possible signature names could be added to the respective error messages when the indicated model/signature can not be found.

**Comment by benelot** [comment] 2017-07-04 13:10
Any updates on this?

**Comment by B1tMaster** [comment] 2018-03-20 12:26
Please help.. I am trying to use inception_client.py to query the "serving" server. I have retrained the inception model and loaded it into inception "serving" server. it loaded fine. 
The problem is that signatureDef of the model is:  "serving-default" . there is no way to make the retrain.py take an argument to change that.

However inception_client.py is looking for "predict_image" signatureDef. Why? If serving server has "serving-default" why the client is looking for a different key?

But ok, I went and modified inception_client.py to look for "predict_image" . And I was so sure that finally I will get my model to work and test it. But unfortunately no.. Now I get this new error:


```
  File "./serving/tensorflow_serving/example/inception_client.py", line 56, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "./serving/tensorflow_serving/example/inception_client.py", line 51, in main
    result = stub.Predict(request, 10.0)  # 10 secs timeout
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 309, in __call__
    self._request_serializer, self._response_deserializer)
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 195, in _blocking_unary_unary
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.INVALID_ARGUMENT, details="input tensor alias not found in signature: images. Inputs expected to be in the set {image}.")
root@5f0f0cbe40b7:/#
```

Please help, i have been stuck with this for a week now. I can't figure out why the model is being outputted with "serving-default' by retrain.py and the client is looking for different key. How do I either output the model with the key client looking for or change the client so it can find it?

I have a bit more details and error logs that preceded this error (as history) here:
https://github.com/bitnami/bitnami-docker-tensorflow-inception/issues/4

Very frustrating. Hope somebody can point me to a solution.

**Comment by chrisolston** [comment] 2018-03-26 21:29
The model has *two* signatures, which you can see if you look at how the model is exported [1]. The default one uses the Classify API, and the other one uses the (lower-level) Predict API. The APIs are different, so you can't just swap one signature name for the other in the client and expect it to work.

In particular, the Predict signature is looking for an input called "image" but you are feeding something called "images" (note that it's plural). But in any case, like I said I wouldn't expect it to work if you are using the wrong API (via the wrong signature).

What happens if you leave the request signature as "predict_images" (note that it's plural) in inception_client.py? In other words, could you please revert inception_client.py to the baseline implementation and tell me what outcome/error you get?

[1] https://github.com/tensorflow/serving/blob/3571248707f47b5b9016195c6c06e7fa26f629b0/tensorflow_serving/example/inception_saved_model.py#L130

**Comment by ymodak** [comment] 2018-10-16 22:50
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by ymodak** 2018-10-16 22:50 UTC
