### ISSUE TITLE
TF-serving container doesn't  use GPU when --batching_enabled=true

### ISSUE THREAD

**Issue by TheR3d1** [tensorflow/serving#1392] opened 2019-07-11 13:18 UTC
### System information
- OS : CentOS 7
- Docker image : tensorflow/serving:latest-gpu
- Docker version: 1.13.1
- GPU : PNY Quadro K2200 4GB

###  Issue

I run the docker image of TF-serving first with batching_enabled=false and then with batching_enabled=true(after I have stopped the first container). I watch the GPU usage with watch `nvidia-smi -n0.1`. I make a batched predict request with a http post request. 
When batching_enabled=false GPU usage goes up to 100% but when batching_enabled=true GPU usage stays 0% during test and CPU usage get 3 times higher than the previous test.
So I suppose that when batching_enabled=true the container uses CPU to predict. If that happens how can I use the GPU to predict with batched_enabled=true?

### Exact Steps to Reproduce

`docker run    -t --rm -p 8510:8501 \
	-v "path/to/model:/models/th" \
	-e MODEL_NAME=th \
	tensorflow/serving:latest-gpu &`

#run script batched request(102400 numpy arrays) 5times one after the other GPU usage 100%
#stop the container 

`docker run    -t --rm -p 8510:8501 \
	-v "path/to/model:/models/th" \
	-e MODEL_NAME=th \
	tensorflow/serving:latest-gpu   --enable_batching=true & ` 

#run the same tests GPU usage 0%

**Comment by gowtham-kp** [comment] 2019-07-30 05:46
@TheR3d1 Can you please share the model or the characteristics of the model for us to take a look at it and analyze it as we are not sure if its the model or TF Serving itself that's causing the issue. Thanks!

**Comment by netfs** [comment] 2019-07-31 17:17
I looked at the code, and BatchingSession (one that is created, when you enable batching) uses DirectSession underneath -- and this by looking at the code should use all the underlying devices (this means CPU and GPU both). So its rather strange to see enabling batching causes GPU usage to drop to zero.

As @gowtham-kp points above, to analyze this further -- we will need the model, client code that sends requests and few sample requests that reproduces this problem.

thanks!

**Comment by rmothukuru** [comment] 2019-08-13 06:25
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2019-08-13 06:25 UTC
Labels: stat:awaiting response, type:support
