### ISSUE TITLE
serving won't compile

### ISSUE THREAD

**Issue by ddkang** [tensorflow/serving#400] opened 2017-04-07 22:41 UTC
OS: Ubuntu 14.04.5 LTS
CUDA: 8.0
CUDNN: 5.1.10

I've tried to compile serving and I get the following error, any help would be appreciated:

```root@39238b22128f:~/code/serving# cd tensorflow
root@39238b22128f:~/code/serving/tensorflow# ./configure 
Please specify the location of python. [Default is /usr/bin/python]: 
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 
Do you wish to use jemalloc as the malloc implementation? [Y/n] 
jemalloc enabled
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] 
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] 
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] 
No XLA support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

Using python library path: /usr/local/lib/python2.7/dist-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] 
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] Y
CUDA support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 
Please specify the location where CUDA  toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the cuDNN version you want to use. [Leave empty to use system default]: 
Please specify the location where cuDNN  library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 5.2
Configuration finished
root@39238b22128f:~/code/serving/tensorflow# cd ..
root@39238b22128f:~/code/serving# bazel build tensorflow_serving/...
Extracting Bazel installation...
............
ERROR: /root/.cache/bazel/_bazel_root/eded1d35b827320ea7e77ab03f02d715/external/org_tensorflow/third_party/gpus/cuda_configure.bzl:828:18: unexpected keyword 'environ' in call to repository_rule(implementation: function, *, attrs: dict or NoneType = None, local: bool = False).
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file 'third_party/gpus/cuda_configure.bzl' has errors.
INFO: Elapsed time: 3.666s

root@39238b22128f:~/code/serving# git log -n 1 
commit 51bb3569638d910dfd53a8e049cb932c9c53525e
Merge: 5ead923 8a9d4b2
Author: Kiril Gorovoy <kgorovoy@google.com>
Date:   Wed Feb 15 12:59:24 2017 -0800

    Merge pull request #325 from kirilg/0.5.1
    
    Upstream changes to TF submodule

```

**Comment by terryKing1992** [comment] 2017-04-12 07:19
TensorFlow Serving requires Bazel 0.4.5 or higher.

**Comment by kirilg** [comment] 2017-04-12 17:12
If you intended to use TF Serving at head, then yes, it requires Bazel 0.4.5.

Given your git log, it looks like you want to use TF Serving 0.5.1 with TF 1.0, which at the time didn't require that version of Bazel. I suspect the issue you're seeing is that you cloned from master, then checked out 0.5.1 but didn't update submodules to resync to the commit at the time. Try:

```
# from the serving repo
git checkout 0.5.1
git log -1
# confirm commit is 51bb356
git submodule update --init --recursive
cd tensorflow
git log -1
# confirm the TF commit was correctly updated to 07bb8ea2379bd459832b23951fb20ec47f3fdbd4

./configure
cd ..
```
and continue as you normally would.

**Comment by zhihongzeng** [comment] 2017-04-13 15:21
host OS: ubuntu 16.04 LTS 64bit
I got the error in compiling codes, and tried two methods by following the above methods (checkout 0.5.1 vision, and upgrade bazel) but still cannot figure it out. 
working environment is in the docker container whose image was created by following 
https://tensorflow.github.io/serving/serving_inception

Here are the errors at beginning :

root@35843ba60ca0:/# git clone --recurse-submodules https://github.com/tensorflow/serving
...
root@35843ba60ca0:/# cd serving/tensorflow
root@35843ba60ca0:/serving/tensorflow# ./configure
Please specify the location of python. [Default is /usr/bin/python]: 
Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 
Do you wish to use jemalloc as the malloc implementation? [Y/n] 
jemalloc enabled
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] 
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] 
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] 
No XLA support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

Using python library path: /usr/local/lib/python2.7/dist-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] 
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] 
No CUDA support will be enabled for TensorFlow
..........
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
Configuration finished
root@35843ba60ca0:/serving/tensorflow# cd ..
root@35843ba60ca0:/serving# bazel build -c opt tensorflow_serving/...
INFO: Reading 'startup' options from /root/.bazelrc: --batch
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: /serving/WORKSPACE:10:1: //external:io_bazel_rules_closure: no such attribute 'urls' in 'http_archive' rule.
ERROR: /serving/WORKSPACE:10:1: //external:io_bazel_rules_closure: missing value for mandatory attribute 'url' in 'http_archive' rule.
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Encountered error while reading extension file 'tensorflow/workspace.bzl': no such package '@org_tensorflow//tensorflow': error loading package 'external': Could not load //external package.
INFO: Elapsed time: 0.610s

**The first try:**
Using the above the method by checkout 0.5.1 and submodule update. Then got error about ../configure

root@35843ba60ca0:/serving# git checkout 0.5.1
M	tensorflow
M	tf_models
Note: checking out '0.5.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 51bb356... Merge pull request #325 from kirilg/0.5.1

root@35843ba60ca0:/serving# git submodule update --init --recursive
Submodule path 'tensorflow': checked out '07bb8ea2379bd459832b23951fb20ec47f3fdbd4'
Submodule path 'tf_models': checked out '2fd3dcf3f31707820126a4d9ce595e6a1547385d'
Submodule path 'tf_models/syntaxnet/tensorflow': checked out '45ab528211c962b19e12f6b77165848310271624'
root@35843ba60ca0:/serving# cd tensorflow
root@35843ba60ca0:/serving/tensorflow# ./configure
Please specify the location of python. [Default is /usr/bin/python]: 
Please specify optimization flags to use during compilation [Default is -march=native]: 
Do you wish to use jemalloc as the malloc implementation? (Linux only) [Y/n] 
jemalloc enabled on Linux
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] 
No Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] 
No Hadoop File System support will be enabled for TensorFlow
Do you wish to build TensorFlow with the XLA just-in-time compiler (experimental)? [y/N] 
No XLA support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

Using python library path: /usr/local/lib/python2.7/dist-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] 
No OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] 
No CUDA support will be enabled for TensorFlow
Configuration finished
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
.........
ERROR: /serving/tensorflow/tensorflow/workspace.bzl:65:3: //external:eigen_archive: no such attribute 'urls' in 'new_http_archive' rule.
ERROR: /serving/tensorflow/tensorflow/workspace.bzl:65:3: //external:eigen_archive: missing value for mandatory attribute 'url' in 'new_http_archive' rule.
ERROR: /serving/tensorflow/tensorflow/workspace.bzl:76:3: //external:libxsmm_archive: no such attribute 'urls' in 'new_http_archive' rule.
ERROR: /serving/tensorflow/tensorflow/workspace.bzl:76:3: //external:libxsmm_archive: missing value for mandatory attribute 'url' in 'new_http_archive' rule.
ERROR: /serving/tensorflow/tensorflow/workspace.bzl:92:3: //external:com_googlesource_code_re2: no such attribute 'urls' in 'http_archive' rule.
ERROR: /serving/tensorflow/tensorflow/workspace.bzl:92:3: //external:com_googlesource_code_re2: missing value for mandatory attribute 'url' in 'http_archive' rule.

**The second try:** upgrade bazel by following 
https://bazel.build/versions/master/docs/install-ubuntu.html

root@35843ba60ca0:/serving/tensorflow# echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8
root@35843ba60ca0:/serving/tensorflow# curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3157  100  3157    0     0   7403      0 --:--:-- --:--:-- --:--:--  7410
OK
root@35843ba60ca0:/serving/tensorflow# sudo apt-get update && sudo apt-get install bazel
root@35843ba60ca0:/serving/tensorflow# sudo apt-get upgrade bazel
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
bazel is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@35843ba60ca0:/serving# bazel version
INFO: Reading 'startup' options from /root/.bazelrc: --batch
Build label: 0.3.2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Oct 7 17:25:10 2016 (1475861110)
Build timestamp: 1475861110
Build timestamp as int: 1475861110

**Comment by kirilg** [comment] 2017-04-13 21:37
It looks like your Bazel version is 0.3.2. Please follow the [instructions here](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/setup.md) to update your Bazel version. The minimum version that works with head is 0.4.5

**Comment by zhihongzeng** [comment] 2017-04-17 16:38
I found the problem is:
in the tensorflow_serving/tools/docker/Dockerfile.devel  at https://tensorflow.github.io/serving/serving_inception

Line 59: ENV BAZEL_VERSION 0.3.2

So that in the built image, bazel version is always 0.3.2 no matter whether I upgrade it.

Conclusion: 
tensorflow_serving/tools/docker/Dockerfile.devel is out of date.

**Comment by sukritiramesh** [comment] 2017-04-18 17:37
Hi @zhihongzeng, it looks like this is now fixed:
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel#L59
Please reopen if the file is still outdated.

**Closed by sukritiramesh** 2017-04-18 17:37 UTC
