### ISSUE TITLE
Tensorflow serving "inception_client" for android?

### ISSUE THREAD

**Issue by informatica92** [tensorflow/serving#439] opened 2017-05-12 09:03 UTC
Hi all, 
I installed tensorflow serving on my computer. In particular I'm interested in the inception sample.
Following the steps reported in https://tensorflow.github.io/serving/serving_inception#part_0_create_a_docker_image I installed tensorflow serving and configured it. I can also launch the tensorflow_model_server and test it using inception_client (on the same computer using python scripts).
My question is: Is there a sample to perform request to the server from android?

Thanks

**Comment by quanhua92** [comment] 2017-05-19 05:53
It is possible to create a java version of the python client. However, I think that it won't be easy if you are not familiar with grpc. If I were you, I would create a python rest api to use the code in inception_client and the android app will call the rest api to receive the result.

**Comment by fzngagan** [comment] 2018-01-21 14:51
keras is way better atleast for prototyping as it supports https based model serving

**Comment by gautamvasudevan** [comment] 2018-08-03 20:02
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 20:02 UTC
