### ISSUE TITLE
TF-Serving Python Support

### ISSUE THREAD

**Issue by csteegz** [tensorflow/serving#933] opened 2018-06-12 16:46 UTC
GRPC has announced they will be [ending support for Python 2.7 in the beginning of 2020.](https://groups.google.com/forum/#!topic/grpc-io/psLfi-li4u8)

Given the TF-Serving's team previous stance on python 3 support #700 - what is the plan for the GRPC EOL. Will there be an official Python3 package release? Will there be continued support for Python 2?

**Comment by illagrenan** [comment] 2018-06-12 21:03
This is IMHO duplicate of https://github.com/tensorflow/serving/issues/700.

**Comment by gautamvasudevan** [comment] 2018-06-19 23:49
We will eventually have a Python3 package.

**Closed by gautamvasudevan** 2018-06-19 23:49 UTC
