### ISSUE TITLE
GPU utilization with TF serving

### ISSUE THREAD

**Issue by blakenguyen97** [tensorflow/serving#1440] opened 2019-09-17 09:42 UTC
Hi, I have trained a model (EfficientNet) on a machine with 4xRTX 2080Ti. The the problem is when I served the model with TF serving, it didn't use 100% GPU utilization ( it got stuck at 40%-50%), but when I serve it on another machine (RTX 2070) it used 100%. Can you tell  me what the problem is ? Thank you so much

**Comment by rmothukuru** [comment] 2019-09-17 17:14
@blakenguyen97 ,
Can you please provide below details:

1. What is the size of the Model
2. When you said you have Served it on another machine (RTX 2070), how many GPUs were you using in that Machine
3. Is the process of Serving same in both the Machines, like batching, etc..
4. Can you please monitor GPU usage, as described in #1190,  and share us the details.
Thanks!

**Comment by Khang-9966** [comment] 2019-09-18 03:15
> @blakenguyen97 ,
> Can you please provide below details:
> 
> 1. What is the size of the Model
> 2. When you said you have Served it on another machine (RTX 2070), how many GPUs were you using in that Machine
> 3. Is the process of Serving same in both the Machines, like batching, etc..
> 4. Can you please monitor GPU usage, as described in #1407 ,  and share us the details.
>    Thanks!

Hi @rmothukuru, I think may be problem we have is the CPU cores. Because when we run the docker tensorflow serving with NVIDIA docker [https://hub.docker.com/layers/tensorflow/serving/latest-gpu/images/sha256-fd54edb56a7bc72ea0606ed03b7de7d3cfb8a2143e797187555a78b37ff7c49a](url) on the 6 Cores Intel CPU the usage of GPU is max 100%, But when tried to perform the same method for Intel Xeon 28 Physical Cores / 56 visual Cores, 4 card 2080Ti, but we turned on visible the only one GTX for that docker, we got this issue. Do you think some config bellow can solve this problem ?
```
-e OMP_NUM_THREADS=
-e TENSORFLOW_INTER_OP_PARALLELISM=
-e TENSORFLOW_INTRA_OP_PARALLELISM=
```
I found many issue happen with the tensorflow docker on CPU within many cores like:
- [https://www.freecodecamp.org/news/how-a-badly-configured-tensorflow-in-docker-can-be-10x-slower-than-expected-3ac89f33d625/](url)
- [http://blog.tabanpour.info/projects/2018/09/07/tf-docker-kube.html](url)
- [https://arxiv.org/pdf/1812.01665.pdf](url)

So, When Initializing docker, Did It take all cores of CPU and conflicted with this config?
```
#Based on our observations during experiments,
#setting tensorflow_session_parallelism=<1/4th of physical cores> and
#setting OMP_NUM_THREADS=<Total physical cores>
#gave optimal performance results with MKL
KMP_BLOCKTIME=<Varies based on your model>
#NOTE: We don't guarantee same settings to give optimal performance across all hardware
#please tune variables as required.
ENV OMP_NUM_THREADS=2
ENV TENSORFLOW_INTRA_OP_PARALLELISM=2
ENV TENSORFLOW_INTER_OP_PARALLELISM=2
```
 Would you like to give us the advice ? Many thanks !!!

**Comment by blakenguyen97** [comment] 2019-09-19 03:56
> @blakenguyen97 ,
> Can you please provide below details:
> 
> 1. What is the size of the Model
> 2. When you said you have Served it on another machine (RTX 2070), how many GPUs were you using in that Machine
> 3. Is the process of Serving same in both the Machines, like batching, etc..
> 4. Can you please monitor GPU usage, as described in #1407 ,  and share us the details.
>    Thanks!

Hi @rmothukuru,

1. The size of the model is 'bout 80Mb.
2. There was only 1 RTX 2070 on my second machine ( with 6 physical cores Intel CPU ). But on my first machine ( 4xRTX 2080Ti ), there was a 28 cores Intel Xeon CPU. Can this difference cause the problem ?
3. Yes, the process is same in both machines.
4. I just have an image of GPU utilization on my RTX 2070 (using nvtop tool)
![image_2019_09_18T04_06_29_133Z](https://user-images.githubusercontent.com/52020800/65212369-05fa8b00-dacc-11e9-9a69-f649f7edc787.png)

Thank you.

**Comment by rmothukuru** [comment] 2019-09-19 17:33
@aaroey,
Do you have any idea regarding this issue. Thanks!

**Comment by blakenguyen97** [comment] 2019-09-20 02:54
> @aaroey,
> Do you have any idea regarding this issue. Thanks!

Hi @rmothukuru, one more thing is I used TensorRT for optimizing the model (FP16). Thanks

**Comment by aaroey** [comment] 2019-09-20 14:08
@blakenguyen97 could you try running the model with pure TF (not TF Serving), and see what the GPU utilization is?

**Comment by rmothukuru** [comment] 2019-10-03 06:26
@blakenguyen97,
Can you please respond to @aaroey's comments so that we can help you. Thanks!

**Comment by rmothukuru** [comment] 2019-10-07 06:22
@blakenguyen97,
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue using both, Tensorflow and Tensorflow Serving. Thanks!

**Comment by blakenguyen97** [comment] 2019-10-07 07:24
> @blakenguyen97,
> Can you please respond to @aaroey's comments so that we can help you. Thanks

I'm really sorry for this :(

> @blakenguyen97 could you try running the model with pure TF (not TF Serving), and see what the GPU utilization is?

Hi @aaroey, I tried to run the model with the model with pure TF, but the utilization didn't increase.

I used these lines of code to convert the model with TRT...
![image](https://user-images.githubusercontent.com/52020800/66291129-41d68280-e90b-11e9-814b-a9ebd435a1d3.png)

...and these for TF Serving
![image](https://user-images.githubusercontent.com/52020800/66291213-79452f00-e90b-11e9-88e5-053b24984b99.png) 

I think the problem is from the hardware. Do you have any suggestion for this? 
I will test again on another machine with less CPU core and share with you as soon as possible.
Thank you @aaroey  @rmothukuru

**Comment by leo-XUKANG** [comment] 2019-10-14 02:34
> @blakenguyen97 could you try running the model with pure TF (not TF Serving), and see what the GPU utilization is?

I have the some problem that gpu-utils only can reach 7% in tensorflow-serving, but when i use prune tensorflow.   it is 100%.

**Comment by philongnghoang** [comment] 2019-10-14 09:35
@blakenguyen97 try to run the container with these parameters:

--grpc_channel_arguments=grpc.max_concurrent_streams=1000 \
--per_process_gpu_memory_fraction=0.7 \
--enable_batching=true \
--batching_parameters_file=/models/flow2_batching.config \
--tensorflow_session_parallelism=2 \

**Comment by blakenguyen97** [comment] 2019-10-15 03:14
@philongnghoang It works. I use multi-threading to create several requests and the utilization reached 98%. But when there was only 1 request, the utilization only reached 50-60%, but I will try to fix it later. Thank you very much. 
![image_2019_10_14T09_37_43_532Z](https://user-images.githubusercontent.com/52020800/66797316-8af28c00-ef34-11e9-9f89-84f72d47af39.png)

**Comment by jusonn** [comment] 2019-10-15 04:45
@philongnghoang  Does your server inference request in batch?

**Comment by rmothukuru** [comment] 2019-10-15 06:02
@blakenguyen97,
Can you please confirm if we can close this issue. Thanks!

**Closed** 2019-10-15 06:41 UTC
Labels: gpu utilization, stat:awaiting response, type:support

**Comment by philongnghoang** [comment] 2019-10-15 06:51
> @philongnghoang Does your server inference request in batch?
Yes. I set up my server to inference in batching. You can try to run the container with these parameters:
--enable_batching=true
--max_batch_size=10
--batch_timeout_micros=1000 
--max_enqueued_batches=1000
--num_batch_threads=6

**Comment by philongnghoang** [comment] 2019-10-15 06:52
> @philongnghoang Does your server inference request in batch?
Yes. I set up my server to inference in batching. You can try to run the container with these parameters:
--enable_batching=true
--max_batch_size=10
--batch_timeout_micros=1000
--max_enqueued_batches=1000
--num_batch_threads=6

**Comment by leo-XUKANG** [comment] 2019-10-17 06:18
@philongnghoang  if i use a big batch, it will use a lot of GPU-MEM,

**Comment by philongnghoang** [comment] 2019-10-17 07:05
> @philongnghoang if i use a big batch, it will use a lot of GPU-MEM,

I have a lot of GPU

**Comment by leo-XUKANG** [comment] 2019-10-17 09:13
LOL， dude, you won
![image](https://user-images.githubusercontent.com/28701457/66995325-639cea00-f101-11e9-8773-55e63841af1e.png)

**Comment by leo-XUKANG** [comment] 2019-10-17 09:13
> > @philongnghoang if i use a big batch, it will use a lot of GPU-MEM,
> 
> I have a lot of GPU

dude, you won 
![image](https://user-images.githubusercontent.com/28701457/66995379-7c0d0480-f101-11e9-9a11-939529ec90cf.png)

**Comment by Arnold1** [comment] 2020-02-25 04:01
hi, I currently use TensorFlow Serving with cpu only, the p99 latency is around 20ms (no batching).
lets say I switch from cpu to cpu, will it help to increase the throughput and still keep p99 latency at 20ms?

**Comment by Arnold1** [comment] 2020-03-10 22:41
@blakenguyen97 are you still available?

**Comment by blakenguyen97** [comment] 2020-03-12 03:51
> @blakenguyen97 are you still available?

Sorry for being late. I didn't notice the notifications. This is my my batching.config files:
---
max_batch_size { value: 1000 }
batch_timeout_micros { value: 100000 }
max_enqueued_batches { value: 1000000 }
num_batch_threads { value: 48 }
---

If you need any helps just comment below. Regards

**Comment by blakenguyen97** [comment] 2020-03-12 03:52
> @blakenguyen97 are you still available?

Sorry for being late. I didn't notice the notifications. This is my batching.config files:

max_batch_size { value: 1000 }
batch_timeout_micros { value: 100000 }
max_enqueued_batches { value: 1000000 }
num_batch_threads { value: 48 }

If you need any help just comment below. Regards

**Comment by Arnold1** [comment] 2020-03-12 17:36
@blakenguyen97 thank u

can you provide infos to:
- how you start the tf serving docker image? (gpu memory fraction, etc)
- which TensorFlow Serving image you use? 
- ubuntu version
- cuda version
- what gpu card you use

also, is there a "hello world" I can run for the first time I use tf serving on the gpu? are you hanging out on slack  or irc by chance?

**Comment by blakenguyen97** [comment] 2020-03-16 04:34
Hi there,






> * how you start the tf serving docker image? (gpu memory fraction, etc)

It depends on how much memory you need, for me I set it to 0.9
--per_process_gpu_memory_fraction=0.9



> * which TensorFlow Serving image you use?

I built my image based on this official image "nvcr.io/nvidia/tensorflow:19.02-py3" , you can directly use this image to serve your model. It's totally fine. I built my own image because I need to install more packages.



> * ubuntu version
> * cuda version

You don't have to worry about the CUDA, it is included in the image, just start the docker container and you have all you need. Are you new to container technology? Maybe you should know about docker container first before jumping into TF Serving.




> * what gpu card you use

 It's NVIDIA  RTX 2070. 


> also, is there a "hello world" I can run I tf serving on the gpu the very first time?
There's a lot of tutorials, you can search for them on medium blog, google, youtube,..Maybe it's a little bit confusing when you first try tf serving,... but trust me, you will love it like I do  LOL. Good luck.

Regards,

**Comment by junneyang** [comment] 2020-11-11 03:36
why close
