### ISSUE TITLE
tensorflow_model_server does not die when parent dies

### ISSUE THREAD

**Issue by kamei86i** [tensorflow/serving#498] opened 2017-06-23 09:10 UTC
I'm experiencing a problem with the tensorflow_model_server 0.5.1 compiled on an ubuntu machine. I usually start the tf serving within Java ProcessBuilder.
When the main Java thread is killed (kill -15) the tensorflow_model_server remains running with a new parent (the init process). I was instead expecting it would have been killed as well with the parent Java process.
To reproduce the problem you can use the following Java code:

```
import java.io.IOException;
import java.util.Arrays;
public class ShutdownTest {
	public static void main(String[] args) {
		ProcessBuilder builder = new ProcessBuilder(Arrays.asList(
				"tensorflow_model_server", "--use_saved_model=true",
				"--port=9000", "--model_name=model_name",
				"--model_base_path=your_model"));
		builder.redirectErrorStream(true);
		try {
			Process servingProcess = builder.start();
		} catch (IOException e) {
			e.printStackTrace();
		}
		while (true) {
		}
	}
}
```

then you should kill the java process and you should observe that the tensorflow_model_server process is still running.

**Comment by kamei86i** [comment] 2017-06-27 08:28
Other info:
1) a strace -p PID command started over the tf serving process launched from Java says something like:
``
futex(0x6f90fec, FUTEX_WAIT_PRIVATE, 1, NULL
``
 When killing the parent nothing happens, while killing the tf serving process a sigterm signal is observed in the strace.
2) A tf serving model server compiled from source (about in mid december 2016) seems not affected by this problem
2.1) when i launch it from Java it is killed when i kill the java process
2.2.) in the strace output i have again futex call, but when i kill the java process a SIGPIPE signal is received and the tf model server is killed.

**Comment by kamei86i** [comment] 2017-06-27 09:07
I think could be relevant also:
4.4.0-81-generic #104~14.04.1-Ubuntu x86_64
Ubuntu EGLIBC 2.19-0ubuntu6.13
grpcio 1.0.3

**Comment by gautamvasudevan** [comment] 2018-08-03 20:13
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 20:13 UTC
