### ISSUE TITLE
High CPU usage for tensor serialization/deserialization

### ISSUE THREAD

**Issue by llhe** [tensorflow/serving#414] opened 2017-04-20 03:10 UTC
We tested with a java client + tensorflow serving setup. And noticed the tensor serialization/deserialization consumes a lot of CPU cycles in the client side (the server side should be similar), especially when the model is shallow. [Here](https://github.com/tensorflow/serving/files/939760/jstack.txt) is an example jstack.

It's suggested to support tensor serialization optimization as done in [distributed training](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/tensor.proto#L36), at least, as an option.

**Comment by gautamvasudevan** [comment] 2018-08-03 19:56
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 19:56 UTC
