### ISSUE TITLE
Running TFX/tutorials/serving/rest_simple.ipynb on Colab is returning ConnectionError

### ISSUE THREAD

**Issue by dennymarcels** [tensorflow/serving#2054] opened 2022-09-07 14:17 UTC
### System information
Current Google Colab environment

### Describe the problem
Running [this tutorial](https://www.tensorflow.org/tfx/tutorials/serving/rest_simple) on Colab is returning `ConnectionError: HTTPConnectionPool(host='localhost', port=8501): Max retries exceeded with url: /v1/models/fashion_model:predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fddc00a8310>: Failed to establish a new connection: [Errno 111] Connection refused'))`
Since I am trying to implement the tutorial with my own code, I am stuck at the request stage.

### Exact Steps to Reproduce
Just run the tutorial.

**Comment by singhniraj08** [comment] 2022-09-09 09:29
@dennymarcels,

Looks like this is duplicate of issue #2012.

As a workaround, downgrade tensorflow-model-server from 2.10.0 to 1.15.0.  

In `Install TensorFlow Serving` section of the notebook, please uncomment `!{SUDO_IF_NEEDED} apt-get install tensorflow-model-server` line and add below lines. 

**Code to install tensorflow-model-server 1.15.0:**
```
!wget 'http://storage.googleapis.com/tensorflow-serving-apt/pool/tensorflow-model-server-1.15.0/t/tensorflow-model-server/tensorflow-model-server_1.15.0_all.deb'
!dpkg -i tensorflow-model-server_1.15.0_all.deb
!pip3 install tensorflow-serving-api==1.15

```


Sharing the working [gist file](https://colab.sandbox.google.com/gist/singhniraj08/dff4c94062c2409828bbf1211dd50821/rest_simple.ipynb) for reference. Can you please close this issue, since it is already being tracked on #2012. Thank you!

**Comment by dennymarcels** [comment] 2022-09-09 12:44
Hi there, thank you very much for the reply.
I did install actually version 2.8.0 as suggested in #2012 and it is back to work! :)

**Closed** 2022-09-09 12:44 UTC
Labels: stat:awaiting response, type:bug
