### ISSUE TITLE
libprotobuf ERROR external/protobuf/src/google/protobuf/io/coded_stream.cc:207

### ISSUE THREAD

**Issue by TgithubJ** [tensorflow/serving#396] opened 2017-04-04 22:38 UTC
Hi, 

I tried to load my exported model (1.9 GB size), but couldn't succeed because the protocol message was bigger than 1GB. However, I think it should be okay to load 1.9GB model because the "kDefaultTotalBytesLimit" is INT_MAX (It is 2^31-1) inside "coded_stream.h". 

Could you let me know why the size is limited to 1 GB, instead of 2GB?

And, I found that my model is huge because of the Word_Embedding is inside my model. 
Could you give me an advice how to separate Word_Embedding from the ML Model and serve both of them?

Thank you very much.

**Comment by gautamvasudevan** [comment] 2018-08-03 19:55
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 19:55 UTC
