### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by smartvdo** [tensorflow/serving#560] opened 2017-08-13 04:04 UTC
Hi, I understand that the current TF serving can only be used on the linux env. How could it be ported to the Windows platform?

**Comment by kirilg** [comment] 2017-08-14 23:27
Bazel on Windows is in Beta, but it might have the necessary functionality to compile TensorFlow Serving already. My guess is it will require a lot of  trial and error trying to compile on Windows and fixing issues one by one as they come up. There will probably be issues with some of the dependencies as well, but I'm not sure. We've never tried compiling on Windows and are not entirely sure what to expect.

**Comment by gautamvasudevan** [comment] 2018-07-13 18:57
Duplicate of #240

**Closed by gautamvasudevan** 2018-07-13 18:57 UTC
Labels: contributions welcome
