### ISSUE TITLE
Slow start (or crash) on GPU

### ISSUE THREAD

**Issue by Panaetius** [tensorflow/serving#337] opened 2017-02-25 15:57 UTC
I'm trying to run a modified version of the tensorflow cifar10 tutorial model (basically VGGNet using the cifar10 as boilerplate). I accidentally installed tensorflow serving without GPU support earlier and tensorflow_model_server started almost instantly when I ran it (1-5 seconds).

When executing the model in regular tensorflow, it takes maybe 30 seconds to get up and running (loading data for batching etc.)

The exported model is 450MB.

Since I realised my mistake, I rebuilt tensorflow serving with GPU support, and now when I run tensorflow_model_server it correctly starts using the GPU (NVIDIA 1070 GTX), but it seems to hang at the "Running LegacyInitOp on SavedModel bundle." step. It uses all memory on the GPU, 26GB on my system and 100% CPU (on one core, I think), and after a couple of minutes, it failed with the following error:

`tensorflow_model_server: external/eigen_archive/unsupported/Eigen/CXX11/src/Tensor/TensorExecutor.h:262: static void Eigen::internal::TensorExecutor<Expression, Eigen::GpuDevice, Vectorizable>::run(const Expression&, const Eigen::GpuDevice&) [with Expression = const Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<long long int, 1, 1, long int>, 16, Eigen::MakePointer>, const Eigen::TensorConversionOp<long long int, const Eigen::TensorMap<Eigen::Tensor<const int, 1, 1, long int>, 16, Eigen::MakePointer> > >; bool Vectorizable = false]: Assertion `cudaGetLastError() == cudaSuccess' failed.
Aborted (core dumped)`

I started it again, and this time the server started successfully, but it took 9.7 minutes to start.

Here's the code I'm using to export the model: https://gist.github.com/Panaetius/9ea02b58883bbacd64cac772d92f53c5

Why does tensorflow_model_server sometimes fail loading this model and why does starting a GPU instance of tensorflow_model_server take so much longer than running on CPU or running on GPU in regular tensorflow?

**Comment by drewswinney** [comment] 2017-12-18 21:44
I am having this exact same issue. I can load 20 smallish models (the .pb files are extremely small) in about 3 seconds using tensorflow-serving built with CPU, but when I load these using the GPU version it can take up to 20 minutes to start. 

Any explanation as to why this is happening would be greatly appreciated.

**Comment by gautamvasudevan** [comment] 2018-08-03 20:01
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 20:01 UTC
