### ISSUE TITLE
gRPC API: HandleReloadConfigRequest() return Deadline Exceeded

### ISSUE THREAD

**Issue by rush9838465** [tensorflow/serving#1447] opened 2019-09-26 08:54 UTC
Suppose I load a model that doesn't exist locally, and TFS starts printing errors:
`E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:362] FileSystemStoragePathSource encountered a filesystem access error: Could not find base path ...`

And then when I call the HandleReloadConfigRequest() again, Keep reporting errors:
```
I0926 15:55:17.991882  3816 modelmanagement.py:93] <_Rendezvous of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1569484477.115000000","description":"Error received from peer ipv4:172.16.2.8:8500","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"Deadline Exceeded","grpc_status":4}"
```

**Comment by gowthamkpr** [comment] 2019-09-26 21:01
@rush9838465 Whare are you saving your model? Can you also share some reproducable code for us to reproduce the issue? Thanks!

**Comment by rush9838465** [comment] 2019-09-27 03:01
I am ready to launch my model on TFS. If the user gives me the wrong model path, I use HandleReloadConfigRequest() configuration to TFS will report this error.
Later, even if the user gives me the correct configuration, I will call HandleReloadConfigRequest() again and keep reporting errors.
HandleReloadConfigRequest() will stop reporting errors unless I put a .pd file in the wrong path.

from tensorflow_serving.apis import model_service_pb2_grpc
from tensorflow_serving.apis import model_management_pb2, get_model_status_pb2
from tensorflow_serving.config import model_server_config_pb2
import grpc
import os

```
# add a model to TFS
models = {"model_name": "CNN",
          "model_platform": "tensorflow",
          "model_version": 1,
          }
channel = grpc.insecure_channel("192.168.0.2:8500")
stub = model_service_pb2_grpc.ModelServiceStub(channel)
request = model_management_pb2.ReloadConfigRequest()
# request_status = get_model_status_pb2.GetModelStatusRequest()

config_content = open("./models.config", "r").read()
model_server_config = model_server_config_pb2.ModelServerConfig()
config_list = model_server_config_pb2.ModelConfigList()
new_config = config_list.config.add()
new_config.name = models["model_name"]
new_config.base_path = os.path.join("./models/pd", models["model_name"]).replace("\\", "/")
new_config.model_platform = models["model_platform"]
new_config.model_version_policy.specific.versions.extend([models["model_version"]])  # 1

model_server_config.model_config_list.MergeFrom(config_list)
request.config.CopyFrom(model_server_config)
request.IsInitialized()
request.ListFields()
request_response = stub.HandleReloadConfigRequest(request, 3)
if request_response.status.error_code == 0:
    with open("./models.config", "w") as fd:
        fd.write(str(request.config))

```

**Comment by gowthamkpr** [comment] 2019-10-02 00:11
Can you please take a look at this [issue](https://stackoverflow.com/questions/54440762/tensorflow-serving-update-model-config-add-additional-models-at-runtime) and let me know if it helps. Thanks!

**Comment by rush9838465** [comment] 2019-10-08 02:24
> Can you please take a look at this [issue](https://stackoverflow.com/questions/54440762/tensorflow-serving-update-model-config-add-additional-models-at-runtime) and let me know if it helps. Thanks!

I did. I didn't have the answer

**Comment by unclepeddy** [comment] 2019-10-09 22:45
Can you clearly explain 1) What you're doing 2) What the observed outcome is and 3) What the expected outcome is? 


It sounds like you're _adding_ new models, not replacing them. So the behavior is expected? Should you be replacing the model in the config file with a new one instead of adding it?

**Comment by rmothukuru** [comment] 2019-11-08 06:24
@rush9838465,
Can you please respond to @unclepeddy's comments. Thanks!

**Comment by rmothukuru** [comment] 2019-11-15 09:44
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2019-11-15 09:44 UTC
Labels: stat:awaiting response, type:support

**Comment by namjals** [comment] 2020-03-05 00:31
This problem is reproduced. The code is shown below. I need help.
# docker run script
docker run -t --rm -d \
-p 8501:8501 \
-p 8500:8500 \
-v "{model_path}:/models/" --name serving tensorflow/serving --model_config_file={config_path} --model_config_file_poll_wait_seconds=10

# config file
model_config_list: {
   config: {
    name:  "model",
    base_path:  "{not exsist path}",
    model_platform: "tensorflow",
  }
}

# tensorflow serving error log
FileSystemStoragePathSource encountered a filesystem access error: Could not find base path {not exist path} for servable model

# python, reload script by grpc
hostport = 'localhost:8500'
path = {config_path}
with open(path, "r") as f:
    config_ini = f.read()
model_server_config = model_server_config_pb2.ModelServerConfig()
model_server_config = text_format.Parse(text=config_ini, message=model_server_config)
channel = grpc.insecure_channel(hostport)
stub = model_service_pb2_grpc.ModelServiceStub(channel)
request = model_management_pb2.ReloadConfigRequest()
request.config.CopyFrom(model_server_config)
response = stub.HandleReloadConfigRequest(request, 10)
if response.status.error_code == 0:
    print("Reload done")
