### ISSUE TITLE
Batched output tensor's 0th dimension does not equal the sum of the 0th dimension sizes of the input tensors

### ISSUE THREAD

**Issue by anandanand84** [tensorflow/serving#276] opened 2016-12-15 16:58 UTC
Batched output tensor's 0th dimension does not equal the sum of the 0th dimension sizes of the input tensor error occurs when using the tensorflow model_server PredictionService. Below is my export variables in python.

```
    imagesize = 400;
    x = tf.placeholder(tf.float32, [None, imagesize], name="x_placeholder")
    y = tf.placeholder(tf.float32, [None, labelscount], name="y_placeholder")
```

### Inference

```
    pred = conv_net(x, weights, biases, keep_prob)
    actual = tf.cast(tf.argmax(pred, 1), tf.int32); 
    output = tf.reshape(tf.gather(availableClasses, actual), [-1,1])
    probability = tf.reshape(tf.reduce_max(tf.nn.softmax(pred), 1), [-1,1])
```
### Export
```
    export_saver = tf.train.Saver(sharded=True)
    model_exporter = exporter.Exporter(export_saver)
    model_exporter.init(sess.graph.as_graph_def(), named_graph_signatures={
        'inputs': exporter.generic_signature({'images': x}),
        'outputs': exporter.generic_signature({'classes': output , 'probability' : probability})})
    model_exporter.export(export_path, tf.constant(export_version), sess)
```

The inferance happens fine without batching(--enable-batching), but when batching is enabled it fails with error mentioned below.

```
    { Error: Batched output tensor's 0th dimension does not equal the sum of the 0th dimension sizes of the input tensors
        at /Users/anandmac/dev/projects/serving-client/node_modules/grpc/src/node/src/client.js:417:17 code: 9, metadata: Metadata { _internal_repr: {} } }
```

Below is the grpc proto used to call the predict.

```
    {
        model_spec: { name: 'patterndetector' },
        inputs: {
            images: {
            dtype: 'DT_FLOAT',
            tensor_shape: {
                dim: {
                    size : 1 # I have tried 0, 1 , -1 without any luck
                },
                dim: {
                    size: values.length
                }
            },
            float_val: values
            }
        }
    };
```
When I run it in python without tensorflow-model-server and print the shape of input, output and probability 
I get the below result which has the same dimension in 0th place

```
    result, prob =  sess.run([output, probability], feed_dict={x: batch_xs, keep_prob : 1.0} );
    print(tf.constant(np.zeros([10,400])).get_shape()); #(10, 400)
    print(result.shape); #(10, 1)
    print(prob.shape); #(10, 1)
```

 what does the error message mean if it occurs even if the dimension are correct.

**Comment by chrisolston** [comment] 2016-12-15 17:15
In TF-Serving, batching works by concatenating multiple input tensors along the 0th dimension (which is assumed to be the batch-size dimension), then calling Session::Run() on the concatenated tensor(s), and then splitting the resulting tensor(s). This only works if the resulting tensor's 0th dimension size equals the sum of the 0th-dimension sizes of the input tensors. A common case has each input tensor having 0th-dimension size 1, in which case what's happening is that TF-Serving concatenates N tensors into a tensor with dimensions [N, ...], and then running Session::Run(), and then receiving a tensor with dimension [not N, ...] -- so it doesn't know how to attribute the output entries (which output corresponds to which input?).

Perhaps your graph is not maintaining the 0th dimension constant (i.e. always N) throughout the graph?

**Comment by anandanand84** [comment] 2016-12-15 18:40
I did try to send 800(400 is one set) float values from a nodejs grpc client to the same model-server predictionservice and able to get back 2 outputs, so If performed batching from client(nodejs) by concatenating tensors it does work. But if I send multiple request with 400 values to the server it comes back with this error.  So should this be a bug with model server or still something in my graph causes this issue?

**Comment by chrisolston** [comment] 2016-12-15 18:51
The batching code has been pounded on quite a bit so if there was a basic bug in there like that I think we would have found it already. That said, we *just* pushed an update to the batching code 6 days ago, so if you're living on the bleeding edge that could explain it. The change I'm referring to is https://github.com/tensorflow/serving/commit/c28f2982ef7df2a06c46157f9a5cea9979cf1022.

**Comment by anandanand84** [comment] 2016-12-15 19:11
No the build I am using doesn't have that change. The commit of the build is https://github.com/tensorflow/serving/commit/a7d6daff24b786a7c3fa1f4ee2eb259c3a941652. Just to clarify batching does allow multiple outputs with one input  like below right
```
model_exporter.init(sess.graph.as_graph_def(), named_graph_signatures={
        'inputs': exporter.generic_signature({'images': x}),
        'outputs': exporter.generic_signature({'classes': output , 'probability' : probability})})
```

**Comment by chrisolston** [comment] 2016-12-15 19:23
Since you're using the build before that change, then my best guess is that it's something in your model. Often we have seen that folks leave some asynchronous op in their model e.g. a queue, which makes the output size not match the input size for a given Run() call (some outputs may be buffered in a queue, for example).

Yes, the batching does support having multiple output tensors like classes & probability.

**Comment by anandanand84** [comment] 2016-12-17 17:39
@chrisolston I tried to simplify my use case to understand how the batching works, below is the simple model that exactly represents my model, even for this use case the batching doesnt work and I get the same error I get for my model. I believe this should be something related to the input size and how serving handles batch during those scenario. Can you let me know what is wrong with this model? You can take a look at the working python invocation of model and not working model-server in this ide http://seaof-153-125-234-179.jp-tokyo-10.arukascloud.io:31141/ide.html I have more details on the instructions.md. I am new to tensorflow serving and machine learning so I might have made a basic mistake as well.

```
import numpy as np
import tensorflow as tf
from tensorflow.contrib.session_bundle import exporter
flags = tf.app.flags
FLAGS = flags.FLAGS
flags.DEFINE_boolean('export', False,
                     'If False predicts the pattern from the given imagedata, else train from the existing data'); 

classes          = np.array(['A','B','C','D','E','F','G','H'])
labelscount      = len(classes)
imagesize        = 400;
availableClasses = tf.constant(classes, shape=[labelscount,1], dtype=tf.string);

x = tf.placeholder(tf.float32, [None, imagesize], name="x_placeholder")
W = tf.Variable(tf.zeros([imagesize, labelscount]))
b = tf.Variable(tf.zeros([labelscount]))
pred = tf.nn.softmax(tf.matmul(tf.reshape(x, [-1,400]), W) + b)

init = tf.initialize_all_variables()

saver = tf.train.Saver();

sess = tf.Session();

sess.run(init)

actual = tf.cast(tf.argmax(pred, 1), tf.int32); 
output = tf.reshape(tf.gather(availableClasses, actual), [-1,1])
probability = tf.reshape(tf.reduce_max(tf.nn.softmax(pred), 1), [-1,1])

def export_model(sess, export_path, export_version, x, y , probability):
    export_saver = tf.train.Saver(sharded=True)
    model_exporter = exporter.Exporter(export_saver)
    model_exporter.init(sess.graph.as_graph_def(), named_graph_signatures={
        'inputs': exporter.generic_signature({'images': x}),
        'outputs': exporter.generic_signature({'classes': y , 'probability' : probability})})
    model_exporter.export(export_path, tf.constant(export_version), sess)
    print("Export Finished!")

def test():
    batch_xs = np.zeros([10,400])
    result, prob =  sess.run([output, probability], feed_dict={x: batch_xs} );
    print('batch xs shape', batch_xs.shape)
    print('Result shape:', result.shape)
    print('probability shape:', prob.shape)
    print('result ', result);
    print('prob ', prob);
if FLAGS.export:    
    export_model(sess, '/model/', 1 , x , output, probability)
else:
    test()
```

**Comment by gautamvasudevan** [comment] 2018-08-03 20:11
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 20:11 UTC
