### ISSUE TITLE
Should prometheus exporter use ':' in metric names?

### ISSUE THREAD

**Issue by pnsantos** [tensorflow/serving#1690] opened 2020-07-15 15:32 UTC
## Bug Report

Prometheus exporter using `:` when it's stated that colons shouldn't be used by exporters.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: `tensorflow/serving:2.2.0-gpu`
- **TensorFlow Serving installed from (source or binary)**: docker image
- **TensorFlow Serving version**: `2.2.0`

### Describe the problem

Prometheus documentation says the following about metric names (emphasis mine):

> The metric name specifies the general feature of a system that is measured (e.g. `http_requests_total` - the total number of HTTP requests received). It may contain ASCII letters and digits, as well as underscores and colons. It must match the regex `[a-zA-Z_:][a-zA-Z0-9_:]*`.
>
> Note: **The colons are reserved for user defined recording rules. They should not be used by exporters or direct instrumentation**.
> 
_source: [Metric Names and Labels](https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels)_

and then about exporters:

> Exposed metrics **should not contain colons**, these are reserved for user defined recording rules to use when aggregating.

_source: [Writing Exporters / Naming](https://prometheus.io/docs/instrumenting/writing_exporters/#naming)_

I guess changing this now would break people's queries but it seems to be against standard recommendations... Maybe it could be added as an option in the prometheus config to replace `:` with say `_`?

### Exact Steps to Reproduce

1) Run tensorflow/serving with prometheus metrics enabled.
2) Call the exporter endpoint 
3) Metric names will have `:` in them

### Source code / logs

Example:
```
:tensorflow:cc:saved_model:load_attempt_count{model_path="..."} 1
```

**Comment by minglotus-6** [comment] 2020-07-31 16:39
Hi Pedro,
  TF and TF serving exports metrics consisting of "/" ([source code](https://github.com/tensorflow/tensorflow/blob/74408f404a1c22ece5f17e94dc588c8a8337b9bb/tensorflow/cc/saved_model/loader.cc#L42) where `:tensorflow:cc:saved_model:load_attempt_count{model_path="..."} 1` is defined. [Prometheus forum](https://github.com/prometheus/prometheus) might be a good place to follow up on how ":" are added.

  Also, regarding `adding an option in the prometheus config to replace : with say _`, is it a supported use case of  Prometheus already?

**Comment by pnsantos** [comment] 2020-08-04 18:55
I did some follow up and I suspect it's the scraper that is replacing the `/` with `:`

 I am curious about why `/` are used vs `_` (from what I know prom metrics tend to be separated by `_`)

Anyway feel free to close this, I might have been a little hasty in opening it ^_^

**Comment by minglotus-6** [comment] 2020-08-04 18:58
Thanks for following up! Going to close it if the issue is not blocking anything.

Curiously, what's the solution / workaround?

**Closed by minglotus-6** 2020-08-04 18:58 UTC
Labels: stat:awaiting tensorflower, type:support

**Comment by pnsantos** [comment] 2020-08-06 15:23
So in practice the `:` seem to prevent grafana from listing them in the drop-downs (pretty sure this is an issue with config but I haven't had time to dig into it), however when writing the queries auto-complete does list them so it's not too bad. The metrics _are_ functional so this was more of a technical detail curiosity about the use of `:`.

From what I can tell TF (or TF service) somewhere is replacing the `/` with `:` because when you query the configured metrics endpoint the metric names are already with `:` but I am no C++ expert so I can't point to where that is being done.

In the end it is only a should 
> Note: The colons are reserved for user defined recording rules. They should not be used by exporters or direct instrumentation.
not a must so I just though I'd ask (in case it was unintended)
