### ISSUE TITLE
Docker tf-serving gets error: curl: (52) Empty reply from server

### ISSUE THREAD

**Issue by YoungXu06** [tensorflow/serving#1646] opened 2020-05-28 08:47 UTC
I follow the tool docker deploying example:
![image](https://user-images.githubusercontent.com/14051806/83120120-31c21c00-a103-11ea-9220-fa06a777a8b9.png)

After runing the `half_plus_two`  model, I use `curl -d "{"instances": [1.0, 2.0, 5.0]}" -X POST http://localhost:8501/v1/models/half_plus_two:predict` to predict, and got this: `curl: (52) Empty reply from server` or `curl: (7) Failed connect to localhost:8501; Connection refused` sometimes.

I tried in Win10, Mac and linux plateform with different tf-serving versions, all failed...  I've struggled for days, anyone can help plz? Thanks advance!

**Comment by gowthamkpr** [comment] 2020-05-29 06:35
I was able to run this using the latest version of tf-serving image on ubuntu(linux). 
![image](https://user-images.githubusercontent.com/47574994/83228469-415d5700-a13b-11ea-849d-f7fc53d9182f.png)
![image](https://user-images.githubusercontent.com/47574994/83228397-1e32a780-a13b-11ea-9c4a-47290740a9c6.png)
I am not sure what error you are running into. This is not an issue with Tensorflow serving as the port forwarding is not happening in your case. I am not sure why this is happening

**Comment by gowthamkpr** [comment] 2020-06-02 16:04
@YoungXu06 Are you still running into this issue?

**Comment by gowthamkpr** [comment] 2020-06-04 23:49
Closing this issue as it it not a bug. Please add additional comments for us to open this issue again. Thanks!

**Closed** 2020-06-04 23:49 UTC
Labels: stat:awaiting response, type:support

**Comment by C-Compton** [comment] 2021-06-28 14:11
I'm getting this issue running tf-serving 2.5.0-rc3 

OS: macOS 11.4. 
Docker: 20.10.6

Container output indicates it successfully loaded the model. 
> 2021-06-28 14:06:36.116454: I tensorflow_serving/core/loader_harness.cc:87] Successfully loaded servable version {name: pushed_model version: 9}
2021-06-28 14:06:36.118419: I tensorflow_serving/model_servers/server_core.cc:486] Finished adding/updating models
2021-06-28 14:06:36.118483: I tensorflow_serving/model_servers/server.cc:367] Profiler service is enabled
2021-06-28 14:06:36.119558: I tensorflow_serving/model_servers/server.cc:393] Running gRPC ModelServer at 0.0.0.0:8500 ...
[warn] getaddrinfo: address family for nodename not supported
2021-06-28 14:06:36.122075: I tensorflow_serving/model_servers/server.cc:414] Exporting HTTP/REST API at:localhost:8501 ...
[evhttp_server.cc : 245] NET_LOG: Entering the event loop ...

However, 
> curl  -G http://localhost:8505/v1/models/pushed_model
curl: (52) Empty reply from server
