### ISSUE TITLE
Using a fraction of GPU memory for each model

### ISSUE THREAD

**Issue by dakshvar22** [tensorflow/serving#675] opened 2017-12-01 05:42 UTC
Hi,

I have one GPU at my disposal for deployment but multiple models need to be deployed. I don't want to allocate the full GPU memory to the first deployed model because then I can't deploy my subsequent models. While training, this could be controlled using `gpu_memory_fraction` parameter.
I am using the following command to deploy my model - 

`tensorflow_model_server --port=9000 --model_name=<name of model> --model_base_path=<path where exported models are stored &> <log file path>`

Is there a flag that I can set to control the gpu memory allocation?

Thanks

**Comment by chrisolston** [comment] 2017-12-11 13:57
This is a dupe of https://github.com/tensorflow/serving/issues/249

**Closed by chrisolston** 2017-12-11 13:57 UTC
Labels: duplicate
