### ISSUE TITLE
Error: grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.NOT_FOUND, details="Servable not found for request: Latest(inception)

### ISSUE THREAD

**Issue by Pokharaa** [tensorflow/serving#750] opened 2018-02-02 09:51 UTC
I am using tensorflow for poets data for tensorflow for serving.
When I am trying to predict the image I got the following error in ubuntu :
Error: 
pb@ubuntu:~/Downloads/cadrecok$ python client.py --server=172.17.0.3:9000 image=./testdata/washer1.JPG
Traceback (most recent call last):
  File "client.py", line 48, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "client.py", line 43, in main
    result = stub.Predict(request, 60.0)  # 60 secs timeout
  File "/home/pb/.local/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 310, in __call__
    self._request_serializer, self._response_deserializer)
  File "/home/pb/.local/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 196, in _blocking_unary_unary
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.NOT_FOUND, details="Servable not found for request: Latest(inception)")

The code in the client.py is:
**# Command line arguments 
tf.app.flags.DEFINE_string('server', 'localhost:9000',  'PredictionService host:port') 
tf.app.flags.DEFINE_string('image', '', 'path to image in JPEG format') 
FLAGS = tf.app.flags.FLAGS 
 
def main(_): 
    host, port = FLAGS.server.split(':') 
    channel = implementations.insecure_channel(host, int(port)) 
    stub = prediction_service_pb2.beta_create_PredictionService_stub(channel) 

    # Send request 
    with open(FLAGS.image, 'rb') as f: 

        # See prediction_service.proto for gRPC request/response details. 
        data = f.read() 
        request = predict_pb2.PredictRequest() 
 
        # Call model to make prediction on the image 
        request.model_spec.name = 'inception' 
        #request.model_spec.signature_name = 'predict_images' 
        request.inputs['images'].CopyFrom( 
            tf.contrib.util.make_tensor_proto(data, shape=[1])) 
 
        result = stub.Predict(request, 60.0)  # 60 secs timeout 
        print(result) 

if __name__ == '__main__': 
    tf.app.run()**

I couldn't figure out the problem.
Help me please.

**Comment by chrisolston** [comment] 2018-02-05 20:30
The error means the server could not find a loaded model called "inception", so either the model name in the requests doesn't match the name on the server, or it isn't loaded, or perhaps it's in the process of loading. You can check the server logs to see the status in terms of loading/loaded and what the model name is.

**Comment by Pokharaa** [comment] 2018-02-22 01:48
Hope this tutorial might help to solve the above problem.
https://www.youtube.com/watch?v=SsaJJsRvwIs

**Comment by B1tMaster** [comment] 2018-03-19 16:39
@chrisolston Hi. thank you for your insights. Very helpful.

I have same issue and it does look as my model name is "default" , that explains the error. But how do I set the model name to be something other than default?  I don't there was an option during re-training to set model name.. There was an option to set name for last hidden layer.  Any advise?

server:
```
018-03-19 16:25:10.380947: I tensorflow_serving/core/loader_harness.cc:86] Successfully loaded servable version {name: default version: 1}
2018-03-19 16:25:10.383243: I tensorflow_serving/model_servers/main.cc:316] Running ModelServer at 0.0.0.0:9000 ...
```

client:

```
raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.NOT_FOUND, details="Servable not found for request: Latest(inception)")

```

**Comment by B1tMaster** [comment] 2018-03-19 16:55
@chrisolston Hi. 
I have a slightly different issue with my inception client. It can't find SignitureDef "predict_images". 
I confirmed with cli tools that my SignatureDef is "default_serving" . which is the one that retrain.py is using.. Do you know how can I force "predict_images" in my SavedModel during re-training? 
or how to have the serving to change the key, so it can found?

Inspection of my SavedModel: 
(```
tensorflow) SonicMac:tensorflow davramenko$ saved_model_cli show --dir /tmp/saved_models/1 --tag_set serve
The given SavedModel MetaGraphDef contains SignatureDefs with the following keys:
SignatureDef key: "serving_default"
```

Error I get when running the inception_client.py : 
```
le "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 195, in _blocking_unary_unary
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.FAILED_PRECONDITION, details="Serving signature key "predict_images" not found.")

```

**Comment by gautamvasudevan** [comment] 2018-08-03 20:17
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 20:17 UTC
