### ISSUE TITLE
Something is wrong when I try to bazel build tensorflow_serving

### ISSUE THREAD

**Issue by xvdehao** [tensorflow/serving#607] opened 2017-09-28 02:55 UTC
Hi，I have a problem when I tried to bazel build tensorflow serving as follows.
It looks like I cannot enter the git.com?
Any suggestion is so helpful to me who is a really freshman, thanks.
![image](https://user-images.githubusercontent.com/31030801/30947283-735eb3a2-a43b-11e7-8ea5-849aa1ae066a.png)

**Comment by kirilg** [comment] 2017-10-02 19:40
It seems you're able to clone TensorFlow serving and TensorFlow which is a dependency. Might have been a transient error connecting to github.com for that package. Is this still happening? If so, did you make any changes locally or does `git status` show a clean unmodified local repo?

**Comment by gautamvasudevan** [comment] 2018-08-03 20:16
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 20:16 UTC
