### ISSUE TITLE
rest_simple.ipynb tutorial is broken

### ISSUE THREAD

**Issue by andres-zartab** [tensorflow/serving#2012] opened 2022-06-13 19:35 UTC
## Bug Report
If this is a bug report, please fill out the following form in full:

Running this [tutorial](https://www.tensorflow.org/tfx/tutorials/serving/rest_simple) in Google colab fails due to some GLIBC errors.

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow Serving installed from (source or binary)**:
- **TensorFlow Serving version**:

Platform: Google colab
The notebook was ran exactly as it is (no changes made).

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in
TensorFlow Serving.

I would not say this is a TF Serving bug per se but a bug in the tutorial.

Server fails to spin up. `server.log` has this info:

```
tensorflow_model_server: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by tensorflow_model_server)
tensorflow_model_server: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by tensorflow_model_server)
tensorflow_model_server: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by tensorflow_model_server)
```

### Exact Steps to Reproduce
Please include all steps necessary for someone to reproduce this issue on their
own machine. If not, skip this section.

Just running the tutorial in google colab.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached. Try to provide a reproducible test case that is the bare
minimum necessary to generate the problem.

**Comment by Tayge** [comment] 2022-06-17 08:09
Hello! Just install this version of tensorflow-model-server and everything will work.

```
!wget 'http://storage.googleapis.com/tensorflow-serving-apt/pool/tensorflow-model-server-universal-2.8.0/t/tensorflow-model-server-universal/tensorflow-model-server-universal_2.8.0_all.deb'
!dpkg -i tensorflow-model-server-universal_2.8.0_all.deb
```

As far as I understand, versions of tensorflow-model-server 2.8.2 and 2.9.0 require newer ones GLIBC.

**Comment by andres-zartab** [comment] 2022-06-17 15:38
I can confirm this works. Thanks @Tayge! :)

**Comment by pindinagesh** [comment] 2022-06-20 04:43
Hi @andres-zartab 

Could you please move this issue to closed status if it works. Thanks!

**Comment by Forpee** [comment] 2022-07-21 11:59
The tutorial is also broken for me but not for GLIBC errors.

The notebook was run exactly as it is (no changes made).

And I get this error

`---------------------------------------------------------------------------
ConnectionRefusedError                    Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/urllib3/connection.py](https://localhost:8080/#) in _new_conn(self)
    158             conn = connection.create_connection(
--> 159                 (self._dns_host, self.port), self.timeout, **extra_kw)
    160 

19 frames
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)
NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fa196602550>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
MaxRetryError: HTTPConnectionPool(host='localhost', port=8501): Max retries exceeded with url: /v1/models/fashion_model:predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa196602550>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/requests/adapters.py](https://localhost:8080/#) in send(self, request, stream, timeout, verify, cert, proxies)
    514                 raise SSLError(e, request=request)
    515 
--> 516             raise ConnectionError(e, request=request)
    517 
    518         except ClosedPoolError as e:

ConnectionError: HTTPConnectionPool(host='localhost', port=8501): Max retries exceeded with url: /v1/models/fashion_model:predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa196602550>: Failed to establish a new connection: [Errno 111] Connection refused'))`

**Comment by gaikwadrahul8** [comment] 2022-11-09 20:58
@Forpee, @andres-zartab 

It seems like duplicate issue like https://github.com/tensorflow/serving/issues/2054 and As workaround please comment this line : `!{SUDO_IF_NEEDED} apt-get install tensorflow-model-server` line and add below 03 lines of command to install Tensorflow serving 2.8.0 in section : Install TensorFlow Serving

```
!wget` 'http://storage.googleapis.com/tensorflow-serving-apt/pool/tensorflow-model-server-2.8.0/t/tensorflow-model-server/tensorflow-model-server_2.8.0_all.deb'
!dpkg -i tensorflow-model-server_2.8.0_all.deb
!pip3 install `tensorflow-serving-api==2.8.0
```

Sharing the working [gist file](https://colab.research.google.com/gist/gaikwadrahul8/94387f4ce95bd0dffb0639bb5b8bff70/rest_simple.ipynb) for reference. Can you please close this issue, since it is already being tracked on https://github.com/tensorflow/serving/issues/2054.

Thank you!

**Closed** 2022-11-09 21:16 UTC
Labels: stat:awaiting response, type:bug
