### ISSUE TITLE
ImportError: No module named 'gflags_validators'

### ISSUE THREAD

**Issue by YMMS** [tensorflow/serving#568] opened 2017-08-21 02:06 UTC
Hi, when I complied serving when bazel under nvidia-docker, I got error as below:

```
ERROR: /root/serving/tensorflow_serving/model_servers/BUILD:181:1: error executing shell command: 'bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/build_tar --flagfile=bazel-out/local-opt/bin/tensorflow_serving/model_servers/tensorflow_model_server_tar.args' failed (Exit 1)
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/01a289b7faaf5ec651fb0e4e35f862a1/execroot/tf_serving/bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/build_tar.runfiles/tf_serving/../bazel_tools/tools/build_defs/pkg/build_tar.py", line 23, in <module>
    from third_party.py import gflags
  File "/root/.cache/bazel/_bazel_root/01a289b7faaf5ec651fb0e4e35f862a1/execroot/tf_serving/bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/build_tar.runfiles/bazel_tools/third_party/py/gflags/__init__.py", line 409, in <module>
    import gflags_validators
ImportError: No module named 'gflags_validators'
INFO: Elapsed time: 537.655s, Critical Path: 62.62s
FAILED: Build did NOT complete successfully
```

When I search the solution, some suggestion mentioned I need to install `python-gflags`, but it doesn't work.

**Comment by jiyonghe** [comment] 2017-08-29 02:29
the same question for me

**Comment by YMMS** [comment] 2017-08-30 04:28
It seems that python3 and cuda still don't work. Now I used the **TensorFlow Serving ModelServer binary** to start server, and use **tensorflow-serving-api** to make client. But the **tensorflow-serving-api** seems only support python2 and CPU.

**Comment by chrisolston** [comment] 2017-09-05 17:28
Currently our pip package only supports python 2. We are looking into adding python 3 support.

**Comment by virtualdvid** [comment] 2017-10-26 02:12
Once you install `pip install python-gflags` , you need to copy the missing file `gflags_validators` from google_appengine: 
> C:\Program Files (x86)\Google\Google_Appengine\lib\python-gflags

and paste or replace if it is necessary in the main library folder:

> C:\Python27\Lib\site-packages\gflags 

Here is the link to a video that I made on the topic:

[How to fix: python-gflags errors in Google Analytics API](https://youtu.be/fCgVlEZByi4)

**Comment by gautamvasudevan** [comment] 2018-08-03 20:00
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 20:00 UTC
