### ISSUE TITLE
EfficientDet model from google/autoML not working in tensorflow serve due missing OP moving_variance

### ISSUE THREAD

**Issue by digital-thinking** [tensorflow/serving#1757] opened 2020-10-23 16:03 UTC
Hello,

I wanted to deploy [EfficientDet ](https://github.com/google/automl/tree/master/efficientdet) with tensorflow serving and have the following error, when the server wants to load the model:

> 
>  E external/org_tensorflow/tensorflow/core/common_runtime/executor.cc:654] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'allowed_devices' not in Op<name=VarHandleOp; signature= -> resource:resource; attr=container:string,default=""; attr=shared_name:string,default=""; attr=dtype:type; attr=shape:shape; is_stateful=true>; NodeDef: {{node efficientnet-b6/blocks_5/tpu_batch_normalization_2/moving_variance}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
         [[efficientnet-b6/blocks_5/tpu_batch_normalization_2/moving_variance]]

Seems like the OP is missing:
**efficientnet-b6/blocks_21/tpu_batch_normalization_2/moving_variance**

Any ideas how to fix this?

Version: TensorFlow 2.3 with Python3 (CUDA 10.2 and Intel MKL-DNN)

**Comment by gowthamkpr** [comment] 2020-10-23 17:23
@digital-thinking What version of tensorflow serving are you using?

**Comment by digital-thinking** [comment] 2020-10-23 17:30
@gowthamkpr 2.3.0

**Comment by BorhenJlidi** [comment] 2020-10-23 22:32
@digital-thinking to use custom ops in tensorflow serving you should build a TF serving image with these ops. For more details refer to https://www.tensorflow.org/tfx/serving/custom_op

**Comment by digital-thinking** [comment] 2020-10-23 23:17
@BorhenJlidi Thanks for your response. I see that it's possible to build a customized version. But I guess it's not really a solution for the most people (using prebuild optimized containers and images). I just wondered because the EfficientDet implementation is also from Google and provides a way to build the savedModel for serving. So I was thinking, there might be some trick to get it working without building the hole server manually.

**Comment by BorhenJlidi** [comment] 2020-10-23 23:46
@digital-thinking Believe me, I thought so too :laughing: 
"Building the whole server manually" seems like reasonable solution for them, I don't think they're going to make an exception for EfficientDet.

**Comment by gowthamkpr** [comment] 2020-11-02 17:56
@digital-thinking For now, as mentioned by @BorhenJlidi , thats the only option we have.

**Comment by lilao** [comment] 2020-11-02 18:14
The error seems to indicate that the attribute 'allowed_devices' defined in the SavedModel is invalid for the op. It does not seem to be caused by missing op. Can you double check if allowed_devices is a valid attribute for moving_variance? If so, it might be a Tensorflow forward compatibility issue (https://www.tensorflow.org/guide/versions#backward_and_partial_forward_compatibility), i.e., the graph is produced by a version of tensorflow that is newer than tensorflow serving, the consumer of the graph.

**Comment by rmothukuru** [comment] 2020-11-28 10:24
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2020-11-28 10:24 UTC
Labels: stat:awaiting response, type:support
