### ISSUE TITLE
tensorflow serving for cifar model raise grpc.framework.interfaces.face.face.AbortionError when using client to inference the test data

### ISSUE THREAD

**Issue by terryKing1992** [tensorflow/serving#503] opened 2017-06-27 08:04 UTC
## System
```
   CentOS 7.1
   bazel : 0.4.5
   Tensorflow: 1.2.0
   tensorflow serving: latest
```
---
## Issue:

I have trained the cifar10 model using tensorflow on spark, and save model using the follow code snippet(i cut down some unimportant code, eg: training step):

```python
x = tf.placeholder(tf.float32, shape=[None, 32, 32, 3],
                                    name='images')
y = tf.placeholder(tf.float32, shape=[None, 10], name='image-labels')

ignore train step...

local_model_dir = "/tmp/" + current_user + "/" + model_name + "/" + str(version)

classification_inputs = utils.build_tensor_info(x)
classification_outputs_classes = utils.build_tensor_info(y)

classification_signature = signature_def_utils.build_signature_def(
    inputs={signature_constants.CLASSIFY_INPUTS: classification_inputs},
    outputs={
        signature_constants.CLASSIFY_OUTPUT_CLASSES:
            classification_outputs_classes
    },
    method_name=signature_constants.CLASSIFY_METHOD_NAME)
tensor_info_x = utils.build_tensor_info(x)
tensor_info_y = utils.build_tensor_info(y)
prediction_signature = signature_def_utils.build_signature_def(
    inputs={'inputs': tensor_info_x},
    outputs={'outputs': tensor_info_y},
    method_name=signature_constants.PREDICT_METHOD_NAME)
legacy_init_op = tf.group(tf.tables_initializer(), name='legacy_init_op')

if os.path.exists(local_model_dir):
    shutil.rmtree(local_model_dir)

builder = saved_model_builder.SavedModelBuilder(local_model_dir)
builder.add_meta_graph_and_variables(
    sess, [tag_constants.SERVING],
    signature_def_map={
        'prediction_signature':
            prediction_signature,
        signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY:
            classification_signature,
    },
    clear_devices=True, legacy_init_op=legacy_init_op)
builder.save()
```
and I use 

```
bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --enable_batching --port=25678 --model_name=cifar10 --model_base_path=/tmp/terryking1992/cifar10
```
the model was loaded correctly. but when i wrote client to predict the test data, something was wrong.

the client predict code is bellow:

```python
 
import numpy as np
from grpc.beta import implementations
import tensorflow as tf

from tensorflow_serving.apis import predict_pb2
from tensorflow_serving.apis import prediction_service_pb2

def predict():

    def unpickle(file):
        import cPickle
        fo = open(file, 'rb')
        dict = cPickle.load(fo)
        fo.close()
        return dict

    Xtr = unpickle('/root/data/cifar-10-batches-py/data_batch_1')

    img = np.reshape(Xtr['data'][0], (3, 32, 32))
    img = img.transpose(1, 2, 0)
    channel = implementations.insecure_channel("10.60.127.121", 25678)
    stub = prediction_service_pb2.beta_create_PredictionService_stub(channel)
    # Send request
    # See prediction_service.proto for gRPC request/response details.
    request = predict_pb2.PredictRequest()
    request.model_spec.name = "cifar10"
    request.model_spec.signature_name = "prediction_signature"
    request.inputs["inputs"].CopyFrom(
        tf.contrib.util.make_tensor_proto([img], shape=[1, 32, 32, 3]))
    result = stub.Predict(request, 10)  # 10 secs timeout

if __name__ == '__main__':
    predict()
```
 the predict client raise the error like this:

![wrongwithtensorserving](https://user-images.githubusercontent.com/22629426/27577066-e7b2157e-5b51-11e7-97ee-d68c077fbfe2.png)

is there something wrong in my code, and hope you guide me to fix this issue, or any other opinion are welcome! thanks a lot

**Comment by mm-manu** [comment] 2017-07-02 10:26
try to add `dtype=tf.float32` to the `make_tensor_proto` call in your client.

**Comment by vacing** [comment] 2018-02-28 06:28
> try to add dtype=tf.float32 to the make_tensor_proto call in your client.

very helpful !

**Comment by gautamvasudevan** [comment] 2018-08-03 20:23
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 20:23 UTC
