### ISSUE TITLE
How to convert checkpoint file to model .pb file using tf.saved_model.builder.SavedModelBuilder to host on tensorflow serving

### ISSUE THREAD

**Issue by gr8Adakron** [tensorflow/serving#897] opened 2018-05-28 17:05 UTC
Basically I have models which are already developed in Mxnet and I want to convert them into tensorflow serving format without performing retraining.

So for performing conversion from Mxnet to Tensorflow I have used this Intermediate layer created by [Microsoft Mdnn](https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/mxnet/README.md).

**Using this tool/library I was able to convert Mxnet model files to Tensorflow checkpoint format:**
![mxnet model drectories](https://user-images.githubusercontent.com/16715364/40623243-73ba9a2c-62c3-11e8-9746-d6aa3017b2b1.png)

**These are initial Mxnet model files.**
**And this is my flow of conversion.**
> ## Mxnet_model => IR format => Conversion code => Checkpoint => Tensorflow Model, Serving format

**IR = intermediate representation**
I have successfully converted till checkpoint files using this instruction [Mxnet to IR](https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/mxnet/README.md) then[ IR to Tensorflow checkpoint](https://github.com/Microsoft/MMdnn/blob/master/mmdnn/conversion/tensorflow/README.md#convert-models-from-ir-to-tensorflow-code-snippet)

**This final structure of tensorflow checkpoint file are:**
![tensorflow checkpoint](https://user-images.githubusercontent.com/16715364/40623396-762360ae-62c4-11e8-879d-8e850dc71f66.png)

The only step remaining is to convert and save these checkpoint files to **_.pb and variable folder_** format using this [SaveBuilder function](https://www.tensorflow.org/api_docs/python/tf/saved_model/builder/SavedModelBuilder) 
Saving using this function is essentials because its is the only valid format to save the model, inorder to serve the model on [tensorflow serving](https://www.tensorflow.org/serving/)

### **This is how the final structure of the converted model must look like in order to get served using TF-serving:**
![save_model_format](https://user-images.githubusercontent.com/16715364/40623657-a02c82f8-62c5-11e8-83ce-d521e35dc4da.png)

### **This is the accurate structure which TF-serving accept and generate predictions for.**

I tried using these scripts [freeze_graph.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py) and [incepiton_save_model.py](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_saved_model.py) but nothing came out they have some arguments which I don't have files to pass.

**Help!!!**
Is there a way? I am trying since last 3days but couldn't find anything. 
Thanks in advance.

**Comment by Johnson-yue** [comment] 2018-09-06 07:50
hi, I have the same question!!  
I have checkpoint files like:(data-0000-of-0001, index,  .meta), I want to convert them to tf serving use. 
the format is (saved_model.pb,  variables, variables.data-0000-of-0001, variabels/variables.index)
Do you fix it??

**Comment by elvys-zhang** [comment] 2018-09-14 04:07
Use imagenet1k-resnet-50 as example:
`mmdownload -f mxnet -n imagenet1k-resnet-50 -o ./`  
`mmtoir -f mxnet -n resnet-50-symbol.json -w resnet-50-0000.params -d resnet50 --inputShape 3 224 224`  
`mmtocode -f tensorflow --IRModelPath resnet50.pb --IRWeightPath resnet50.npy -d tf_resnet50.py `  
`mmtomodel -f tensorflow -in tf_resnet50.py -iw resnet50.npy -o tf_resnet50 --dump_tag SERVING  `

Final structure:  
![image](https://user-images.githubusercontent.com/39507256/45529207-8da51e00-b816-11e8-8700-5e6bcb70a0de.png)

It worked fine, and no need to convert mxnet to tf ckpt. Hope it will help.

**Comment by wt-huang** [comment] 2018-10-12 00:57
Closing as the issue is resolved.

**Closed by wt-huang** 2018-10-12 00:57 UTC

**Comment by YB221** [comment] 2021-07-02 12:00
> hi, I have the same question!!
> I have checkpoint files like:(data-0000-of-0001, index, .meta), I want to convert them to tf serving use.
> the format is (saved_model.pb, variables, variables.data-0000-of-0001, variabels/variables.index)
> Do you fix it??

Hey could you please tell me if you solved it? if yes how?
