### ISSUE TITLE
Example inception_model.inference Error

### ISSUE THREAD

**Issue by ank286** [tensorflow/serving#136] opened 2016-07-22 20:36 UTC
I am trying to export the inception model and I get the following error:

, in export
    logits, _ = inception_model.inference(images, NUM_CLASSES + 1)
  File "/home/ubuntu/tf/serving/serving/tensorflow_serving/example/inception/inception_model.py", line 80, in inference
    with slim.arg_scope([slim.ops.conv2d, slim.ops.fc], weight_decay=0.00004):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/ubuntu/tf/serving/serving/tensorflow_serving/example/inception/inception/slim/scopes.py", line 125, in arg_scope
    raise ValueError("%s is not decorated with @add_arg_scope", key_op)
ValueError: ('%s is not decorated with @add_arg_scope', ('inception.inception.slim.ops', 'conv2d'))

Thanks for any suggestions
Ankur

**Comment by nfiedel** [comment] 2016-07-22 22:30
Fangwei, any thoughts?

**Comment by ank286** [comment] 2016-07-26 16:30
I saw that I have not "installed" Inception models.
Basically, when I do 
`from inception import inception_model`
I get an ImportError: no module found. 

How do I install inception? Right now, I can't run the TF-Serving example for Inception but it works for MNIST.

Thank you
Ankur

**Comment by ank286** [comment] 2016-07-28 11:11
I have re-installed TF and TF-Serving, I still get the 
`from inception import inception_model` ImportError (no module found) from python. 
Is there a specific flag that I missed when installing TensorFlow or Serving for building the Inception module?
Or do I need to add it to my `PYTHONPATH`?

**Comment by fangweili** [comment] 2016-07-29 16:33
How did you run it?
In order for PYTHONPATH to be set up properly (&automatically), you have to run bazel-bin/tensorflow_serving/example/inception_export instead.

**Comment by ank286** [comment] 2016-07-29 16:58
I did a 
`basel build //tensorflow_serving/example:inception_export`
Then ran `bazel-bin/tensorflow_serving/example/inception_export`

Here is the output:

`ubuntu@ip-172-31-24-85:~/tf/serving/serving$ sudo bazel-bin/tensorflow_serving/example/inception_export
/home/ubuntu/tf/serving/serving

Traceback (most recent call last):
  File "/home/ubuntu/tf/serving/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/tf_serving/tensorflow_serving/example/inception_export.py", line 146, in <module>
    tf.app.run()
  File "/home/ubuntu/tf/serving/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/ubuntu/tf/serving/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/tf_serving/tensorflow_serving/example/inception_export.py", line 142, in main
    export()
  File "/home/ubuntu/tf/serving/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/tf_serving/tensorflow_serving/example/inception_export.py", line 94, in export
    logits, _ = inception_model.inference(images, NUM_CLASSES + 1)
  File "/home/ubuntu/tf/serving/serving/tensorflow_serving/example/inception/inception_model.py", line 80, in inference
    with slim.arg_scope([slim.ops.conv2d, slim.ops.fc], weight_decay=0.00004):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/ubuntu/tf/serving/serving/tensorflow_serving/example/inception/inception/slim/scopes.py", line 125, in arg_scope
    raise ValueError("%s is not decorated with @add_arg_scope", key_op)
ValueError: ('%s is not decorated with @add_arg_scope', ('inception.inception.slim.ops', 'conv2d'))
`

**Comment by fangweili** [comment] 2016-09-08 18:13
can't reproduce the issue with TF Serving @HEAD against TF@83fe2a5.
I am gonna close it for now. feel free to re-open if problem persists.

**Closed by fangweili** 2016-09-08 18:13 UTC
