### ISSUE TITLE
Is there any way to use tfprof profiling tf-serving request.

### ISSUE THREAD

**Issue by xiaop1987** [tensorflow/serving#492] opened 2017-06-18 03:23 UTC
The requirement is getting profile info for a predict request, but noticing that the cpp interface of tfprof is private in tensorflow project, I can't use them to implement a Profile interface for tf-serving, 

Is there any solution to access the tensorflow/tools/tfprof/internal without change the code of tensorflow?

**Comment by gautamvasudevan** [comment] 2018-08-03 19:57
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 19:57 UTC
