### ISSUE TITLE
Build error on macOs

### ISSUE THREAD

**Issue by itechbear** [tensorflow/serving#144] opened 2016-08-01 05:32 UTC
$ bazel build tensorflow_serving/core/...
WARNING: /private/var/tmp/_bazel_thinkpad/833bf204b935a1b16b0da880974a0117/external/protobuf/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_thinkpad/833bf204b935a1b16b0da880974a0117/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
WARNING: /private/var/tmp/_bazel_thinkpad/833bf204b935a1b16b0da880974a0117/external/highwayhash/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_thinkpad/833bf204b935a1b16b0da880974a0117/external/highwayhash/WORKSPACE (@__main__) does not match the name given in the repository's definition (@highwayhash); this will cause a build error in future versions.
WARNING: /private/var/tmp/_bazel_thinkpad/833bf204b935a1b16b0da880974a0117/external/re2/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_thinkpad/833bf204b935a1b16b0da880974a0117/external/re2/WORKSPACE (@__main__) does not match the name given in the repository's definition (@re2); this will cause a build error in future versions.
INFO: Found 55 targets...
ERROR: /Users/thinkpad/Code/tensorflow-serving/tensorflow_serving/core/test_util/BUILD:52:1: C++ compilation of rule '//tensorflow_serving/core/test_util:fake_loader' failed: cc_wrapper.sh failed: error executing command external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wthread-safety -Wself-assign -fcolor-diagnostics -fno-omit-frame-pointer '-std=c++0x' ... (remaining 108 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from tensorflow_serving/core/test_util/fake_loader.cc:16:
./tensorflow_serving/core/test_util/fake_loader.h:59:10: error: thread-local storage is not supported for the current target
  static thread_local bool was_deleted_in_this_thread_;
         ^
tensorflow_serving/core/test_util/fake_loader.cc:24:1: error: thread-local storage is not supported for the current target
thread_local bool FakeLoader::was_deleted_in_this_thread_;
^
2 errors generated.
INFO: Elapsed time: 3.689s, Critical Path: 3.33s

$ cc --version
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

**Comment by kirilg** [comment] 2016-08-23 20:57
Duplicate of https://github.com/tensorflow/serving/issues/1

**Closed by kirilg** 2016-08-23 20:57 UTC
Labels: installation/compilation
