### ISSUE TITLE
undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringE

### ISSUE THREAD

**Issue by polarisZhao** [tensorflow/serving#692] opened 2017-12-14 03:41 UTC
when I run 
bazel-bin/tensorflow_serving/example/inception_saved_model --checkpoint_dir=inception-v3 --output_dir=/tmp/inception-export
**fellow Serving Inception Model with TensorFlow Serving and Kubernetes. give me a error：
tensorflow.python.framework.errors_impl.NotFoundError: /home/ubuntu/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/contrib/data/python/ops/../../_prefetching_ops.so: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringE**

my system is :Ubuntu 14.04.5 LTS
tensorflow version: tensorflow-gpu (1.4.0)
protobuf version: protobuf (3.5.0.post1)

how can I solve it? anyone met same error?

**Comment by chrisolston** [comment] 2017-12-14 04:58
This looks like a dupe of https://github.com/tensorflow/serving/issues/684

**Closed by chrisolston** 2017-12-14 04:58 UTC

**Comment by 15940260868** [comment] 2018-12-11 19:42
@polarisZhao Hi, have you solved your problem? I have the same error. Could you help me?

**Comment by usptact** [comment] 2019-03-19 18:07
In my case, the problem was separately installed C++ library for Tensorflow "libtensorflow_framework.so" in "/usr/local/lib". I removed this library and Python tensorflow started to work once again.
