### ISSUE TITLE
Build issue: Linking of rule '@org_tensorflow//tensorflow/python:_pywrap_tensorflow.so' failed

### ISSUE THREAD

**Issue by derek121** [tensorflow/serving#199] opened 2016-10-04 14:58 UTC
I'm using bazel version 0.3.1, Ubuntu 14.04, python 2.7.6, with a fresh clone of TensorFlow Serving.

Following the steps at https://tensorflow.github.io/serving/setup.

During `bazel build tensorflow_serving/...`

``` ERROR:
/home/ubuntu/.cache/bazel/_bazel_ubuntu/9593a225285aa956b99521125644f546/external/org_tensorflow/tensorflow/python/BUILD:1779:1:
Linking of rule '@org_tensorflow//tensorflow/python:_pywrap_tensorflow.so'
failed: gcc failed: error executing command /usr/bin/gcc -shared -o
bazel-out/local-fastbuild/bin/external/org_tensorflow/tensorflow/python/_pywrap_tensorflow.so
-Wl,--version-script external/org_tensorflow/tensorflow/tf_version_script.lds
... (remaining 9 argument(s) skipped):
com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with
status 1.  collect2: error: ld terminated with signal 9 [Killed]
```

Thanks for any tips.

**Comment by kirilg** [comment] 2016-10-04 21:24
This looks like resource constraints on your machine. You may want to try running while constraining the amount of CPU/RAM Bazel is allowed to use:

`bazel build --local_resources 5000,1.0,1.0 tensorflow_serving/...`
for example to constrain to 5G of RAM and 1 core. You can adjust these numbers, but just make sure they're not too high for the machine it's running on (keep in mind the lower the numbers, the longer it will probably take to compile). Please report back if this fixes it or if you're still seeing errors with a lower cap.

**Comment by derek121** [comment] 2016-10-05 00:00
Thanks, @kirilg- that changed the error. Now got the following. Hmmm...

```
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-self-assign" [enabled by default]
ERROR:
/home/ubuntu/.cache/bazel/_bazel_ubuntu/9593a225285aa956b99521125644f546/external/org_tensorflow/tensorflow/core/kernels/BUILD:1128:1:
C++ compilation of rule '@org_tensorflow//tensorflow/core/kernels:svd_op'
failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE
'-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin
-B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object
-fno-omit-frame-pointer -g0 ... (remaining 102 argument(s) skipped):
com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with
status 4.  gcc: internal compiler error: Segmentation fault (program cc1plus)
```

**Comment by kirilg** [comment] 2016-10-05 00:27
Hmm, I haven't encountered this, but it's still an internal compiler error, not a problem with the actual code. An initial search suggests it could be a low memory issue. What command did you end up going with? what local_resources constraints did you set and how much does the machine have?

**Comment by derek121** [comment] 2016-10-05 17:22
@kirilg- thanks. It was with `bazel build --local_resources 6000,2.0,2.0 tensorflow_serving/...`

It has 2 cores and 8 GB RAM.

**Comment by rayglover-ibm** [comment] 2016-10-06 14:51
On the segfault, Which version of `gcc` are you using? I seem to remember not being able to build Tensorflow with `4.8.2` because of a bug in gcc which was fixed in `4.8.3`.

You might have the same problem because you say you're building on Ubuntu 14.04.

**Comment by joenewbry** [comment] 2016-11-01 16:59
I think I'm running into a similar problem.  Initially my docker settings limited available to memory to 2GB. I've tried again after changing the docker memory preferences to 16GB (see stats below with updated memory limit)

CONTAINER           CPU %               MEM USAGE / LIMIT       MEM %               NET I/O              BLOCK I/O            PIDS
6ff2fb9120b0        397.30%             4.556 GiB / 15.65 GiB   29.11%              252.4 MB / 3.56 MB   831.5 kB / 2.19 GB   243

Steps to reproduce based on [this tutorial] (https://tensorflow.github.io/serving/docker).
mkdir tensorflow_serving
cd tensorflow_serving
curl https://raw.githubusercontent.com/tensorflow/serving/master/tensorflow_serving/tools/docker/Dockerfile.devel > Dockerfile.devel
docker build --pull -t $USER/tensorflow-serving-devel -f Dockerfile.devel .
docker run -it $USER/tensorflow-serving-devel
git clone --recurse-submodules https://github.com/tensorflow/serving
cd serving/tensorflow
./configure
cd ..
bazel test tensorflow_serving/...

Executed 0 out of 45 tests: 45 were skipped.


ERROR: /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/external/org_tensorflow/tensorflow/core/kernels/BUILD:1296:1: C++ compilation of rule '@org_tensorflow//tensorflow/core/kernels:cwise_op' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -Wall -Wl,-z,-relro,-z,now -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer ... (remaining 98 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 4.

root@6ff2fb9120b0:/serving# gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

running docker on El Capitan 10.11.5 (15F34)

If there's any other information I can provide please let me know

**Comment by gautamvasudevan** [comment] 2018-06-29 22:37
Closing - please see the latest [Docker examples](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md) for bringing up a build environment.

**Closed by gautamvasudevan** 2018-06-29 22:37 UTC
Labels: installation/compilation
