### ISSUE TITLE
Getting an "Unimplemented" error when using TFServing built from source on TF Object Detection API model.

### ISSUE THREAD

**Issue by farzaa** [tensorflow/serving#1311] opened 2019-04-11 20:43 UTC
I am using tf-serving built from source via the Docker image found [here](https://www.tensorflow.org/tfx/serving/docker#building_an_optimized_serving_binary). My model is `faster_rcnn_inception_v2_coco` found within the TensorFlow object detection API located [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md).

When I use `tensorflow-gpu` `1.13.1` and don't build from source (installed via Docker w/ the instructions found [here](https://www.tensorflow.org/install/docker#gpu_support)) everything works perfectly upon inference. 

But when I use tf-serving (running TF `1.13.1`) built from source (via the Docker image linked above) to take advantage of CPU optimizations I get hit with the following error upon attempting to do inference. 

```
[evhttp_server.cc : 237] RAW: Entering the event loop ...
2019-04-11 20:27:59.196073: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1408] OP_REQUIRES failed at conv_ops_fused_impl.h:648 : Unimplemented: Fusion is not implemented: [BiasAdd,Relu6]
2019-04-11 20:27:59.196141: E external/org_tensorflow/tensorflow/core/common_runtime/executor.cc:637] Executor failed to create kernel. Unimplemented: Fusion is not implemented: [BiasAdd,Relu6]
	 [[{{node Conv/Relu6}}]]
2019-04-11 20:28:01.013470: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1408] OP_REQUIRES failed at conv_ops_fused_impl.h:648 : Unimplemented: Fusion is not implemented: [BiasAdd,Relu6]
2019-04-11 20:28:01.013541: E external/org_tensorflow/tensorflow/core/common_runtime/executor.cc:637] Executor failed to create kernel. Unimplemented: Fusion is not implemented: [BiasAdd,Relu6]
	 [[{{node Conv/Relu6}}]]
2019-04-11 20:28:02.892400: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1408] OP_REQUIRES failed at conv_ops_fused_impl.h:648 : Unimplemented: Fusion is not implemented: [BiasAdd,Relu6]
2019-04-11 20:28:02.892476: E external/org_tensorflow/tensorflow/core/common_runtime/executor.cc:637] Executor failed to create kernel. Unimplemented: Fusion is not implemented: [BiasAdd,Relu6]
	 [[{{node Conv/Relu6}}]]
```

This is super odd, because things worked fine with tf-serving installed normally with Docker when doing inference, but when i build tf-serving from source something breaks.

**Comment by hgadig** [comment] 2019-04-16 20:59
Could you please provide the exact steps followed and a small code snippet which help us to reproduce the error from our end?

**Comment by hgadig** [comment] 2019-04-19 20:53
> Could you please provide the exact steps followed and a small code snippet which help us to reproduce the error from our end?

Any update?

**Comment by gowtham-kp** [comment] 2019-05-08 21:48
@farzaa Closing this issue due to the lack of recent activity. Please update the issue with additional details and we will reopen it. Thanks!

**Closed by gowtham-kp** 2019-05-08 21:48 UTC
Labels: stat:awaiting response, type:support
