### ISSUE TITLE
Predict is error

### ISSUE THREAD

**Issue by BannockYJQ** [tensorflow/serving#1571] opened 2020-03-12 06:28 UTC
When i predict data by tensorflow serving, a part of data is ok, there are some result.but other data are not ok, the error is Incompatible shapes:[43, 8] vs [58, 8].
![image]( #https://user-images.githubusercontent.com/30150009/76493543-d40c2500-646d-11ea-9c08-e3770460da2a.png)
It is important that the error is not found on tf serving test, but online tf serving is error . and some data is ok, some data is error
i cant understant.
Help me, THX

**Comment by gowthamkpr** [comment] 2020-03-12 16:53
@BannockYJQ I think that this error is caused due to tensorflow(model) itself as serving just queries the model and gets the predictions. Can you please add all the steps you followed and a minimal example for us to reproduce the error. Thanks!

**Comment by gowthamkpr** [comment] 2020-03-18 17:03
@BannockYJQ Can you please respond to the above comment so that we can take the discussion further.

**Comment by BannockYJQ** [comment] 2020-03-19 06:41
@gowthamkpr emmm,sry,i work every day so i forget it. The problem has been solved.
THX, bro. the secret is Thread safety issues，not Tensorflow serving, it cause the shape is error

**Comment by gowthamkpr** [comment] 2020-03-19 16:42
Thank you. Closing this issue as it has been resolved.

**Closed by gowthamkpr** 2020-03-19 16:42 UTC
Labels: stat:awaiting response, type:support
