### ISSUE TITLE
How can I remove a model by the tensorflow serving grpc or api ?

### ISSUE THREAD

**Issue by liutao053877** [tensorflow/serving#1572] opened 2020-03-12 13:36 UTC
In my program there are lot of models I need to load and remove automatically at the runtime.
So when i remove a model i want to release the memory the model used before.
I remove the model by first remove the model from the config.ini and the reload the config.ini(the grpc reload config function),we can see the model version is END(by curl -XGET http://ip:port/v1/models/{modelname}),but the memory  did not release or just release a part of the remove model occupied before.

I can solve it by restart tensorflow serving, but the service will stop for a short time.
In fact my service can not stop for the customers for 24 hours.

Except the way to restart tensorflow serving ,how can i remove a model and release the memory 
by grpc or api ?  Thx

**Comment by liutao053877** [comment] 2020-03-12 23:27
@gowthamkpr I just find the demo add model by grpc, but i do not know how to delete it by grpc

**Comment by liutao053877** [comment] 2020-03-12 23:29
@gowthamkpr  I remove the model by first remove the model from the config.ini and the reload the config.ini. I am not sure whether it is the right way to delete model

**Comment by liutao053877** [comment] 2020-03-13 12:56
??

**Comment by gowthamkpr** [comment] 2020-03-13 22:05
@liutao053877 Please take a look at [Reloading Model Server Configuration](https://www.tensorflow.org/tfx/serving/serving_config#reloading_model_server_configuration) especially `HandleReloadConfigRequest`

As mentioned [here](https://github.com/tensorflow/serving/blob/3d5b44a95a2c458affeb284f1141a8612427dd8c/tensorflow_serving/apis/model_service.proto#L19) it reloads the set of served models. The new config supersedes the old one,so if a model is omitted from the new config it will be unloaded and no longer served.

**Comment by liutao053877** [comment] 2020-03-14 01:25
@gowthamkpr I know this ,I find the model is omitted from the new config do not release the memory .I just find a way to solve it is to open two tfs process, one is used to restart and release delete models and one is used for serving, once the restart process is OK we will switch it for serving and close the other process, the two process will switch at the run time .This way is not very good because we can use half of the max memory for serving  but can solve the problem
thank you  !

**Comment by gowthamkpr** [comment] 2020-03-16 18:23
@liutao053877 Can you please share a dummy example for us to reproduce the issue. Thanks!

**Comment by lzzuo2** [comment] 2020-03-26 15:08
I had the same problem, is there any grpc api to unload a model ?

**Comment by lilao** [comment] 2020-04-03 22:54
@liutao053877 Did the model actually get unloaded in your case? If the model was unloaded, it's likely that the malloc system did not return the freed memory back to OS. This depends on the implementation of the malloc, and is out of the control of tensorflow serving.

**Comment by geraldstanje** [comment] 2020-05-16 15:42
do you have some code to share to test it?

**Comment by rmothukuru** [comment] 2020-10-16 11:05
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2020-10-16 11:05 UTC
Labels: stat:awaiting response, stat:awaiting tensorflower, type:performance
