### ISSUE TITLE
How to prepare these model to Serving

### ISSUE THREAD

**Issue by nikkysound** [tensorflow/serving#796] opened 2018-03-06 20:53 UTC
I've just trained these models https://github.com/Maluuba/qgen-workshop/blob/master/qgen/model.py

Got 5 models

- model-1.data-00000-of-00001
- model-1.index
- model-1.meta

**(from model-1 to model-5)**

and those files:

- checkpoint
- embeddings.ckpt.data-00000-of-00001
- embeddings.ckpt.index
- embeddings.ckpt.meta
- projector_config.pbtxt
- vocab.tsv

tensorflow dashboard works perfectly

So, now I want to deploy this model to production with TensorFlow Serving which is really confused to me.

I've read few manuals, and the main question is how should I convert all this model to use it in TensorFlow Serving and should I convert all of them?

**Comment by sukritiramesh** [comment] 2018-03-21 23:25
TensorFlow Serving uses SavedModels for serving (see here for an example: https://www.tensorflow.org/serving/serving_basic). See the TensorFlow Programmer's Guide for more on SavedModels: https://www.tensorflow.org/programmers_guide/saved_model#overview_of_saving_and_restoring_models. It looks like the current format of your models is the old deprecated format. Once you export your models as SavedModels, the tutorials should be able to help further.

**Comment by gautamvasudevan** [comment] 2018-08-03 20:17
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 20:17 UTC
