### ISSUE TITLE
Tensorflow serving setup on GPU - memory allocated, but inference on CPU (slow, verified by htop)

### ISSUE THREAD

**Issue by jaypanda** [tensorflow/serving#635] opened 2017-11-01 16:02 UTC
Hi, 

I am observing a weird issue while setting up tensorflow serving for GPUs. After compiling with `bazel build -c opt --config=cuda tensorflow_serving/...` and initiating the serving, GPU memory seems to be consumed/allocated for the process, but during inference the process seems to utilize mutli-core CPU validated by the relatively slower inference time. Am I missing something here ? Any pointers would be helpful.
Same observation on a 4-GPU  (12 GB RAM each) TitanX workstation and Google Compute instance setup with "1 x NVIDIA Tesla K80". Both running Ubuntu 16.04 with Cuda V8.0.61.

Thanks in advance.

**Comment by chrisolston** [comment] 2017-11-01 17:21
You need to make sure the graphdef (in your SavedModel files) specifies that certain ops are assigned to the gpu device. And of course it matters a lot *which* ops you place on the gpu. See https://www.tensorflow.org/tutorials/using_gpu

**Comment by gautamvasudevan** [comment] 2018-08-03 20:00
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 20:00 UTC
