### ISSUE TITLE
Issues Installing TF Serving on Jetson TX2

### ISSUE THREAD

**Issue by booglerz** [tensorflow/serving#832] opened 2018-03-30 16:37 UTC
Hello,

Since our TF models heavily utilize unsupported TF layers, converting our TF Model to a UFF in TensorRT does not seem feasible. Instead, we were thinking of trying to get TensorFlow Serving working on the jetson, to act as a mini server for model inference.

Has anyone done this yet, or know of people who have? I've seen examples of installing TensorFlow on the Jetson so I assumed it might be possible to install TensorFlow Serving as well.

However, I run in issues building TF Serving with Bazel, and have exhausted my ability to narrow down the problem. 

So far I have:
Installed all pre-reqs
Installed bazel
cloned TF Serving and attempted to build it from source. 

I run into an issue which is similar to memory issues (see below) I've seen around the forums/github pages and have tried to confine the resources used during the build, but nothing works (e.g., bazel build --jobs 1 --local_resources 1024,1.0,1.0 --verbose_failures tensorflow_serving/...)

The error I keep getting is:
Linking of rule '//tensorflow_serving/model_servers:tensorflow_model_server' failed (Exit 1).
bazel-out/local-opt/bin/external/aws/_objs/aws/external/aws/aws-cpp-sdk-core/source/client/ClientConfiguration.o:ClientConfiguration.cpp:function Aws::Client::ComputeUserAgentString(): error: undefined reference to 'Aws::OSVersionInfo::ComputeOSVersionString[abi:cxx11]()'
<lots of similar undefined reference error outputs as above>
collect2: error: ld returned 1 exit status

Does anyone have experience attempting / successfully installing TensorFlow Serving on a Jetson?

Any clue why my build is failing?

**Comment by VladislavSu** [comment] 2018-07-24 06:58
My workaround is
In file:
`/home/<user_name>/.cache/bazel/_bazel_<user_name>/<hash>/external/aws/BUILD.bazel`
(where `<user_name>` - user current linux user name,
`<hash>` is hash like de4a7858eac0c7de37e543fdc903ef12) 

 In section (cc_library) in my case line 27 replace:
`"//conditions:default": []"`
with
`"//conditions:default": glob(["aws-cpp-sdk-core/source/platform/linux-shared/*.cpp",]),`

Then it will successfully build on Jetson.

**Comment by harshini-gadige** [comment] 2018-10-25 17:36
@booglerz  - Hi, is this still an issue ? Did the workaround help you to resolve it ?

**Comment by harshini-gadige** [comment] 2018-11-16 19:22
There is a workaround provided and it was in awaiting response for more than 7 days. Hence closing this issue.

**Closed** 2018-11-16 19:22 UTC
Labels: stat:awaiting response, type:build/install

**Comment by laurent-george** [comment] 2018-11-22 14:17
> @booglerz - Hi, is this still an issue ? Did the workaround help you to resolve it ?

It solves the issues for me. Thanks a lot, but the bug is still present.

**Comment by unclepeddy** [comment] 2019-08-08 17:55
Noting this as a duplicate of #1277 for prioritization

**Comment by pigubaoza** [comment] 2020-08-06 02:34
hi @mrodozov is this pulled into the main tensorflow repo?
