### ISSUE TITLE
Latency Tensorflow serving with docker for video analysis

### ISSUE THREAD

**Issue by userEnsb** [tensorflow/serving#1752] opened 2020-10-19 16:16 UTC
I would like to ask a question regarding the response time of a tensorflow model in docker. I transformed a Yolo model from .h5 into a model API with the function.

I use a Ubuntu machine with an i9 CPU and an RTX 2080 TI graphics card

```
Model.save(
    filepath,
    overwrite=True,
    include_optimizer=True,
    save_format=None,
    signatures=None,
    options=None,
)
```

I took a docker image from tensorflow/serving:latest-gpu which I copied my models as follows:

```
FROM tensorflow/serving:latest-gpu
COPY models /apps/
EXPOSE 8500
EXPOSE 8501
```
I wrote the following script to analyze a video

```
img = img.astype('float32')
    img = img / 255.0

    data = json.dumps({"signature_name": "serving_default", "instances": img.tolist()})


        }

    headers = {"content-type": "application/json"}
    start_time = time.time()
    json_response = requests.post('http://172.27.240.5:8501/v1/models/vetements:predict', data=dat   a, headers=headers)
    print("--- %s seconds ---" % (time.time() - start_time))

    predictions = json.loads(json_response.text)['predictions']
```
my question is as follows the rest time to analyze a single image is 0.5 seconds, please does it have a way to speed up the execution of analysis

thank you

**Comment by BorhenJlidi** [comment] 2020-10-19 17:11
My first instinct when working with images or generally large input data is to use gRPC instead of REST.
I would recommend working on changing the protocol then seeking other optimizations.

**Comment by userEnsb** [comment] 2020-10-20 08:03
> My first instinct when working with images or generally large input data is to use gRPC instead of REST.
> I would recommend working on changing the protocol then seeking other optimizations.

@BorhenJlidi 
then look for other optimizations, please what kind of optimizations you think can help me
Thank you

**Comment by rmothukuru** [comment] 2020-10-20 09:37
@userEnsb,
Please refer [Tensorflow Serving Performance Guide](https://www.tensorflow.org/tfx/serving/performance). This [Google Cloud Article](https://cloud.google.com/solutions/machine-learning/minimizing-predictive-serving-latency-in-machine-learning) also might help. Thanks!

**Comment by BorhenJlidi** [comment] 2020-10-20 10:47
@userEnsb ,
@rmothukuru summarized the different aspects of optimization, once you overcome latency issues give NVIDIA TensorRT a go.

**Comment by userEnsb** [comment] 2020-10-20 12:21
@BorhenJlidi 
Thank you, please Can I use NVIDIA TensorRT with Docker as API Model ?

**Comment by rmothukuru** [comment] 2020-10-20 13:11
@userEnsb,
Please find this [Github Documentation](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md#serving-with-docker-using-your-gpu) which explains how to use TF Serving along with GPU and Docker. Hope it helps. Thanks!

**Comment by userEnsb** [comment] 2020-10-20 14:34
@rmothukuru 
Thank you, it's already done, you can see the code at the top.
The problem now is the latency.
Thanks!

**Comment by rmothukuru** [comment] 2020-10-21 08:58
@userEnsb,
Please refer this [Medium Article](https://medium.com/tensorflow/optimizing-tensorflow-serving-performance-with-nvidia-tensorrt-6d8a2347869a) which shows how to use TF Serving with TensorRT using Docker. Thanks

**Comment by nrobeR** [comment] 2020-10-23 17:31
@userEnsb could you please take a look at the [Tensorflow Serving Performance Guide](https://www.tensorflow.org/tfx/serving/performance) that @rmothukuru referred to above? There are some suggestions and instructions on how to profile a request using tensorboard

**Comment by rmothukuru** [comment] 2020-10-28 14:56
@BorhenJlidi,
Can you please respond to the above comments (mine and @nrobeR's). Thanks!

**Comment by BorhenJlidi** [comment] 2020-10-28 23:00
@userEnsb I can confirm that the links shared by @nrobeR and @rmothukuru cover serving TensorRT optimized models. I might as well add https://www.tensorflow.org/tfx/serving/tensorboard for profiling TF Serving inference requests and NVIDIA's Profiler nvprof [https://docs.nvidia.com/cuda/profiler-users-guide/index.html](https://docs.nvidia.com/cuda/profiler-users-guide/index.html) for inference profiling in general.

**Comment by rmothukuru** [comment] 2020-10-29 04:22
@userEnsb,
Can you please let us know if your issue is resolved so that we can close it. Thanks!

**Comment by rmothukuru** [comment] 2020-11-06 12:29
@userEnsb,
Can you please respond to the above comment. Thanks!

**Comment by rmothukuru** [comment] 2020-11-15 08:28
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2020-11-15 08:28 UTC
Labels: stat:awaiting response, type:performance
