### ISSUE TITLE
TensorFlow Serving didnt work on Windows 10

### ISSUE THREAD

**Issue by Pokharaa** [tensorflow/serving#729] opened 2018-01-17 10:54 UTC
My configuration are:
Windows 10
Python 2.7
cudnn5.1
cuda8.0
When I try to run this command on docker:
**_bazel build -c opt tensorflow_serving/...**
I got the following error:
DEBUG: C:/users/pb/appdata/local/temp/_bazel_pb/texvsyie/external/bazel_tools/tools/build_defs/pkg/pkg.bzl:197:9: @//tensorflow_serving/model_servers:tensorflow_model_server_tar: you provided a non dictionary to the pkg_tar `files` attribute. This attribute was renamed to `srcs`. Consider renaming it in your BUILD file.
ERROR: error loading package 'tensorflow_serving/example': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf_archive//': Traceback (most recent call last):
 File"C:/users/pb/appdata/local/temp/_bazel_pb/texvsyie/external/org_tensorflow/third_party/repo.bzl", line 88_apply_patch(ctx, ctx.attr.patch_file)
File"C:/users/pb/appdata/local/temp/_bazel_pb/texvsyie/external/org_tensorflow/third_party/repo.bzl", line 59, in _apply_patch _execute_and_check_ret_code(ctx, cmd)
File"C:/users/pb/appdata/local/temp/_bazel_pb/texvsyie/external/org_tensorflow/third_party/repo.bzl", line 44, in _execute_and_check_ret_code fail("Non-zero return code({1}) when ...))
Non-zero return code(256) when executing 'C:\tools\msys64\usr\bin\bash.exe -c patch -p1 -d C:/users/pb/appdata/local/temp/_bazel_pb/texvsyie/external/protobuf_archive -i C:/users/pb/appdata/local/temp/_bazel_pb/texvsyie/external/org_tensorflow/third_party/protobuf/add_noinlines.patch':
Stdout:
Stderr: Timed out
ERROR: error loading package 'tensorflow_serving/example': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf_archive//': Traceback (most recent call last):
File"C:/users/pb/appdata/local/temp/_bazel_pb/texvsyie/external/org_tensorflow/third_party/repo.bzl", line 88_apply_patch(ctx, ctx.attr.patch_file)
File"C:/users/pb/appdata/local/temp/_bazel_pb/texvsyie/external/org_tensorflow/third_party/repo.bzl", line 59, in _apply_patch _execute_and_check_ret_code(ctx, cmd)
File"C:/users/pb/appdata/local/temp/_bazel_pb/texvsyie/external/org_tensorflow/third_party/repo.bzl", line 44, in _execute_and_check_ret_code fail("Non-zero return code({1}) when ...))
Non-zero return code(256) when executing 'C:\tools\msys64\usr\bin\bash.exe -c patch -p1 -d C:/users/pb/appdata/local/temp/_bazel_pb/texvsyie/external/protobuf_archive -i C:/users/pb/appdata/local/temp/_bazel_pb/texvsyie/external/org_tensorflow/third_party/protobuf/add_noinlines.patch':
Stdout:
Stderr: Timed out
INFO: Elapsed time: 18.745s
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow_serving/core ... (12 packages)

>I couldn't figure out the problem.Please help me

**Comment by R-Miner** [comment] 2018-05-31 17:54
Did you resolve this issue? I am also trying to install tensorflow serving on a windows 10 machine and is throwing me similar issues. Any help is appreciated.

**Comment by Pokharaa** [comment] 2018-06-01 00:09
Hello R-Miner

**Comment by Pokharaa** [comment] 2018-06-01 00:11
Hello @R-Miner ,
The video is quite difficult to see but I hope it will help you to solve the above issues.
https://www.youtube.com/watch?v=SsaJJsRvwIs&t=20s

Let me know if it worked or not?
Regards.

**Comment by R-Miner** [comment] 2018-06-01 14:10
@Pokharaa Thankyou for your response.

 The above video is about installing tensorflow serving in an Ubuntu machine which I am able to do successfully. I am trying to do the same on a windows 10 machine  which is still not successful.  I am getting the same error like you got.  Please update if there is any progress in installing it in windows machine. It will be really helpful. I will update if I find any progress.

Thanks
R-Miner

**Comment by Pokharaa** [comment] 2018-06-01 14:14
Did u run the bazel inside the container? 
If possible could you send me the screen shot of your problem?
And whats your bazel version?
Regards,
Pokharaa

**Comment by R-Miner** [comment] 2018-06-01 14:18
I did not use the docker container for installation.

**Comment by Pokharaa** [comment] 2018-06-03 23:52
HI @R-Miner ,
I am sorry to say without using docker, I haven't tried it.

**Comment by R-Miner** [comment] 2018-06-08 13:59
I tried to install tensorflow serving with docker.
 I installed docker following the instructionsin docker website.
 Then I followed the instructions in installing tensorflow servings.
 The first step was a docker build command which throws me an error:
 docker build Error checking context: 'can't stat '\?\C:\Users\username\AppData...

Do you know a fix for this? Did you encounter such an error?

Thanks in Advance!

**Comment by shivamshukla12** [comment] 2018-06-09 19:34
May be this is helpful for windows users  - 

https://www.youtube.com/watch?v=r7-WPbx8VuY

Thanks,
Shivam

**Comment by Pokharaa** [comment] 2018-06-11 00:08
Hi @R-Miner,

Is your problem solved?

**Comment by gautamvasudevan** [comment] 2018-07-13 18:58
Duplicate of #240

**Closed by gautamvasudevan** 2018-07-13 18:58 UTC
Labels: installation/compilation
