### ISSUE TITLE
build tf-serving with mkl failed, when using official dockerfile.

### ISSUE THREAD

**Issue by wangchengbi** [tensorflow/serving#1224] opened 2018-12-26 12:40 UTC
### System information
- ** Windows 10 pro **:
- **TensorFlow Serving installed from source **:

### Describe the problem
I build tf-serving with mkl failed, when using official dockerfile. The dockerfile is Dockerfile.devel-mkl.

### Exact Steps to Reproduce
use docker build can reproduce the problem.

### Source code / logs
The error message is 
'ERROR:/root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/org_tensorflow/tensorflow/core/kernels/BUILD:6589:1: no such package '@icu//': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/unicode-org/icu/archive/release-62-1.tar.gz, https://github.com/unicode-org/icu/archive/release-62-1.tar.gz] to /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/icu/release-62-1.tar.gz: Checksum was d5de71cff315fd3b51739af9a8f0a0847d6b63d397a1320be31a658468376861 but wanted e15ffd84606323cbad5515bf9ecdf8061cc3bf80fb883b9e6aa162e485aa9761 and referenced by '@org_tensorflow//tensorflow/core/kernels:unicode_script_op'
ERROR: Analysis of target '//tensorflow_serving/model_servers:tensorflow_model_server' failed; build aborted: Analysis failed
INFO: Elapsed time: 347.067s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (105 packages loaded)
The command '/bin/sh -c bazel build --color=yes --curses=yes     ${TF_SERVING_BAZEL_OPTIONS}     --verbose_failures     --output_filter=DONT_MATCH_ANYTHING     ${TF_SERVING_BUILD_OPTIONS}     tensorflow_serving/model_servers:tensorflow_model_server &&     cp bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server     /usr/local/bin/' returned a non-zero code: 1'

**Comment by Remember2018** [comment] 2018-12-26 13:14
I also want to build the tensorflow_model_server with mkl support as somebody noted that the tensorflow can support the MaxPooling2D with NCHW data format. Could you please provide the bazel build configuration for that? Thanks.

**Comment by wangchengbi** [comment] 2018-12-26 13:59
I build the tf serving failed unit now.
And I just use the dockerfile noticed above to build a docker image.

**Comment by gautamvasudevan** [comment] 2018-12-26 20:06
dupe of https://github.com/tensorflow/tensorflow/issues/24135

**Closed by gautamvasudevan** 2018-12-26 20:06 UTC

**Comment by Remember2018** [comment] 2018-12-27 02:46
My solution is: try to run the bazel build command for many times, as the downlading is cached so after the dowloading is completed, the build procedure will begin. 

I think this error occured because of the unstable network.

**Comment by wangchengbi** [comment] 2018-12-27 02:50
Thank you very much! I will try it.

**Comment by Fordisk123** [comment] 2019-06-21 00:57
I  build  tf-serving with mkl failed, when using official dockerfile. The dockerfile is Dockerfile.devel-mkl 

**System information**
Ubuntu 16.04

**Error source code:**
ERROR: /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/io_bazel_rules_closure/closure/private/defs.bzl:18:17: FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
ERROR: /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/io_bazel_rules_closure/closure/private/defs.bzl:19:18: FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
ERROR: /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/io_bazel_rules_closure/closure/private/defs.bzl:20:16: FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
ERROR: /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/io_bazel_rules_closure/closure/private/defs.bzl:22:21: FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
ERROR: /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/io_bazel_rules_closure/closure/private/defs.bzl:23:17: FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
ERROR: error loading package '': in /tensorflow-serving/tensorflow_serving/workspace.bzl: in /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/org_tensorflow/tensorflow/workspace.bzl: in /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/io_bazel_rules_closure/closure/defs.bzl: in /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/io_bazel_rules_closure/closure/compiler/closure_js_aspect.bzl: Extension file 'closure/private/defs.bzl' has errors
ERROR: error loading package '': in /tensorflow-serving/tensorflow_serving/workspace.bzl: in /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/org_tensorflow/tensorflow/workspace.bzl: in /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/io_bazel_rules_closure/closure/defs.bzl: in /root/.cache/bazel/_bazel_root/e53bbb0b0da4e26d24b415310219b953/external/io_bazel_rules_closure/closure/compiler/closure_js_aspect.bzl: Extension file 'closure/private/defs.bzl' has errors
INFO: Elapsed time: 138.167s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
