### ISSUE TITLE
when i execute bazel build -c opt tensorflow_serving/...   report  erro

### ISSUE THREAD

**Issue by daixiangzi** [tensorflow/serving#1049] opened 2018-08-12 11:31 UTC
ERROR: error loading package '': Encountered error while reading extension file 'tensorflow/workspace.bzl': no such package '@org_tensorflow//tensorflow': java.io.IOException: Error downloading [https://mirror.bazel.build/github.com/tensorflow/tensorflow/archive/1a22b0b982fa1a953651b98af8f3cd30542048fd.tar.gz, https://github.com/tensorflow/tensorflow/archive/1a22b0b982fa1a953651b98af8f3cd30542048fd.tar.gz] to /home/ubuntu/.cache/bazel/_bazel_ubuntu/d016dfc7e6b16d74c48e527282d5d20c/external/org_tensorflow/1a22b0b982fa1a953651b98af8f3cd30542048fd.tar.gz: All mirrors are down: [GET returned 403 Forbidden, GET returned 502 Bad Gateway]

**Comment by gautamvasudevan** [comment] 2018-08-13 04:11
Looks like a proxy issue.
Duplicate of #347

**Closed by gautamvasudevan** 2018-08-13 04:11 UTC
