### ISSUE TITLE
Export the inception-v3/v4 to Savedmodel for tensorflow-serving.

### ISSUE THREAD

**Issue by drimyus** [tensorflow/serving#1688] opened 2020-07-15 01:41 UTC
## Export the inception-v3/v4 to Savedmodel for tensorflow-serving.

I want to export the image classification models (inception v3/v4) to SavedModel format (saved_model.pb). 

I downloaded the checkpoint files from [here](https://github.com/tensorflow/models/tree/master/research/slim)
inception-v3: http://download.tensorflow.org/models/inception_v3_2016_08_28.tar.gz 
inception-v4: http://download.tensorflow.org/models/inception_v4_2016_09_09.tar.gz

To export the checkpoints to savedModel format, I used this `export_inference_graph.py`.  https://github.com/tensorflow/models/blob/master/research/slim/export_inference_graph.py

But these converted model did not work. Here is the error message when I send the request for prediction.
```
2020-07-13 06:04:25.418044: E tensorflow_serving/util/retrier.cc:37] Loading servable: {name: inception_v4_2016_09_09 version: 1} failed: Not found: Could not find meta graph def matching supplied tags: { serve }. To inspect available tag-sets in the SavedModel, please use the SavedModel CLI: `saved_model_cli`
2020-07-13 06:04:25.418070: I tensorflow_serving/util/retrier.cc:46] Retrying of Loading servable: {name: inception_v4_2016_09_09 version: 1} exhausted max_num_retries: 5
```

I wonder is there any tutorial or example script to export the pre-trained checkpoint files to Savedmodel(.pb).
What should I do ?

The workspace environment is: 
Ubuntu 18.04, Python 3.7, Tensorflow 2.0.1 (FYI, I tested with TF 1.14.0 too, but same issue)

**Comment by rmothukuru** [comment] 2020-07-15 05:46
@drimyus,
Please check if the Saved Model in TF Format from TF Hub Link for [Inception V3](https://tfhub.dev/google/imagenet/inception_v3/classification/4) will be useful to you. You can download the Module from that link. Thanks!

**Comment by drimyus** [comment] 2020-07-15 10:03
Hi @rmothukuru
Thank you for your response, 
Can you let me know how can I do that on my side? I mean how can I convert/export the inception_v3 checkpoint to Savedmodel on my s?

**Comment by drimyus** [comment] 2020-07-15 10:15
I got this error, when I send the request for image classification.
```
'{
    "error": "Serving signature name: \\"serving_default\\" not found in signature def"
}'
```
Please let me know what is wrong on my side.

**Comment by rmothukuru** [comment] 2020-07-16 09:53
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by drimyus** [comment] 2020-07-16 09:58
```    def predict(self, img):
        ret, jpg = cv2.imencode('.jpg', img)
        jpg_as_text = base64.b64encode(jpg).decode('utf-8')

        url = f'http://localhost:8501/v1/models/imagenet_inception_v3_classification_4:predict'

        data = '{"instances" : [{"b64": "%s"}]}' % jpg_as_text
        response = requests.post(url, data=data)

        if response.status_code != 200:
            return []
        elif len(response.json()["predictions"]) == 0:
            return []
        else:
            prediction = response.json()["predictions"][0]
            # top_class_id = prediction['classes']

            res = []
            for i, prob in enumerate(prediction['probabilities']):
                res.append({
                    KEY_CLASS_ID: i,
                    KEY_LABEL: self.labels[i - 1],
                    KEY_CONFIDENCE: prob
                })
            return sorted(res, key=lambda p: p[KEY_CONFIDENCE], reverse=True)```

Here is my script to send the classification request to the tf-servin-docker.

**Comment by rmothukuru** [comment] 2020-07-17 08:29
@drimyus,
Sorry for asking multiple questions and this is the final one from my side. Can you please share the complete code which comprises Data Pre-Processing, Model Building  and Model Saving so that we can reproduce it at our end and can help you. Thanks!

**Comment by rmothukuru** [comment] 2020-07-24 10:55
@drimyus,
Can you please respond to the above comment. Thanks!

**Comment by rmothukuru** [comment] 2020-08-03 11:26
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Closed by rmothukuru** 2020-08-03 11:26 UTC
Labels: stat:awaiting response, type:support
