### ISSUE TITLE
AbortionError with "FeedInputs: unable to find feed output images"

### ISSUE THREAD

**Issue by MtDersvan** [tensorflow/serving#437] opened 2017-05-09 18:00 UTC
I found out that if I build from a [dockerfile](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel), it gives me an `AbortionError(code=StatusCode.NOT_FOUND, details="FeedInputs: unable to find feed output images")`. But when I install everything myself it works just fine.

There is a similar issue https://github.com/tensorflow/serving/issues/295.
But, those solutions do not work in my case for obvious reasons:
- My model is saved using .export_savedmodel(), so solution with `--use_saved_model=false` does not apply.
- Defining an input layer (--input_layer=Mul), does not work either, because I'm using a different model rather than mentioned `mnist_client`.

Steps to reproduce:
1. Install using [Dockerfile.devel](https://tensorflow.github.io/serving/docker).
2. Follow [these steps](https://github.com/MtDersvan/tf_playground/blob/master/wide_and_deep_tutorial/wide_and_deep_basic_serving.md).

I assume it can be connected to the grcpio, but I'm not sure.
This is rather confusing, and wasted quite a bit of my time, thanks for understanding.
Again it works fine if I installed everything [this way](https://tensorflow.github.io/serving/setup).

**Comment by kirilg** [comment] 2017-05-09 21:57
It's surprising since the error is inside TensorFlow, I wouldn't expect Docker to change the result. I might be missing something but I don't see where the signatures are defined, do you have a pointer? Is it possible the export file or the version of TensorFlow that's used is different in your Docker container

**Comment by MtDersvan** [comment] 2017-05-10 02:14
Yes, I have both containers running, specifically so we can debug.
It's [1.0.0](https://tensorflow.github.io/serving/docker) and [1.1.0-rc2](https://tensorflow.github.io/serving/setup) respectively.

**Comment by zhaozhichao4515** [comment] 2017-06-05 08:16
I have same error , have you solve it? it just work fine when I run mnist demo and inception demo, but when I use my model, it have error"FeedInputs: unable to find feed output ParseExample/ParseExample:0" 。Did you have some idea to solve this problem?

**Comment by MtDersvan** [comment] 2017-06-05 16:47
@zhaozhichao4515 first, try to update your tensorflow sources. I just built/installed everything myself instead of using a Docker image, and it worked for me.

**Comment by aforwardz** [comment] 2017-09-04 14:32
@zhaozhichao4515 I got the same issue, the example in tf serving also worked but came across this problem when I requested my own model served at a remote server. Have u sovled it ?

FYI

**Comment by gautamvasudevan** [comment] 2018-08-03 20:15
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 20:15 UTC
