### ISSUE TITLE
Tutorial code from inception_saved_model does not work

### ISSUE THREAD

**Issue by josauder** [tensorflow/serving#482] opened 2017-06-14 13:21 UTC
# System:

Ubuntu 16.04 in a Virtualbox VM
Bazel 0.4.5
Tensorflow serving commit a44fd6df3834aa054ff156e31fa0c9d524ac1693 from May 25, 2017

# Issue: 

The code from the tutorial at https://tensorflow.github.io/serving/serving_inception

```
curl -O http://download.tensorflow.org/models/image/imagenet/inception-v3-2016-03-01.tar.gz
tar xzf inception-v3-2016-03-01.tar.gz
bazel-bin/tensorflow_serving/example/inception_saved_model --checkpoint_dir=inception-v3 --output_dir=inception-export
```

Does not work for me. The error message is:

```
2017-06-14 14:50:02.260995: W external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-14 14:50:02.261021: W external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-14 14:50:02.261026: W external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
Successfully loaded model from inception-v3/model.ckpt-157585 at step=157585.
Traceback (most recent call last):
  File "/home/d069176/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/tf_serving/tensorflow_serving/example/inception_saved_model.py", line 204, in <module>
    tf.app.run()
  File "/home/d069176/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/d069176/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/tf_serving/tensorflow_serving/example/inception_saved_model.py", line 200, in main
    export()
  File "/home/d069176/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/tf_serving/tensorflow_serving/example/inception_saved_model.py", line 118, in export
    saver.save(sess,"/home/d069176/workspace/inception/stuff", global_step = global_step )
  File "/home/d069176/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 1450, in save
    global_step = training_util.global_step(sess, global_step)
  File "/home/d069176/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/python/training/training_util.py", line 58, in global_step
    return int(sess.run(global_step_tensor))
  File "/home/d069176/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/d069176/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 984, in _run
    self._graph, fetches, feed_dict_string, feed_handles=feed_handles)
  File "/home/d069176/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 410, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/home/d069176/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 238, in for_fetch
    return _ElementFetchMapper(fetches, contraction_fn)
  File "/home/d069176/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/python/client/session.py", line 277, in __init__
    'Tensor. (%s)' % (fetch, str(e)))
ValueError: Fetch argument u'157585' cannot be interpreted as a Tensor. ("The name '157585' refers to an Operation not in the graph.")
```

**Comment by chrisolston** [comment] 2017-06-14 18:05
I'm not sure but I suspect this problem is due to skew between TF-Serving and TF-Core. I saw a recent change to TF-Core that *may* be what's causing this: https://github.com/tensorflow/tensorflow/commit/b3c3a1c5720fd8122ef425b2c9b9081967a16d21

I just updated TF-Serving's submodules to point to a more recent version of TF-Core, in https://github.com/tensorflow/serving/pull/483. Can you sync to that change and retry please? If the problem persists we'll investigate more.

**Comment by josauder** [comment] 2017-06-20 14:08
I updated all tf_serving and all submodules with `git pull --recurse-submodules` and am now experiencing the same error as in https://github.com/tensorflow/serving/issues/461

**Comment by gautamvasudevan** [comment] 2018-08-03 19:57
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 19:57 UTC
