### ISSUE TITLE
CUDA performance inferior in tensorflow serving 

### ISSUE THREAD

**Issue by asheshjain399** [tensorflow/serving#705] opened 2017-12-26 01:48 UTC
Running the same cuda code (to multiply two matrices) from `serving` and `serving/tensorflow` results in very different performances. Below are the details to repro the problem:

Repo: https://github.com/asheshjain399/serving
Sha: `e10982ce56b57b89702cfc447e85f804afc0e43e`
(I've configured tensorflow with CUDA 8.0 and cuDNN 6.0 support)

**Performance= 15.17 GFlop/s, Time= 8.638 msec**
```
~/project/serving $ bazel run --config=cuda //gpu:matrix_mult_cc 
[Matrix Multiply Using CUDA] - Starting...
GPU Device 0: "GeForce GTX 970" with compute capability 5.2

MatrixA(320,320), MatrixB(640,320)
Computing result using CUDA Kernel...
done
Performance= 15.17 GFlop/s, Time= 8.638 msec, Size= 131072000 Ops, WorkgroupSize= 1024 threads/block
Checking computed result for correctness: Result = PASS

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.
```

**Performance= 613.49 GFlop/s, Time= 0.214 msec**
```
~/project/serving $ cd tensorflow
~/project/serving/tensorflow $ bazel run --config=cuda //gpu:matrix_mult_cc 
INFO: Running command line: bazel-bin/gpu/matrix_mult_cc
[Matrix Multiply Using CUDA] - Starting...
GPU Device 0: "GeForce GTX 970" with compute capability 5.2

MatrixA(320,320), MatrixB(640,320)
Computing result using CUDA Kernel...
done
Performance= 613.49 GFlop/s, Time= 0.214 msec, Size= 131072000 Ops, WorkgroupSize= 1024 threads/block
Checking computed result for correctness: Result = PASS

NOTE: The CUDA Samples are not meant for performance measurements. Results may vary when GPU Boost is enabled.
```

**Comment by gautamvasudevan** [comment] 2018-08-03 20:01
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 20:01 UTC
