### ISSUE TITLE
Cannot assign a device to node

### ISSUE THREAD

**Issue by richfwebb** [tensorflow/serving#403] opened 2017-04-12 20:43 UTC
Ubuntu 16.04LTS
CUDA 8.0
Bazel 0.4.5
TF Serving master branch installed from: [here](https://tensorflow.github.io/serving/setup)
EDIT: I am also stuck at the same issue running the binary after installing and configuring branch r0.5.1

Attempting to build:
bazel build //tensorflow_serving/model_servers:tensorflow_model_server

I fixed the build errors by following some directions from: [here](https://github.com/tensorflow/serving/issues/318)
The initial error was:
```Cannot assign a device to node 'save_1/ShardedFilename_1': 
Could not satisfy explicit device specification '/device:GPU:0' 
because no devices matching that specification are registered in this process; 
available devices: /job:localhost/replica:0/task:0/cpu:0
```

After the build succeeded, running the binary results in a new error:
```
Cannot assign a device to node 'save_1/ShardedFilename_1':
Could not satisfy explicit device specification '/device:GPU:0' 
because no supported kernel for GPU devices is available.

Colocation Debug Info:
Colocation group had the following types and devices: 
Identity: CPU 
ShardedFilename: CPU 
ShardedFilename: CPU 
	 [[Node: save_1/ShardedFilename_1 = ShardedFilename[_output_shapes=[[]],
_device="/device:GPU:0"](save_1/StringJoin, save_1/ShardedFilename_1/shard, save_1/num_shards)]]
```

The gpu memory is fully allocated from 'nvidia-smi', and the gpu devices are recognized:
```
Creating TensorFlow device (/gpu:0) -> 
(device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0)
```

Outside of TF Serving, I load the model with tf.Session(session_config=...allow_soft_placement=True) and this sort of issue is bypassed. If I save the model with the parameter "clear_devices=True", then both the build and running the server binary succeed, and the GPU memory is fully used by the process "...ing/model_servers/tensorflow_model_server" once loaded.

Is this a bug or is there a way to allow_soft_placement of nodes? What node is causing this issue?

**Comment by chrisolston** [comment] 2017-06-13 18:24
I'm sorry you're having trouble. The first thing to do is to verify that you are building TensorFlow (core, not Serving) with cuda, to which the answer is likely "yes" if you followed https://github.com/tensorflow/serving/issues/318.

TF-Serving doesn't alter the node/device assignments so this may be a TF-Core issue. If allow_soft_placement makes it go away then that indicates that the node/device assignments in your graph are not achievable as-is, and need to be altered. You can inspect the protobuf of the metagraph file in the saved model and see what assignments are in there. Perhaps some ops that aren't gpu-compatible have been assigned to gpu? Alternatively if you don't have gpu support (e.g. no cuda) then having *any* op assigned to gpu would cause a failure.

**Comment by gautamvasudevan** [comment] 2018-08-03 19:56
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 19:56 UTC
