### ISSUE TITLE
Deploying TF model on Docker container and serving using tf_serving

### ISSUE THREAD

**Issue by soumya-ranjan-sahoo** [tensorflow/serving#781] opened 2018-02-23 14:45 UTC
Hi folks !

I got the following error message while trying to deploy my locally trained tf_model onto a docker container and serving it using tf_serving -

F tensorflow_serving/model_servers/main.cc:473] Non-OK-status: ServerCore::Create(std::move(options), &core) status: Invalid argument: Expected model tf to have an absolute path or URI; got base_path()=saved_model_tf
[1]+  Aborted                 (core dumped) bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --port=9000 --model_name=tf --model_base_path=saved_model_tf &> tf_log

Any help is highly appreciated.

Thanks in advance.

**Comment by Kindrat** [comment] 2018-02-23 21:39
model_base_path is absolute path inside a container to a directory with exported model, not just model name

**Comment by soumya-ranjan-sahoo** [comment] 2018-02-26 08:09
Hi Kindrat,

I have already included the path to directory where my trained model artifacts are. In my case saved_model_tf is the directory where I have my trained variables and the tf_graph. Any further help is appreciated.

Thanks.

**Comment by Kindrat** [comment] 2018-02-26 12:16
model_base_path expects absolute path, not just a directory name

**Comment by soumya-ranjan-sahoo** [comment] 2018-02-26 12:44
Super cool. Can you please help me figure out what an absolute path looks
like when my directory name is tf_model. I am all new to this ground.
Kindly help me.

Thanks in advance.

**Comment by Kindrat** [comment] 2018-02-26 13:41
https://en.wikipedia.org/wiki/Path_(computing)#Absolute_and_relative_paths

**Comment by gautamvasudevan** [comment] 2018-08-03 20:07
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 20:07 UTC
