### ISSUE TITLE
how to write a tensorflow serving platform_config_file

### ISSUE THREAD

**Issue by baodingge** [tensorflow/serving#584] opened 2017-09-01 03:00 UTC
I want to config session allow_soft_placement.

**Comment by chrisolston** [comment] 2017-09-01 03:27
Take a look at CreateTensorFlowPlatformConfigMap() in platform_config_util.cc. That should give you the info you need. allow_soft_placement is in SessionBundleSourceAdapterConfig->SessionBundleConfig->SessionConfig.

Alternatively, you could send a small PR to add --allow_soft_placement and/or --session_config_file flags to main.cc, and then you won't need to drop down to a platform config. This would make it more usable for yourself and others. (Optimistically, thank you in advance :)

**Comment by baodingge** [comment] 2017-09-01 03:38
I find this file , I thik it is not a good idea. platform_config_file can do all confit. I want to know how to write a config file, this may be better, I don't kow how to write it

**Comment by chrisolston** [comment] 2017-09-01 03:47
The file format is ascii protocol buffer. Unfortunately I'm not sure if there is good documentation of what that format looks like, but I'm sure you can at least find examples out on the web. See e.g. https://stackoverflow.com/questions/18873924/what-does-the-protobuf-text-format-look-like

**Comment by chrisolston** [comment] 2017-09-01 04:36
For anyone else who might be observing, there's more info at https://github.com/tensorflow/serving/issues/342

**Comment by baodingge** [comment] 2017-09-01 08:28
thank you very much .I have looked that answer, but don't know the details.I try this code, and find this way is not convenient. Each time you change this mai.cc you should compile the code.It takes too much time.
Now, i can run tensorflow serving with gpus, except which model has ops can not place in to gpu. One model is keras, and another is converted from caffe.
thanks very much.

**Comment by chrisolston** [comment] 2017-09-01 13:35
I think there was a misunderstanding. I am not suggesting doing it via code. You should create a text file containing the config and pass it in via the --platform_config_file. The reason I pointed you to the code in platform_config_util.cc is to show you how we populate the config in code to give you a sense of what the config should contain -- I think I may have confused you on that point.

In short, I think you can create a platform config *text file* along the lines of:

 platform_configs: {
  key: "tensorflow",
  value:  {
          source_adapter_config: {
            config: {
              allow_soft_placement: true
            }
          }
  }
}

**Comment by baodingge** [comment] 2017-09-04 01:52
It is wrong.I follow related prpto files, and find the related config proto.
platform_configs: {
    key: "tensorflow",
    value:  {
        source_adapter_config: {
			type_url: "type.googleapis.com/tensorflow.serving.SavedModelBundleSourceAdapterConfig"
			value:  {
			    legacy_config: {
					session_config:{
						allow_soft_placement:True
					}
				}
			}
    	}
    }
}
But there are still some wrong.Because values must be bytes .
message Any {
  // A URL/resource name whose content describes the type of the
  // serialized protocol buffer message.
  //
  // For URLs which use the scheme `http`, `https`, or no scheme, the
  // following restrictions and interpretations apply:
  //
  // * If no scheme is provided, `https` is assumed.
  // * The last segment of the URL's path must represent the fully
  //   qualified name of the type (as in `path/google.protobuf.Duration`).
  //   The name should be in a canonical form (e.g., leading "." is
  //   not accepted).
  // * An HTTP GET on the URL must yield a [google.protobuf.Type][]
  //   value in binary format, or produce an error.
  // * Applications are allowed to cache lookup results based on the
  //   URL, or have them precompiled into a binary to avoid any
  //   lookup. Therefore, binary compatibility needs to be preserved
  //   on changes to types. (Use versioned type names to manage
  //   breaking changes.)
  //
  // Schemes other than `http`, `https` (or the empty scheme) might be
  // used with implementation specific semantics.
  //
  string type_url = 1;

  // Must be a valid serialized protocol buffer of the above specified type.
  bytes value = 2;
}

**Comment by ales-t** [comment] 2017-10-05 15:30
This worked for me, maybe it could be helpful for others: https://github.com/tensorflow/serving/issues/342#issuecomment-334490108

**Comment by vitalyli** [comment] 2017-10-17 03:26
Is Soft Placement param helpful in case of multiple GPUs? I'm looking for way to make it utilize all 8 available GPUs.

**Comment by gautamvasudevan** [comment] 2018-08-03 20:16
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 20:16 UTC
