### ISSUE TITLE
C++ compilation of rule '//tensorflow_serving/servables/tensorflow:serving_session' failed

### ISSUE THREAD

**Issue by amirj** [tensorflow/serving#461] opened 2017-06-01 16:04 UTC
I can perfectly build both TensorFlow (GPU) and tf-serving (without CUDA support). Now, I'm trying to build TF-serving with CUDA support. The problem is that after running `bazel build --config=cuda tensorflow_serving/...`, the following error is appeared:

```
ERROR: /home/amir/projects/serving/tensorflow_serving/servables/tensorflow/BUILD:386:1: C++ compilation of rule '//tensorflow_serving/servables/tensorflow:serving_session' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter ... (remaining 126 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from tensorflow_serving/servables/tensorflow/serving_session.cc:16:0:
./tensorflow_serving/servables/tensorflow/serving_session.h:73:34: error: 'DeviceAttributes' was not declared in this scope
   Status ListDevices(std::vector<DeviceAttributes>* response) override {
                                  ^
./tensorflow_serving/servables/tensorflow/serving_session.h:73:50: error: template argument 1 is invalid
   Status ListDevices(std::vector<DeviceAttributes>* response) override {
                                                  ^
./tensorflow_serving/servables/tensorflow/serving_session.h:73:50: error: template argument 2 is invalid
./tensorflow_serving/servables/tensorflow/serving_session.h:73:10: error: 'tensorflow::Status tensorflow::serving::ServingSessionWrapper::ListDevices(int*)' marked 'override', but does not override
   Status ListDevices(std::vector<DeviceAttributes>* response) override {
          ^
./tensorflow_serving/servables/tensorflow/serving_session.h: In member function 'tensorflow::Status tensorflow::serving::ServingSessionWrapper::ListDevices(int*)':
./tensorflow_serving/servables/tensorflow/serving_session.h:74:22: error: 'class tensorflow::Session' has no member named 'ListDevices'
     return wrapped_->ListDevices(response);
                      ^
INFO: Elapsed time: 2077.663s, Critical Path: 334.59s

```

I'm using Ubuntu 16.04, CUDA 8.0, CuDNN 5 and gcc 5.4.0 and the latest version of TensorFlow and Bazel.

**Comment by amirj** [comment] 2017-06-01 16:06
The following is the `--verbose_failures`, if it can help:

``` 
ERROR: /home/amir/projects/serving/tensorflow_serving/servables/tensorflow/BUILD:386:1: C++ compilation of rule '//tensorflow_serving/servables/tensorflow:serving_session' failed: crosstool_wrapper_driver_is_not_gcc failed: error executing command 
  (cd /home/amir/.cache/bazel/_bazel_amir/966b8bcac9ca10b7138a16de173d472c/execroot/serving && \
  exec env - \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python \
  external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -U_FORTIFY_SOURCE '-D_FORTIFY_SOURCE=1' -fstack-protector -fPIE -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++11' -MD -MF bazel-out/local_linux-fastbuild/bin/tensorflow_serving/servables/tensorflow/_objs/serving_session/tensorflow_serving/servables/tensorflow/serving_session.pic.d '-frandom-seed=bazel-out/local_linux-fastbuild/bin/tensorflow_serving/servables/tensorflow/_objs/serving_session/tensorflow_serving/servables/tensorflow/serving_session.pic.o' -fPIC -DEIGEN_MPL2_ONLY -DSNAPPY -iquote . -iquote bazel-out/local_linux-fastbuild/genfiles -iquote external/org_tensorflow -iquote bazel-out/local_linux-fastbuild/genfiles/external/org_tensorflow -iquote external/bazel_tools -iquote bazel-out/local_linux-fastbuild/genfiles/external/bazel_tools -iquote external/protobuf -iquote bazel-out/local_linux-fastbuild/genfiles/external/protobuf -iquote external/eigen_archive -iquote bazel-out/local_linux-fastbuild/genfiles/external/eigen_archive -iquote external/local_config_sycl -iquote bazel-out/local_linux-fastbuild/genfiles/external/local_config_sycl -iquote external/gif_archive -iquote bazel-out/local_linux-fastbuild/genfiles/external/gif_archive -iquote external/jpeg -iquote bazel-out/local_linux-fastbuild/genfiles/external/jpeg -iquote external/com_googlesource_code_re2 -iquote bazel-out/local_linux-fastbuild/genfiles/external/com_googlesource_code_re2 -iquote external/farmhash_archive -iquote bazel-out/local_linux-fastbuild/genfiles/external/farmhash_archive -iquote external/fft2d -iquote bazel-out/local_linux-fastbuild/genfiles/external/fft2d -iquote external/highwayhash -iquote bazel-out/local_linux-fastbuild/genfiles/external/highwayhash -iquote external/png_archive -iquote bazel-out/local_linux-fastbuild/genfiles/external/png_archive -iquote external/zlib_archive -iquote bazel-out/local_linux-fastbuild/genfiles/external/zlib_archive -iquote external/snappy -iquote bazel-out/local_linux-fastbuild/genfiles/external/snappy -iquote external/local_config_cuda -iquote bazel-out/local_linux-fastbuild/genfiles/external/local_config_cuda -iquote external/gemmlowp -iquote bazel-out/local_linux-fastbuild/genfiles/external/gemmlowp -isystem external/bazel_tools/tools/cpp/gcc3 -isystem external/protobuf/src -isystem bazel-out/local_linux-fastbuild/genfiles/external/protobuf/src -isystem external/eigen_archive -isystem bazel-out/local_linux-fastbuild/genfiles/external/eigen_archive -isystem external/gif_archive/lib -isystem bazel-out/local_linux-fastbuild/genfiles/external/gif_archive/lib -isystem external/farmhash_archive/src -isystem bazel-out/local_linux-fastbuild/genfiles/external/farmhash_archive/src -isystem external/png_archive -isystem bazel-out/local_linux-fastbuild/genfiles/external/png_archive -isystem external/zlib_archive -isystem bazel-out/local_linux-fastbuild/genfiles/external/zlib_archive -isystem external/local_config_cuda/cuda/include -isystem bazel-out/local_linux-fastbuild/genfiles/external/local_config_cuda/cuda/include -isystem external/local_config_cuda/cuda -isystem bazel-out/local_linux-fastbuild/genfiles/external/local_config_cuda/cuda -isystem external/local_config_cuda/cuda/extras/CUPTI/include -isystem bazel-out/local_linux-fastbuild/genfiles/external/local_config_cuda/cuda/extras/CUPTI/include -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -fno-canonical-system-headers -c tensorflow_serving/servables/tensorflow/serving_session.cc -o bazel-out/local_linux-fastbuild/bin/tensorflow_serving/servables/tensorflow/_objs/serving_session/tensorflow_serving/servables/tensorflow/serving_session.pic.o): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
In file included from tensorflow_serving/servables/tensorflow/serving_session.cc:16:0:
./tensorflow_serving/servables/tensorflow/serving_session.h:73:34: error: 'DeviceAttributes' was not declared in this scope
   Status ListDevices(std::vector<DeviceAttributes>* response) override {
                                  ^
./tensorflow_serving/servables/tensorflow/serving_session.h:73:50: error: template argument 1 is invalid
   Status ListDevices(std::vector<DeviceAttributes>* response) override {
                                                  ^
./tensorflow_serving/servables/tensorflow/serving_session.h:73:50: error: template argument 2 is invalid
./tensorflow_serving/servables/tensorflow/serving_session.h:73:10: error: 'tensorflow::Status tensorflow::serving::ServingSessionWrapper::ListDevices(int*)' marked 'override', but does not override
   Status ListDevices(std::vector<DeviceAttributes>* response) override {
          ^
./tensorflow_serving/servables/tensorflow/serving_session.h: In member function 'tensorflow::Status tensorflow::serving::ServingSessionWrapper::ListDevices(int*)':
./tensorflow_serving/servables/tensorflow/serving_session.h:74:22: error: 'class tensorflow::Session' has no member named 'ListDevices'
     return wrapped_->ListDevices(response);
                      ^
INFO: Elapsed time: 7.217s, Critical Path: 3.83s
```

**Comment by QingdiMeng** [comment] 2017-06-06 08:15
There`s a new commit recently which may cause this problem.
https://github.com/tensorflow/serving/commit/92aa67923513a02e20499081397648c857bf8d54

I match same problem, and I just update sub modules of tensorflow and tf_model to newest, and build success !

**Comment by josauder** [comment] 2017-06-20 13:47
I have the same issue as OP. 

Is there anything special I have to consider when updateing submodules of tensorflow and tf_model other than just running `git pull --recurse-submodules`?

**Comment by xtr33me** [comment] 2017-07-07 01:33
I'm having this same issue as the OP. Does anyone have a solution for this yet? I pulled the latest from tensorflow and tf_models as well as tensorflow_serving. Still getting same error.  Any quick fix by chance for now?

**Comment by gautamvasudevan** [comment] 2018-08-03 19:57
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 19:57 UTC
