### ISSUE TITLE
certificate error when reading gcs with docker image 1.9.1, 1.10.0 (cpu)

### ISSUE THREAD

**Issue by lluunn** [tensorflow/serving#1060] opened 2018-08-17 00:00 UTC
## Bug Report
If this is a bug report, please fill out the following form in full:

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: docker 
- **TensorFlow Serving installed from (source or binary)**:  docker
- **TensorFlow Serving version**:  1.9.1 and 1.10.0
 
### Describe the problem
Error message:
```
Unavailable: Error executing an HTTP request: libcurl code 77 meaning 'Problem with the SSL CA cert (path? access rights?)', error details: error setting certificate verify locations:
CAfile: /etc/ssl/certs/ca-certificates.crt
CApath: none
when reading metadata of gs://kubeflow-examples-data/mnist
```

### Exact Steps to Reproduce
I am using GKE to deploy a TF serving deployment, with a model on GCS.
tensorflow/serving:1.8.0 works fine, but 1.9.1 and 1.10.0 show the above error.
1.10.0-gpu is also fine.

See
https://github.com/kubeflow/kubeflow/pull/1370#issuecomment-413703629

**Comment by gautamvasudevan** [comment] 2018-08-17 05:26
Duplicate of #1022

**Closed by gautamvasudevan** 2018-08-17 05:26 UTC
