### ISSUE TITLE
tensorflow-gpu  not work after install  tensorflow-serving-api    on my machine  

### ISSUE THREAD

**Issue by nongcunshaoye** [tensorflow/serving#929] opened 2018-06-11 08:43 UTC
tensorflow-gpu  not work after install  tensorflow-serving-api    on my machine

**Comment by nongcunshaoye** [comment] 2018-06-11 08:45
pip list  

tensorboard            1.8.0    
tensorflow  		   1.8.0  
tensorflow-gpu         1.8.0      
tensorflow-serving-api 1.8.0  

uninstall tensorflow   1.8.0     and   tensorflow-gpu  1.8.0   
next I  install tensorflow-gpu again  .  now  it works

**Comment by kakaluote** [comment] 2018-06-15 07:49
same problem. how can we make tensorflow-serving-api work with tensorflow-gpu

**Comment by nongcunshaoye** [comment] 2018-06-15 10:11
Now I  installed  tensorflow-serving-api on my computer   and     tensorflow-gpu installed on server

**Comment by gautamvasudevan** [comment] 2018-08-15 19:42
Does this still happen with tensorflow-serving-api 1.10.1?

**Comment by minggli** [comment] 2018-09-13 10:10
same here. it appears that tensorflow-serving-api has dependence on tensorflow (CPU) alone and does not consider tensorflow-gpu as its dependence.

**Comment by harshini-gadige** [comment] 2018-12-03 22:51
@nongcunshaoye  Is it the same with the newer version of tensorflow-serving-api ?
I see you were running into this issue with the version 1.8. Please try if you are running into the same issue with the latest version. 
Closing this for now. Please add your comments here if the issue persists with the newer version. We will reopen. Thanks !

**Closed** 2018-12-03 22:51 UTC
Labels: stat:awaiting tensorflower, type:build/install

**Comment by gautamvasudevan** [comment] 2018-12-03 22:59
Duplicate of #1142
