### ISSUE TITLE
How to change tensorflow-serving's rpc framework to thrift?

### ISSUE THREAD

**Issue by IvanJobs** [tensorflow/serving#792] opened 2018-03-02 09:10 UTC
Hi folks,
For historical reasons, I need to use thrift,  but can't find a neat way to achieve this goal.
I manually build tensorflow cpp lib and follow model_servers/BUILD to build a bunch of libs (server_core, ...).
I intend to use the underlining libs.
when I write a simple test.cpp to use ServerCore::Options, link errors occured.

my main.cpp:
`
#include <bits/stdc++.h>
#include "tensorflow_serving/model_servers/server_core.h"
using namespace std;

using tensorflow::serving::ServerCore;

int main() {
  ServerCore::Options options;
//  std::unique_ptr<ServerCore> core;
//  ServerCore::Create(std::move(options), &core);
  cout<<"fool"<<endl;
  return 0;
}
`

my bash:
`
g++ -std=c++11 -lserver_core ./main.cpp
`

link error:
`/tmp/ccxpp3Zh.o: In function `tensorflow::serving::ServerCore::Options::Options()':
main.cpp:(.text._ZN10tensorflow7serving10ServerCore7OptionsC2Ev[_ZN10tensorflow7serving10ServerCore7OptionsC5Ev]+0x15): undefined reference to `tensorflow::serving::ModelServerConfig::ModelServerConfig()'
main.cpp:(.text._ZN10tensorflow7serving10ServerCore7OptionsC2Ev[_ZN10tensorflow7serving10ServerCore7OptionsC5Ev]+0x41): undefined reference to `tensorflow::port::NumSchedulableCPUs()'
main.cpp:(.text._ZN10tensorflow7serving10ServerCore7OptionsC2Ev[_ZN10tensorflow7serving10ServerCore7OptionsC5Ev]+0x9a): undefined reference to `tensorflow::serving::PlatformConfigMap::PlatformConfigMap()'
main.cpp:(.text._ZN10tensorflow7serving10ServerCore7OptionsC2Ev[_ZN10tensorflow7serving10ServerCore7OptionsC5Ev]+0x122): undefined reference to `tensorflow::serving::ModelServerConfig::~ModelServerConfig()'
/tmp/ccxpp3Zh.o: In function `tensorflow::serving::ServerCore::Options::~Options()':
main.cpp:(.text._ZN10tensorflow7serving10ServerCore7OptionsD2Ev[_ZN10tensorflow7serving10ServerCore7OptionsD5Ev]+0x72): undefined reference to `tensorflow::serving::PlatformConfigMap::~PlatformConfigMap()'
main.cpp:(.text._ZN10tensorflow7serving10ServerCore7OptionsD2Ev[_ZN10tensorflow7serving10ServerCore7OptionsD5Ev]+0x9e): undefined reference to `tensorflow::serving::ModelServerConfig::~ModelServerConfig()'
/tmp/ccxpp3Zh.o: In function `tensorflow::serving::optional<std::string>::clear()':
main.cpp:(.text._ZN10tensorflow7serving8optionalISsE5clearEv[_ZN10tensorflow7serving8optionalISsE5clearEv]+0x54): undefined reference to `tensorflow::internal::LogMessageFatal::LogMessageFatal(char const*, int)'
main.cpp:(.text._ZN10tensorflow7serving8optionalISsE5clearEv[_ZN10tensorflow7serving8optionalISsE5clearEv]+0x77): undefined reference to `tensorflow::internal::LogMessageFatal::~LogMessageFatal()'
main.cpp:(.text._ZN10tensorflow7serving8optionalISsE5clearEv[_ZN10tensorflow7serving8optionalISsE5clearEv]+0x86): undefined reference to `tensorflow::internal::LogMessageFatal::~LogMessageFatal()'
/tmp/ccxpp3Zh.o: In function `tensorflow::serving::optional<std::string>::destruct()':
main.cpp:(.text._ZN10tensorflow7serving8optionalISsE8destructEv[_ZN10tensorflow7serving8optionalISsE8destructEv]+0x39): undefined reference to `tensorflow::internal::LogMessageFatal::LogMessageFatal(char const*, int)'
main.cpp:(.text._ZN10tensorflow7serving8optionalISsE8destructEv[_ZN10tensorflow7serving8optionalISsE8destructEv]+0x5c): undefined reference to `tensorflow::internal::LogMessageFatal::~LogMessageFatal()'
main.cpp:(.text._ZN10tensorflow7serving8optionalISsE8destructEv[_ZN10tensorflow7serving8optionalISsE8destructEv]+0xa6): undefined reference to `tensorflow::internal::LogMessageFatal::LogMessageFatal(char const*, int)'
main.cpp:(.text._ZN10tensorflow7serving8optionalISsE8destructEv[_ZN10tensorflow7serving8optionalISsE8destructEv]+0xc9): undefined reference to `tensorflow::internal::LogMessageFatal::~LogMessageFatal()'
main.cpp:(.text._ZN10tensorflow7serving8optionalISsE8destructEv[_ZN10tensorflow7serving8optionalISsE8destructEv]+0xd8): undefined reference to `tensorflow::internal::LogMessageFatal::~LogMessageFatal()'
main.cpp:(.text._ZN10tensorflow7serving8optionalISsE8destructEv[_ZN10tensorflow7serving8optionalISsE8destructEv]+0xe7): undefined reference to `tensorflow::internal::LogMessageFatal::~LogMessageFatal()'
collect2: error: ld returned 1 exit status`

any help would be appreciated:)

**Comment by ydp** [comment] 2018-03-05 09:32
With thrift, you need to build it with bazel first, since you might use TNonBlockServer, you need to build boost, libevent too.

I have compiled it here, you may refer it, see my commits:

https://github.com/ydp/serving

but the problem is, all interface in tensorflow use protocal buffer, if you want minimal change to the serving code, you need to define your own input format with thrift idl, serving receive it and copy it to proto format. In my above, I only define a simple interface for test use like below:

```
namespace cpp thriftApi

struct TModelSpec {
    1: string name,
    2: optional i32 version,
    3: optional string signature_name,
}

struct TTensorProto {
    1: i32 dim,
}

struct TPredictRequest {
    1: TModelSpec model_spec,
    2: optional map<string, TTensorProto> inputs,
    3: optional list<list<double>> vectors,
}

struct TPredictResponse {
    1: optional map<string, TTensorProto> outputs,
    2: optional list<double> probs,
}

service TPredictionService {
    TPredictResponse Predict(1:TPredictRequest req),
}
```

**Comment by gautamvasudevan** [comment] 2018-08-03 20:24
Duplicate of #588

**Closed by gautamvasudevan** 2018-08-03 20:24 UTC
