### ISSUE TITLE
Bazel build error on Archlinux with TFS 1.11

### ISSUE THREAD

**Issue by petronny** [tensorflow/serving#1178] opened 2018-11-09 06:02 UTC
## Bug Report
If this is a bug report, please fill out the following form in full:

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Archlinux
- **TensorFlow Serving installed from (source or binary)**: source
- **TensorFlow Serving version**: 1.11.0

### Describe the problem
According to the [GPU-Dockerfile](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel-gpu), it needs to add `--config cuda` to the `bazel build` command to enable the GPU support.

However, according to the [bazel releases page](https://github.com/bazelbuild/bazel/releases),
```
--[no]allow_undefined_configs no longer exists, passing undefined configs is an error.
```
as of version 0.16.0 and above.

So I'm getting
```
ERROR: Config value cuda is not defined in any .rc file
```
when building on Archlinux which is providing bazel 0.19.0.

### Exact Steps to Reproduce
I'm building it with the script on [AUR](https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=tensorflow-model-server-cuda):
```
$ wget https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=tensorflow-model-server-cuda -O PKGBUILD
$ makepkg
```
I've pasted the log in the next session.

### Source code / logs
```
==> Extracting sources...
  -> Extracting 1.11.0.tar.gz with bsdtar
==> Starting prepare()...
==> Starting build()...
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/build/tensorflow-model-server-cuda/src/serving-1.11.0/tools/bazel.rc
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
ERROR: Config value cuda is not defined in any .rc file
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by troycheng** [comment] 2018-11-09 09:12
Seems you miss `export TF_NEED_CUDA=1` env variable

**Comment by petronny** [comment] 2018-11-09 09:29
```
    export TF_NEED_CUDA=1
```
is in `prepare()`.

**Comment by gautamvasudevan** [comment] 2018-11-13 20:45
Try using bazel 0.15, which is the currently tested version of bazel used.

**Comment by ppwwyyxx** [comment] 2018-12-28 07:30
Please reopen it as the problem is not solved.

**Comment by hgadig** [comment] 2019-01-04 21:40
Reopened the issue as the problem still exist. 
@gautamvasudevan  PTAL

**Comment by unclepeddy** [comment] 2019-06-13 23:53
Closing as this is not a configuration supported by the project.

**Closed by unclepeddy** 2019-06-13 23:53 UTC
Labels: stat:community support, type:build/install
