### ISSUE TITLE
Remove local_repository

### ISSUE THREAD

**Issue by jart** [tensorflow/serving#212] opened 2016-10-21 01:09 UTC
The build files use local_repository() to refer to TensorFlow and other upstream projects. It would probably be better to use http_archive() and track a specific release version.

**Comment by gautamvasudevan** [comment] 2018-08-03 20:10
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 20:10 UTC
