### ISSUE TITLE
'pip install tensorflow-serving-api' uninstalling my current version of tensorflow and installing a new one

### ISSUE THREAD

**Issue by denisb411** [tensorflow/serving#1678] opened 2020-06-26 20:30 UTC
Currenly I'm using the docker version of tensorflow-gpu:1.15 and, when building a docker image from a Dockerfile, I need to download tensorflow-serving-api because my code requires it.
When it executes, it uninstalls my 1.15 version and installs the current one (2.2), which is not what I wanted. As a workaround I have to manually install 1.15 again using `RUN pip uninstall tensorflow && pip install tensorflow-gpu==1.15`. Was that supposed to occur?

This is kinda related with #1142 .

**Comment by minglotus-6** [comment] 2020-08-21 03:08
Hi Denis,
   `pip3 install --no-deps tensorflow-serving-api` works for me.

    Ways to reproduce
    1) `pip3 install tensorflow-gpu==2.2.0`
    2) `pip3 show tensorflow-gpu` returns `Version: 2.2.0`
    3) `pip3 install --no-deps tensorflow-serving-api`
    4) `pip3 show tensorflow-gpu` still returns `Version: 2.2.0` while `pip3 show tensorflow-serving-api` returns `2.3.0`.

    Please lmk for following up questions.

**Comment by minglotus-6** [comment] 2020-08-28 19:25
Got a thumb-up (thanks :D) from Dennis (original poster) so going to close this issue.

**Closed by minglotus-6** 2020-08-28 19:25 UTC
Labels: stat:awaiting tensorflower, type:build/install
