### ISSUE TITLE
how to load custom operation library

### ISSUE THREAD

**Issue by codeVerySlow** [tensorflow/serving#678] opened 2017-12-05 11:46 UTC
I export my model to saved model
I have some custom operation implemented by C++ and build to libcustomop.so
how to load my custom operation library when I use serving

**Comment by codeVerySlow** [comment] 2017-12-05 12:49
in training and testing I use tf.load_op_library(path) to load my custom operation 
how to load op library in serving

**Comment by kirilg** [comment] 2017-12-05 18:37
You can add your op/kernel BUILD targets to the list of [SUPPORTED_TENSORFLOW_OPS](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/BUILD#L109) and recompile the ModelServer.

**Comment by codeVerySlow** [comment] 2017-12-06 08:06
did we have some convenience way for load library
some way like `tensorflow_model_server --port=9000 --model_name=mnist --model_base_path=/tmp/mnist_model/ --op_path=/some/path/to/custom/library`

**Comment by kirilg** [comment] 2017-12-06 17:12
No, I believe the ops will need to be linked into the binary at compile time.

**Comment by bknl** [comment] 2017-12-13 14:03
With some surgery, this is possible without recompilation:

See the following patch in the "loadlibrary" branch.  Currently I only support a single user_op library, ideally this should be a list.

https://github.com/bknl/serving/commit/72ccb799d3fd6e35b2acfcde72e33737fdb723a9

**Comment by sukritiramesh** [comment] 2017-12-19 21:48
@codeVerySlow, looks like there are a couple of options listed here. Resolving for now, but please feel free to reopen if there are follow-up questions.

**Closed by sukritiramesh** 2017-12-19 21:48 UTC

**Comment by bknl** [comment] 2018-02-14 14:23
I am updating my serving source to 1.5 (and soon 1.6) and now have trouble with the loadable custom ops.
Aparently a "variant dtype op registry" was introduced, see https://github.com/tensorflow/models/issues/2355 and somehow parts of the initialization now somehow are called twice.

I can rebuild my custom ops in the "new" linking style with separately linking against "libtensor_framework" to make them work in TensorFlow 1.5, but when I try to load them with the patch in https://github.com/bknl/serving/commit/72ccb799d3fd6e35b2acfcde72e33737fdb723a9 , I now get te same double registration:

 external/org_tensorflow/tensorflow/core/framework/variant_op_registry.cc:104] Check failed: existing == nullptr (0x1ac59f28 vs. nullptr)Unary VariantDecodeFn for type_name: tensorflow::Tensor already registered

I cannot quite make heads or tails where the double registration happens.

**Comment by tobegit3hub** [comment] 2018-03-12 02:12
The code from @bknl is nice and it should be great to add this feature in master.

**Comment by tobegit3hub** [comment] 2018-03-12 07:27
If you are interested, we have the similar "TensorFlow Serving" which supports TensorFlow SavedModel and external custom op. It relies on the TensorFlow Python API to load custom op whiling starting the server. Refer to [simple_tensorflow_serving](https://github.com/tobegit3hub/simple_tensorflow_serving/tree/master/examples/custom_op) for more details.

It would be great if we can make the contribution back to the TensorFlow community 😃

**Comment by praveeny1986** [comment] 2018-04-27 11:40
Using tensorflow serving r1.6, I tried adding my custom op in tensorflow_serving/model_servers/BUILD
[here](https://github.com/tensorflow/serving/blob/r1.6/tensorflow_serving/model_servers/BUILD#L189)

```
SUPPORTED_TENSORFLOW_OPS = [
    "@org_tensorflow//tensorflow/contrib:contrib_kernels",
    "@org_tensorflow//tensorflow/contrib:contrib_ops_op_lib",
    **"//tensorflow_serving/myOp:myOp.so"** #Added this line
]
```

And myOp/BUILD:

```
package(
    default_visibility = [
        "//tensorflow_serving:internal",
    ],
    features = ["-layering_check"],
)

cc_library(
    name = "myOp.so",
    visibility = ["//visibility:public"],
    srcs = [
            "myOp.cc",
            "myOp.h"
           ] ,
    copts = ["-std=c++11"],
    deps = ["@org_tensorflow//tensorflow/core:framework_headers_lib",
            "@org_tensorflow//tensorflow/core/util/ctc",
            "@org_tensorflow//third_party/eigen3",
    ],
)
```
But I get this error while launching tensorflow_model_server
**Loading servable: {name: myModel version: 1} failed: Not found: Op type not registered 'MyOp' in binary running on 43e23d7f1ad2. Make sure the Op and Kernel are registered in the binary running in this process.**

Is it the correct way of adding custom Op in tensorflow serving ?

**Comment by qiaohaijun** [comment] 2018-05-17 07:49
@bknl I am in r1.6

**Comment by xuzhezhaozhao** [comment] 2018-05-31 02:19
@praveeny1986 I add a line ' alwayslink = 1 ' in myOp/BUILD and it worked.

`package(
    default_visibility = [
        "//tensorflow_serving:internal",
    ],
    features = ["-layering_check"],
)

cc_library(
    name = "myOp.so",
    visibility = ["//visibility:public"],
    srcs = [
            "myOp.cc",
            "myOp.h"
           ] ,
    copts = ["-std=c++11"],
    deps = ["@org_tensorflow//tensorflow/core:framework_headers_lib",
            "@org_tensorflow//tensorflow/core/util/ctc",
            "@org_tensorflow//third_party/eigen3",
    ],
    alwayslink = 1,
)`

**Comment by Remember2018** [comment] 2018-10-26 01:29
Hi, @xuzhezhaozhao, @praveeny1986 , I follow your method to compile my custom op into the `tensorflow_model_server`, the code was compiled successfully. But when I run the file, it says:

      Segmentation fault (core dumped)

When I didn't use the bazel to build the custom op (i.e., just use the `g++ -I... -L ... -o myop.so`), the `myop.so` can be loaded into the python environment and can run OK. 
I don't know where the problem is. 

Could you please give some advice? Thanks.

**Comment by CLIsVeryOK** [comment] 2018-12-21 09:13
@Remember2018  did you fix your problem? I also met the Segmentation fault problem when add myOp.so to serving. myOp.so can be loaded in python tensorflow environment

**Comment by highfly22** [comment] 2019-04-26 08:42
Try this command to remove unneeded shared library dependency
```
patchelf --remove-needed libtensorflow_framework.so libhash_op.so
```
