### ISSUE TITLE
How are multiple sequential models inferenced in TF serving?

### ISSUE THREAD

**Issue by smartvdo** [tensorflow/serving#525] opened 2017-07-16 15:10 UTC
Hi, 
I have two TF CNN models which are required to run sequentially. For example, to recognize human face, one has to use one TF model to detect the face, then use another model to position the feature points of one face, finally one more model is used to extract the feature. How could we inference these multiple models one by one in TF serving?

Thanks.

**Comment by eth-n** [comment] 2017-07-27 22:43
#528 is a duplicate of this (can issues this similar be merged?), and @mountaintom posted an idea there. He suggested using Celery for task management (http://www.celeryproject.org/).

Because of the extremely low likelihood that your models have the same inference time, you'll have to queue and batch requests to each model very responsibly. I recommend testing inference time for each model if you haven't already before setting up the server so you have a good idea of which model is going to bottleneck the others. You can have a version of each of your models loaded and ready for inference.

At this point, you also need to know which model takes up the most space with respect to the input batch size on your GPU (assuming here that you are doing inference on a GPU). For example, if one model can accept batches of 50 for an input placeholder of shape `[?, m, n]` for an `m` by `n` pixel image, the output of that model will have 50 in the outermost dimension. If the next model in your sequence fills the GPU's memory with a batch size of 30, you'd need to break up the output of the first model to feed the second. My intuition is that that would get expensive quickly (unless perhaps one model can accept an input that's a multiple of the last?), and that your best bet is to feed a batch size to the first that the others can accept as well.

I haven't seen any indication that you can persist a model's output at the server and use it as input to another model. I envision the solution to your problem with the current architecture is sending one batch to the first model, and sending the data in the response of each model as input to the next. Unfortunately this adds (multiple, in your case) serializations, parses, and wire time to each batch's inference time.

Perhaps you could look into writing up some sort of graph splice, then save that as a single graph. You would still be able to get the intermediate output results (where the model endpoints are defined currently) via the signature_def protobuf if you need that data too. One issue I could foresee here would be if each of your three models already takes up most of the space on the GPU, you would get out of memory errors by increasing the graph size.


Possibly useful links (your mileage with these tools may vary, I've only had success with graph_util.convert_variables_to_constants):
Some tools for trimming the graph size: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python/tools

Implementation of some graph utilities:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/graph_util_impl.py

**Comment by mountaintom** [comment] 2017-08-16 23:25
Good points. 

I just commented on #528, the reply may have made better sense to be here. So, I'll add it below.

-----

An addition point. Many production applications will require a cluster of machines to serve the traffic volume.

In those cases, each sub model would run on its own pool of machines. The size of each pool would be adjusted based on the work required for each mode.

As many AI models take a significant amount of time to process a request, batching like this will likely not be significantly slower (request to final result time) than streaming.

When things grow more, you probably should look into running your infrastructure under Mesos (or your preferred similar functionality), and adding in Hadoop or Spark.

When your models and application begin stabilize, and your volume grows, it will start to make economic sense to take what you have learned and invest development costs into increasing the efficiency of the application to balance the rising costs of adding servers.

**Comment by gautamvasudevan** [comment] 2018-08-03 20:14
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 20:14 UTC
