### ISSUE TITLE
Is there some things specific to do to use GPU with tensorflow serving ?

### ISSUE THREAD

**Issue by jrabary** [tensorflow/serving#499] opened 2017-06-23 21:43 UTC
With have an installation of tensorflow serving with GPU enable : tensorflow was configured with cuda and cudnn support. 
But, when we send request to the tf model server there are no difference in execution time between CPU and GPU. 
At this time we believe that GPU isn't used at all. Is because the graph is not correctly export or because tf serving is not compiled correctly ?

**Comment by xiaop1987** [comment] 2017-06-24 01:33
Does your model train on GPU? If do so, setting clear_devices=False when exporting model or build saved model may help.

**Comment by jrabary** [comment] 2017-07-07 09:25
@xiaop1987 I'm using the pretrained object detector model provided in the models repository. I've just re-export the model as saved model. But I didn't use clear_devices=False. Can it be an explanation ?

**Comment by jlertle** [comment] 2017-07-26 00:35
@jrabary Were you able to host the object detection models in serving? Having issues myself.

**Comment by gautamvasudevan** [comment] 2018-08-03 20:13
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 20:13 UTC
