### ISSUE TITLE
INVALID_ARGUMENT

### ISSUE THREAD

**Issue by koln2017** [tensorflow/serving#1286] opened 2019-03-18 07:02 UTC
**2019-03-18 06:58:44.164013: W external/org_tensorflow/tensorflow/core/framework/allocator.cc:122] Allocation of 14959711273176 exceeds 10% of system memory.
Traceback (most recent call last):
  File "autocut_client_grpc.py", line 140, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "autocut_client_grpc.py", line 133, in main
    result = stub.Predict(request, 10.0)  # 10 secs timeout
  File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 549, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.6/site-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "tensor parsing error: input_tensor"
	debug_error_string = "{"created":"@1552892324.164300190","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1039,"grpc_message":"tensor parsing error: input_tensor","grpc_status":3}"
**

**Comment by hgadig** [comment] 2019-03-19 20:46
Please fill the new issue [template](https://github.com/tensorflow/serving/issues/new). Also please provide exact commands or any code snippet to reproduce the error from our end. Thanks!

**Comment by hgadig** [comment] 2019-03-29 16:29
Closing as the issue is in "awaiting response" status for more than a week. Feel free to add your comments, we will reopen. Thanks!

**Closed by hgadig** 2019-03-29 16:29 UTC
Labels: stat:awaiting response, type:support
