### ISSUE TITLE
tensorflow serving: Running sesion.Run with operations (like fetches and feed) using tensorflow serving model server

### ISSUE THREAD

**Issue by ratsuresh** [tensorflow/serving#511] opened 2017-07-05 01:45 UTC
I have the following code for a tensorflow session.

sess = tf.Session()
saver = tf.train.import_meta_graph('./back/model.ckpt.meta')
saver.restore(sess, tf.train.latest_checkpoint('./back'))
And in the end I'm calling session.Run using the following command

for filename in filenames:
  with tf.gfile.GFile(filename, "r") as f:
    image = f.read()
    initial_state = sess.run(fetches="lstm/initial_state:0",
                         feed_dict={"image_feed:0": image})
Lets say I'm saving the above model and loading it via tensorflow serving. How can I achieve getting the initial state calling the below mentioned command

   sess.run(fetches="lstm/initial_state:0",
                         feed_dict={"image_feed:0": image})

Can I call this command using tensorflow serving. Tensorflow serving has a list of API for predict and classify, but if I need to provide my own operation in session.Run like the above example, how can I achieve that ?

**Comment by ratsuresh** [comment] 2017-07-05 18:01
I looked a little bit more into it and what I'm referring to I think is partial run.
Does tensorflow serving support partial run of graphs

**Comment by chrisolston** [comment] 2017-07-09 14:43
I think you can use the Predict API. Looking at PredictRequest the field "inputs" corresponds to "feed_dict" and "output_filter" corresponds to "fetches" (except the names get translated from aliases to tensor names based on the signature you set up in your saved-model).

**Comment by ratsuresh** [comment] 2017-07-10 04:59
thanks chrisolston,
You are right about the input and output. this is the modified code.

This is the code for saver

def export():
sess = tf.Session()
saver = tf.train.import_meta_graph('./back/model.ckpt.meta')
saver.restore(sess, tf.train.latest_checkpoint('./back'))
graph = tf.get_default_graph()
out_classes = graph.get_tensor_by_name('lstm/initial_state:0')
outputFromGraph = {'lstm/initial_state:0': 
tf.saved_model.utils.build_tensor_info(out_classes)}
input_classes = graph.get_tensor_by_name('image_feed:0')
inputFromGraph = {'image_feed:0': 
tf.saved_model.utils.build_tensor_info(input_classes)}
legacy_init_op = tf.group(tf.tables_initializer(), 
name='legacy_init_op')
prediction_signature = (
    tf.saved_model.signature_def_utils.build_signature_def(
        inputs=inputFromGraph,
        outputs=outputFromGraph, method_name=tf.saved_model.signature_constants.PREDICT_METHOD_NAME
    ))
builder.add_meta_graph_and_variables(
        sess, [tag_constants.SERVING],
        signature_def_map={
            'predict_images': prediction_signature
        },
        legacy_init_op=legacy_init_op)
builder.save()
return

**Comment by gautamvasudevan** [comment] 2018-08-03 19:58
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 19:58 UTC
