### ISSUE TITLE
No python3 tensorflow_serving_api package.

### ISSUE THREAD

**Issue by GrandathePanda** [tensorflow/serving#661] opened 2017-11-16 17:14 UTC
Our entire codebase is written in py3 and tensorflow proper supports py3 heavily. I was wondering if there is any plan to add this for py3 or should I just build from bazel.

**Comment by jkinkead** [comment] 2018-02-27 00:23
This is a duplicate of #700 .

**Comment by gautamvasudevan** [comment] 2018-07-24 21:18
Duplicate of #700

**Closed by gautamvasudevan** 2018-07-24 21:18 UTC
