### ISSUE TITLE
Undefined symbol while running bazel-bin  in _prefetching_ops.so

### ISSUE THREAD

**Issue by Immexxx** [tensorflow/serving#690] opened 2017-12-14 01:43 UTC
Context: 
Built tensorflow_serving successfully - from master branch (Dec 12th) - and able to run "bazel test -c opt tensorflow_serving/..." with all 60 tests passing 

(Tensorflow 1.4, Cuda 9, Cudnn 7) 

But when I try to run any bazel-bin command, for example, "bazel-bin/tensorflow_serving/example/mnist_saved_model /tmp/mnist_model" get the following error: 

`File "/d/serving/bazel-bin/tensorflow_serving/example/mnist_saved_model.runfiles/org_tensorflow/tensorflow/contrib/data/python/ops/prefetching_ops.py", line 25, in <module>
    resource_loader.get_path_to_datafile("../../_prefetching_ops.so"))
  File "/d/serving/bazel-bin/tensorflow_serving/example/mnist_saved_model.runfiles/org_tensorflow/tensorflow/contrib/util/loader.py", line 55, in load_op_library
    ret = load_library.load_op_library(path)
  File "/d/serving/bazel-bin/tensorflow_serving/example/mnist_saved_model.runfiles/org_tensorflow/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/d/serving/bazel-bin/tensorflow_serving/example/mnist_saved_model.runfiles/org_tensorflow/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /d/serving/bazel-bin/tensorflow_serving/example/mnist_saved_model.runfiles/org_tensorflow/tensorflow/contrib/data/python/ops/../../_prefetching_ops.so: undefined symbol: _ZNK6google8protobuf5Arena17OnArenaAllocationEPKSt9type_infom`

Any clues / ideas as to what the issue could be?

Thanks!

**Comment by chrisolston** [comment] 2017-12-14 04:51
This looks like a dupe of https://github.com/tensorflow/serving/issues/684

**Closed by chrisolston** 2017-12-14 04:51 UTC
