### ISSUE TITLE
Seq2Seq Model Serialization and Deserialization Problem

### ISSUE THREAD

**Issue by bugra** [tensorflow/serving#777] opened 2018-02-23 01:12 UTC
I am already using inception like model for image prediction in tensorflow serving in production and would like to use a tensorflow serving for a `seq2seq` model. However, I have a problem with serializing/deserializing a `tf_servable` in the tensorflow serving layer.

I am using `tf.data.TFRecordDataset` interface to train a Seq2Seq Model where the `valid['sample']` is a TFRecordDataSet and `valid['model']` is my seq2seq model:

```python
output = sess.run([valid['model'].beam_output] + list(valid['sample'].values()))
output, data = output[0], output[1:]
data = {k:v for k,v in zip(valid['sample'].keys(), data)}
output = output.predicted_ids[0].T
```
where data looks like this:
```
{'action': array([[1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 1., 1., 1., 1., 1., 1., 0., 0., 0.]], dtype=float32),
 'add_to_cart': array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 0., 0., 0.]], dtype=float32),
 'copy_labels': array([[1, 0, 0, 1, 1]]),
 'eos_inds': array([[ 5, 11, 16, 22, 25]]),
 'query_context': array([[   85,   115,    69,   370, 23373,     1,   515,   366,    75,
            19,   233,     1,   453,    75,    19,   233,     1, 18772,
            33, 21360,  2028,  1621,     1,  1340,   692,     1]]),
 'query_future': array([[1340,  995,  678,  692,    1]]),
 'query_inds': array([[0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3,
         3, 4, 4, 4]]),
 'raw_context': array([[b'outdoor products red backpack 30l | mrs meyers hand soap refill | lemon hand soap refill | scala womens cloche wool hats | turmeric capsules']],
       dtype=object),
 'raw_future': array([[b'turmeric 1000 mg capsules']], dtype=object),
 'time_features': array([[14.680066 , 14.680066 , 14.680066 , 14.680066 , 14.680066 ,
         14.680066 , 13.885922 , 13.885922 , 13.885922 , 13.885922 ,
         13.885922 , 13.885922 , 13.885863 , 13.885863 , 13.885863 ,
         13.885863 , 13.885863 , 12.056493 , 12.056493 , 12.056493 ,
         12.056493 , 12.056493 , 12.056493 ,  4.2195077,  4.2195077,
          4.2195077]], dtype=float32),
 'time_weight': array([1.], dtype=float32)}
```
and output is a numpy array:
```
array([[1340,    1,    1,    1,    1],
       [6840,  692,    1,    1,    1],
       [  20, 1340,  692,    1,    1],
       [4113,   16, 5708,    1,    1],
       [1340,  692, 5708,    1,    1],
       [1340,  692, 7655,    1,    1],
       [1340,  692,   20,    1,    1],
       [1340,  692,  995,  678,    1],
       [ 303, 1311, 1340,  692,    1],
       [ 303,  183, 1340,  692,    1]], dtype=int32)
```

So far so good. I can also save and load model into memory to reproduce this very easily. I do not have any problem with this.

However, I am not sure what I am doing for serializing this model into `tf_servable` is correct:

```python
export_path = os.path.join(
  tf.compat.as_bytes(export_base_path),
  tf.compat.as_bytes(str(version_number))
)

sess = tf.Session()
tf.reset_default_graph()
saver = tf.train.import_meta_graph(model_meta_path)


builder = tf.saved_model.builder.SavedModelBuilder(export_path)

feature_configs = {
    'x': tf.FixedLenFeature(shape=[], dtype=tf.string),
    'y': tf.FixedLenFeature(shape=[], dtype=tf.string),
}

serialized_example = tf.placeholder(tf.string, name="tf_example")
tf_example = tf.parse_example(serialized_example, feature_configs)
x = tf.identity(tf_example['x'], name='x')
y = tf.identity(tf_example['y'], name='y')
predict_signature_def_map = tf.saved_model.signature_def_utils.predict_signature_def(
    inputs={
        tf.saved_model.signature_constants.PREDICT_INPUTS: x
    },
    outputs={
        tf.saved_model.signature_constants.PREDICT_OUTPUTS: y
    }
)

legacy_init_op = tf.group(tf.tables_initializer(), 
                          name="legacy_init_op")

builder.add_meta_graph_and_variables(
    sess=sess,
    tags=[tf.saved_model.tag_constants.SERVING],
    signature_def_map={
        "predict_signature_map": predict_signature_def_map
    },
    legacy_init_op=legacy_init_op,
    
)

builder.save()
```

This does not specify the dataset that I feed, therefore in the deserialization within the `inputs` portion, it should be something different. I am only specifying the `inputs` broadly, but what I want to specify is actually the dictionary structure.

```
dict_keys(['action', 'query_inds', 'add_to_cart', 'eos_inds', 'query_future', 'time_features', 'raw_future', 'raw_context', 'time_weight', 'copy_labels', 'query_context'])
```
My dictionary keys are like this and I have correct placeholder types for this dict.

When I am trying to deserialize this model and pass a dictionary:

```python
def get_prediction_response(stub,
                            data,
                            model_name=MODEL_NAME,
                            signature_name=SIGNATURE_NAME,
                            timeout_in_seconds=TIMEOUT_IN_SECONDS):
  request = predict_pb2.PredictRequest()
  request.model_spec.name = model_name
  request.model_spec.signature_name = signature_name
  request.inputs['inputs'].CopyFrom(tf.contrib.util.make_tensor_proto(data, shape=[1]))

  return stub.Predict(request, timeout_in_seconds) 
```

I am trying to pass either a string or a dictionary in the data portion, but I am getting `input does not match size`. Can someone help me to define the classification signature so that serializing and deserialzing would match?

Ideally, I would like to feed a dictionary to `tf_servable` model and would like to get the prediction.

**Comment by bugra** [comment] 2018-02-23 16:13
I am getting the following error:
```
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.INVALID_ARGUMENT, details="You must feed a value for placeholder tensor 'seq2seq' with dtype string
         [[Node: seq2seq = Placeholder[_output_shapes=[<unknown>], dtype=DT_STRING, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]")
```

@chrisolston Do you know what might be the problem is? If you can provide an example on dictionary passing for the tensorflow model, that would be also really good.

**Comment by gautamvasudevan** [comment] 2018-08-03 20:09
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 20:09 UTC

**Comment by ganni** [comment] 2018-10-11 01:15
@bugra Hi! did you solved your problem? I'm facing same error when trying to start serving server :(
can you please help me if you have solution?


> I am getting the following error:
> 
> ```
> grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.INVALID_ARGUMENT, details="You must feed a value for placeholder tensor 'seq2seq' with dtype string
>          [[Node: seq2seq = Placeholder[_output_shapes=[<unknown>], dtype=DT_STRING, shape=<unknown>, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]")
> ```
> @chrisolston Do you know what might be the problem is? If you can provide an example on dictionary passing for the tensorflow model, that would be also really good.
