### ISSUE TITLE
Does tensorflow serving support compression during stub.Predict()?

### ISSUE THREAD

**Issue by atomextranova** [tensorflow/serving#516] opened 2017-07-11 01:53 UTC
I do know that gRPC supports compression algorithm, but I am not sure if I could do compression for the Predict request (with an array stands for a graph to be predicted) and the corresponding response without modifying the source code?

**Comment by insikk** [comment] 2017-09-25 03:57
I haven't checked yet, but you can try something like below. 

```python

import grpc
from grpc._cython.cygrpc import CompressionAlgorithm
from grpc._cython.cygrpc import CompressionLevel


options = [('grpc.max_receive_message_length', -1),
             ('grpc.default_compression_algorithm', CompressionAlgorithm.gzip),
             ('grpc.grpc.default_compression_level', CompressionLevel.high)]
channel = grpc.insecure_channel(host if port is None else '%s:%d' % (host, port), options)

channel = implementations.Channel(channel)
stub = prediction_service_pb2.beta_create_PredictionService_stub(channel)
```

**Comment by gautamvasudevan** [comment] 2018-08-03 20:16
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 20:16 UTC
