### ISSUE TITLE
TensorFlow Serving example clients can't support Python 3 now

### ISSUE THREAD

**Issue by seetea** [tensorflow/serving#22] opened 2016-03-23 09:41 UTC
It's depressing when I finally find TensorFlow Serving can't support python 3 now. 

In fact, I'm trying to build TensorFlow Serving under python 3.4 because I have been working on tensorflow 0.7.1 for python 3.4 for a while. And I don't find any statement that TensorfFlow Serving can only run on python 2.x.

I used the methods in #21 to make "tensorflow_serving/example/mnist_export.py" and "tensorflow_serving/example/mnist_client.py" support python 3.4.  

Then the mnist_inferenece can be built and run on python 3.4 successfuly:

```
$ bazel-bin/tensorflow_serving/example/mnist_inference --port=9000 /tmp/mnist_model/00000001
I tensorflow_serving/session_bundle/session_bundle.cc:109] Attempting to load a SessionBundle from: /tmp/mnist_model/00000001
I tensorflow_serving/session_bundle/session_bundle.cc:86] Running restore op for SessionBundle
I tensorflow_serving/session_bundle/session_bundle.cc:157] Done loading SessionBundle
I tensorflow_serving/example/mnist_inference.cc:163] Running...
```

The mnist_client can also be built successfuly.

But when I run "bazel-bin/tensorflow_serving/example/mnist_client --num_tests=1000 --server=localhost:9000", I got "ImportError: No module named 'grpc'". 

Unfortunately, gRPC can't support python 3 now. You can find the reason at [Python3.4 support #282](https://github.com/grpc/grpc/issues/282). 

So is that mean TensorFlow Serving can't support python 3 until gRPC can support python 3?  

Is there any plan to let TensorFlow Serving support thrift? thriftpy has been able to support python2.6+, python3.3+, pypy and pypy3.

**Comment by kirilg** [comment] 2016-03-23 17:06
Only the example clients are using python gRPC, so the rest of TensorFlow Serving should still work for you (actually running a server that can handle requests). Unfortunately like you pointed out, until gRPC supports python 3.4, it appears the actual example clients will not work with 3.4.

TensorFlow Serving is not tied to gRPC, that's just what we use in our examples, but you can easily substitute it with any other RPC framework. Please see http://tensorflow.github.io/serving/architecture_overview (the majority of TensorFlow Serving in what's in the "core" section in the "Life of a Servable" diagram).

We don't have any plans to add thrift support right now, but having configurable components (in this case frontend components like the RPC framework) is exactly what it was designed for, so any community contributions to add that are welcome!

**Comment by seetea** [comment] 2016-03-24 11:03
Thank you, Kirilg. I have modified the issue's title to make it more clear.

**Comment by waaran** [comment] 2017-06-20 11:52
Thanks a lot for pointing it out, Kirilg. I'm trying to run inception-client on python3.5 and encountered the same error. I've searched many places for this error and finally get the reason here.
The weird message has mis-led me several days. 
It might be the same reason as inception-client also use gRPC.

But it seems one year passed, does gRPC still not support Python 3?

**Comment by nkconnor** [comment] 2017-06-28 19:47
With https://github.com/grpc/grpc/issues/282 grpc now supports Python 3 so this should run fine. There are a few mods you need to make to build using Python3 (see #504)

**Comment by gautamvasudevan** [comment] 2018-06-28 04:20
Duplicate of #700

**Closed by gautamvasudevan** 2018-06-28 04:20 UTC
Labels: contributions welcome
