### ISSUE TITLE
Where do Google Cloud Storage credentials come from? How to provide one?

### ISSUE THREAD

**Issue by orian** [tensorflow/serving#744] opened 2018-01-30 07:44 UTC
In many Google' apps the credentials come from `GOOGLE_APPLICATION_CREDENTIALS`.

I want to run a `tensorflow_model_server` on Kubernetes with node without read access but my model is on Google Cloud Storage.

GC allows me to generate a file with account permissions in JSON format. I would like to provide such file for server.

According to: https://cloud.google.com/docs/authentication/production#auth-cloud-implicit-go on Kubernetes they're default permissions. But in cluster settings it's called "legacy" and personally I don't trust _magic_ because it tends to break in the least expected moment.

**Comment by gautamvasudevan** [comment] 2018-08-03 20:03
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 20:03 UTC
