### ISSUE TITLE
Inception Model fails to run on Kubernetes

### ISSUE THREAD

**Issue by jason-riddle** [tensorflow/serving#287] opened 2017-01-07 21:59 UTC
From the second step from the following guide: https://tensorflow.github.io/serving/serving_inception, tensorflow_serving is failing to run after creating the deployment with `kubectl create -f tensorflow_serving/example/inception_k8s.yaml`.

Here is the log output I get.

```
/bin/sh: 1: /serving/bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server: not found
```

**Comment by kirilg** [comment] 2017-01-09 22:35
I think that path should not start with a '/' since that makes it an absolute path. Can you try updating [this line](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_k8s.yaml#L19) to be `serving/bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server`?

**Comment by mountaintom** [comment] 2017-02-16 16:39
There is an existing (11 month old) image on-line with the tag name specified in the "inception_k8s.yaml" file. If you built your Kubernetes inception serving cluster before building and pushing your own inception Docker image, the default one may have been loaded. The default image does not have the tensorflow_model_server command installed. 

If you would like to try the Kubernetes inception serving cluster without building your own Docker image, I’ve pushed one to Dockerhub as “mountaintom/tensorflow-serving-inception-kubernetes-demo”.

Update your yaml file to load this image  “mountaintom/tensorflow-serving-inception-kubernetes-demo” instead of the “gcr.io/tensorflow-serving/inception” image.

As things are moving fast with the tensorflow-serving code, my image is based on a one week old commit of the code. I have not tested with the latest commit. Should there be any incompatible changes with the latest server/client code you could pull a copy of this same Docker image and run the client, already built in the image, from your local machine. Some test photos are included in the “/serving/inception-client-test-photos/“ directory.  The bash history may have some useful examples in it.

**Comment by gautamvasudevan** [comment] 2018-08-03 19:53
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce. Thanks!

**Closed by gautamvasudevan** 2018-08-03 19:53 UTC

**Comment by gautamkmr** [comment] 2018-11-05 21:53
Just realized that tensorflow_model_server binary moved to /usr/bin folder
