### ISSUE TITLE
how to improve tf serving performance

### ISSUE THREAD

**Issue by liumilan** [tensorflow/serving#1950] opened 2021-12-11 16:25 UTC
Now I train a recommend  nn model offline ,and then predict it by tf serving on cpu online machine. There are 8 cores i just applied, and found it cost slow when predict it. More than 0.4% it costs 100ms when predict. The batch size request is 50. There are 167 one hot features and 3 full-connected layers.And the usage of cpu is also slow, it is only 20% usage.
How can i analyze the bottleneck of serving ,and can it possible to reduce the time cost ratio by adjust some parameters?

**Comment by sanatmpa1** [comment] 2021-12-13 17:21
@liumilan,

Have you got a chance to look at this official [performance guide](https://www.tensorflow.org/tfx/serving/performance) and also can you take a look at this [link](https://mux.com/blog/tuning-performance-of-tensorflow-serving-pipeline/)? Thanks!

**Comment by naveen-marthala** [comment] 2021-12-18 13:29
How to deploy tf-serving for maximum throughput for inference? is it recommended to use any specifiic web-framewrok(e.g., fastAPI, Flask) along with a WSGI(e.g,. gunicorn) with some set configuration(like worker type) and put it behind some web server or reverse proxy like nginx(or nginx API Gateway).

I would like to know what type of configurations have worked for most people, to take deployment decisions at my side accordingly.

**Comment by sanatmpa1** [comment] 2021-12-23 14:11
@naveen-marthala,

As your question is not a bug/performance/feature request, I would recommend you to open this issue in tf discussion [forum](https://discuss.tensorflow.org/) as there is a larger community there. Thanks!

**Comment by sanatmpa1** [comment] 2021-12-29 05:25
@liumilan,

Closing this issue due to lack of recent activity. You can refer to my above [comment](https://github.com/tensorflow/serving/issues/1950#issuecomment-992699573) and please feel free to open the issue in future if the problem still persists. Thanks!

**Closed by sanatmpa1** 2021-12-29 05:25 UTC
Labels: stat:awaiting response, type:support
