### ISSUE TITLE
Failed to start server. Error: Invalid argument: No request-logger-creator provided.

### ISSUE THREAD

**Issue by krislc** [tensorflow/serving#1846] opened 2021-04-21 09:47 UTC
anyone knows how to log predictions for docker tf-serving ?

**Comment by arghyaganguly** [comment] 2021-04-21 12:44
@krislc , please check with the below format  when starting the Tensorflow serving container :- 

docker run -t --rm -p 8501:8501 \
    -v "$TESTDATA/saved_model_half_plus_two_cpu:/models/half_plus_two" \
    -e -e TF_CPP_MIN_VLOG_LEVEL=1 MODEL_NAME=half_plus_two \
    tensorflow/serving &

**Comment by arghyaganguly** [comment] 2021-04-21 12:52
note: duplicate of #408.
@krislc , can we close this here and follow #408 instead?

Also, have you checked with enabling the TF_CPP_MIN_VLOG_LEVEL in the docker command(like below)? 
docker ... -e TF_CPP_MIN_VLOG_LEVEL=4 ...

**Comment by krislc** [comment] 2021-04-22 02:50
#408

**Closed** 2021-04-22 02:49 UTC
Labels: stat:awaiting response, type:support
