### ISSUE TITLE
Can't import inception_model

### ISSUE THREAD

**Issue by mkemka** [tensorflow/serving#354] opened 2017-03-13 21:01 UTC
This is a basic question and the issue may be my inexperience with docker.
I have followed the tutorial directly on this page:

When I run this step:
bazel-bin/tensorflow_serving/example/inception_saved_model --checkpoint_dir=inception-v3 --output_dir=inception-export

I get a basic import error:
   from inception import inception_model
ImportError: cannot import name inception_model

I can see the inception_model file in the tf_models subdirectory but I can't seem to add it to the path for the function to pick up.

**Comment by abdasgupta** [comment] 2017-03-14 09:37
Exactly the same problem I am facing too

**Comment by mkemka** [comment] 2017-03-14 23:17
I thought the fix would be to copy the models to the PYTHONPATH but it still does not seem to recognise it.

**Comment by NicolasAlmeida** [comment] 2017-03-15 14:19
I face the same problem. Do you already know a possible fix in order to not get this error?

**Comment by ybbaigo** [comment] 2017-03-16 04:55
+1

**Comment by ptrblck** [comment] 2017-03-17 10:36
Hi,

I guess it is not the best way to get around this issue, but I tried the following:

* Pull the tensorflow models 
`git pull http://github.com/tensorflow/models`

The `ImportError` is thrown from
 /serving/bazel-bin/tensorflow_serving/example/inception_saved.model.runfiles/tf_serving/tensorflow_serving/example/inception_saved_model.py, 
which is a symbolic link to /serving/tensorflow_serving/example/inception_saved_model.py.

* Create symbolic links from the missing inception model files to /serving/tensorflow_serving/example:
`ls -s ~/models/inception/inception/ /serving/tensorflow_serving/example/inception`

Now the files should be in the right location, but python cannot import them as a module, because the `__init__.py` files are missing in the directories.

* Create `__init__.py` files, to let python import the desired files:
`cd /serving/tensorflow_serving/example/inception
touch __init__.py
cd slim
touch __init__.py`

After these steps, I could succesfully run
`bazel-bin/tensorflow_serving/example/inception_saved_model --checkpoint_dir=inception-v3 --output_dir=inception-export`

I hope it helps you guys!

**Comment by azagovora** [comment] 2017-03-18 17:45
Thank you!!!

**Comment by mohan-chinnappan-n** [comment] 2017-03-19 00:33
Thank you, @ptrblck . Your steps fixes this issue! 👍 

Can we fix this in docker image itself using the steps: @ptrblck: 

```
1. cd ; git clone https://github.com/tensorflow/models
2. ln -s ~/models/inception/inception/ /serving/tensorflow_serving/example/inception

# lrwxrwxrwx 1 root root 33 Mar 18 22:55 /serving/tensorflow_serving/example/inception -> /root/models/inception/inception/

3. touch /serving/tensorflow_serving/example/inception/__init__.py
4. touch /serving/tensorflow_serving/example/inception/slim/__init__.py

````

**Comment by mountaintom** [comment] 2017-03-19 04:06
HI,

I ran into this issue, also, doing a new build. Here is how I fixed it.
(Run these commands from the /serving directory.)

```
/serving# git checkout 1be938e tensorflow_serving/example/BUILD 
/serving# git checkout 1be938e tensorflow_serving/workspace.bzl
bazel build -c opt tensorflow_serving/example/...
```

Now the command:
```
/serving# bazel-bin/tensorflow_serving/example/inception_saved_model --checkpoint_dir=inception-v3 --output_dir=inception-export
```
Should work.

**Note**: use exactly the same options with the bazel build command as you did when you did the original bazel build, otherwise bazel may try to rebuild nearly everything, rather than just the examples.

In my case I originally built with the "_-c opt_" setting.

**Comment by gautamvasudevan** [comment] 2018-08-03 19:53
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce. Thanks!

**Closed by gautamvasudevan** 2018-08-03 19:53 UTC
