### ISSUE TITLE
Text based model export usable for Serving!?

### ISSUE THREAD

**Issue by JoelGooch** [tensorflow/serving#562] opened 2017-08-14 08:46 UTC
Hi, I'm having trouble getting a text based model (Sentiment Analysis in my case) to export and function for use with Serving (using the SavedModelBuilder). I want to send some text from the client and simply decode this on the server end so it can then be converted to vector space and passed through the network. 

       # Input transformation.
       serialized_tf_example = tf.placeholder(tf.string, name='tf_example')
       feature_configs = {
            'image/encoded': tf.FixedLenFeature(
            shape=[], dtype=tf.string),
       }
       tf_example = tf.parse_example(serialized_tf_example, feature_configs)
       jpegs = tf_example['image/encoded']
       images = tf.map_fn(preprocess_image, jpegs, dtype=tf.float32)

From what I can see, in the inception example, these above lines take in the incoming image stream and converts it into a tensor that can be passed through the network. I require the same process but simply converting the incoming text stream, ideally back into a standard string so I can pass it through a conversion function, which then gives me the numerical vector representation of that text to pass through the net. 

Any help is much appreciated, Thanks!

**Comment by gautamvasudevan** [comment] 2018-08-03 20:13
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 20:13 UTC
