### ISSUE TITLE
TensorFlow Model Server returns different results during Inference

### ISSUE THREAD

**Issue by LouiseAbela** [tensorflow/serving#727] opened 2018-01-16 15:55 UTC
Hey,

I have a model saved by SavedModelBuilder with meta_graph, but can't figure out how to infer with it to get the correct detections.

I'm trying to infer using this format:

<with tf.Session(graph=tf.Graph()) as sess:

        tf.saved_model.loader.load(sess, ["serve"], folder_path)

        graph = tf.get_default_graph()
        x = graph.get_tensor_by_name('Placeholder:0')
        y = graph.get_tensor_by_name('vgg_16/cls_score/BiasAdd:0')
        y_1 = graph.get_tensor_by_name('vgg_16/cls_prob:0')
        y_2 = graph.get_tensor_by_name('add:0')
        y_3 = graph.get_tensor_by_name('vgg_16/rois/concat_1:0')

       _, scores, bbox_pred, rois = sess.run([y, y_1,y_2, y_3], feed_dict={x: new_im[0]})>

Right now I get random detections, some right but mostly wrong and missing. I'm thinking that somehow I have to restore the variables? I have a folder with 2 variable files. 

Thanks very much

**Comment by chrisolston** [comment] 2018-02-05 19:45
tf.saved_model.loader.load() is supposed to restore the variables internally, so you shouldn't need to do anything extra to get get the variables restored. Do verify that the variables are indeed present (look for a variables/ subdir under your saved model dir).

If you are getting wrong predictions there are many possible explanations, so it could be something other than variable restoration.

**Comment by gautamvasudevan** [comment] 2018-08-03 20:06
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 20:06 UTC
