### ISSUE TITLE
build docker image error

### ISSUE THREAD

**Issue by NobleYd** [tensorflow/serving#960] opened 2018-06-25 09:59 UTC
INFO: Analysed target //tensorflow_serving/model_servers:tensorflow_model_server (122 packages loaded).
INFO: Found 1 target...
[1,823 / 2,296] 2 actions running
    Compiling external/org_tensorflow/.../kernels/svd_op_double.cc; 480s local
    Compiling external/org_tensorflow/.../kernels/svd_op_float.cc; 473s local
The command '/bin/sh -c bazel build -c opt --color=yes --curses=yes ${TF_SERVING_BUILD_OPTIONS}     --output_filter=DONT_MATCH_ANYTHING     tensorflow_serving/model_servers:tensorflow_model_server &&     cp bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server /usr/local/bin/ &&     bazel clean --expunge --color=yes &&     rm -rf /root/.cache' returned a non-zero code: 137

**Comment by gautamvasudevan** [comment] 2018-06-25 18:37
Duplicate of #939

**Closed by gautamvasudevan** 2018-06-25 18:37 UTC
