### ISSUE TITLE
Documents for runtime model config reload

### ISSUE THREAD

**Issue by sparkingarthur** [tensorflow/serving#1057] opened 2018-08-15 08:18 UTC
I have the same needs as issue #380 , which means that I need to be able to dynamically add new models for serving. Actually i find a solution in this issue ( which is add a thread to check directory and rebuild a ModelServerConfig and use the ServerCore::ReloadConfig method to reload the config. The problem is that my C++ is already a but rusty by now and I don't fully understand yet all parts of TF serving, including the BUILD file of bazel, so i try to find a simpler way to meet my needs. Then i find PR #774 , but i don't know how to use this api exactly. Could you please give me an example or some documents to show how to use this api to reload model config at runtime exactly? Thx a lot.

ref:[https://github.com/tensorflow/serving/pull/774](#774 )

**Comment by gautamvasudevan** [comment] 2018-08-15 18:46
Duplicate of #380.

**Closed by gautamvasudevan** 2018-08-15 18:46 UTC
