### ISSUE TITLE
Exposing model version for models loaded by model_server

### ISSUE THREAD

**Issue by shrutisharmavsco** [tensorflow/serving#612] opened 2017-10-03 23:01 UTC
My use case is that I would like to access the `version` for the models loaded by model_server in [inception_client.cc](https://github.com/tensorflow/serving/blob/r1.3/tensorflow_serving/example/inception_client.cc) so the client can return the model version number in its response. For example, if I have two versions of the same model loaded via model_server using `specific` model version policy in `model_config_file` and I change the client code to create two different prediction requests with `prediction_request.mutable_model_spec()->mutable_version()->set_value(...);` set differently for both prediction requests. In this way, I can run inference on both the models but in order to set the value of `prediction_request.model_spec.version` from the client, I need to know which versions are loaded. How can I know that?

One potential place where I felt that this information could be available is `GetModelMetadata` [proto](https://github.com/tensorflow/serving/blob/r1.3/tensorflow_serving/apis/get_model_metadata.proto) However, since `GetModelMetadataRequest` also takes a `model_spec`, my understanding is that the intended use of `GetModelMetadata()` in `PredictionService` [proto](https://github.com/tensorflow/serving/blob/r1.3/tensorflow_serving/apis/prediction_service.proto) is to specify a `model_spec` with certain `name` and `version` and get the corresponding `signature_def` when multiple versions are loaded. Could there be a way in which we can use `GetModelMetadata` to also give us which various versions are loaded if we specify just the `name` in the `model_spec`?

**Comment by promiseofcake** [comment] 2017-10-11 13:52
@chrisolston, any guidance you could provide here or insight to future plans?

**Comment by chrisolston** [comment] 2017-10-21 12:43
Unfortunately I don't believe we currently offer a way to discover which version(s) are loaded. We're discussing internally the possibility of adding such a (very sensible :) feature, possibly via GetModelMetadata as you suggest. Stay tuned.

**Comment by promiseofcake** [comment] 2017-10-21 19:27
Thanks @chrisolston!

**Comment by vitalyli** [comment] 2017-11-13 23:42
Would be good to have version long number baked right into the same response object. Hopefully one extra 64bit long number is not too much of an overhead, but it is indeed very useful to have.

**Comment by harshini-gadige** [comment] 2018-10-25 18:02
@chrisolston -  Hi, any inputs for the above ?

**Comment by lilao** [comment] 2018-12-04 18:01
If you know the versions of the model in the model_config_file, you can send inference requests with those versions. If you get not_found error for a request, it means that the version specified in the request is not loaded.

If you don't know the versions of the model, you can try to read the model_config_file in your client to get the model versions and follow the steps in the above paragraph. Alternatively, you can add model version labels to the model_config_file, and send inference requests with those version labels (for details see https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/serving_config.md). In this way, you don't need the specific model versions and can just use version labels instead.

Would this work for you?

**Comment by hgadig** [comment] 2019-01-15 00:21
@shrutisharmavsco  Did you get a chance to try above workaround ? Please update the status. If the issue is resolved, feel free to close this.

**Comment by hgadig** [comment] 2019-02-11 18:20
Closing this at it is in "awaiting response" status for more than a week. Feel free to add comments(if any), we will reopen the issue. Thanks !

**Closed by hgadig** 2019-02-11 18:20 UTC
Labels: stat:awaiting response, type:support
