### ISSUE TITLE
What will happen if the request throughput is higher than the actual throughput of the server? 

### ISSUE THREAD

**Issue by XunChangqing** [tensorflow/serving#520] opened 2017-07-13 01:46 UTC
Assume my server can only process 1 image per second, what will happen if the client send 2 requests per second? Will the latency be bigger and bigger？

**Comment by chrisolston** [comment] 2017-07-13 02:51
Certainly the latency could start going up. I don't know at what point gRPC will stop accepting/enqueueing requests and start returning errors instead. Perhaps someone else knows, or the gRPC documentation would indicate?

**Comment by XunChangqing** [comment] 2017-07-15 02:51
Thanks, I'll check the grpc documentation.

**Comment by mountaintom** [comment] 2017-07-18 10:10
Hi,

I ran a very simple minded load test as follows:

$ run_batch_of_inception_clients.sh

```bash
#!/bin/bash
time ./gen/bin/inception_client --server_port="107.xxx.xxx.xxx:9000" --image_file="grace_hopper.jpg" &> inception_client_batch_test01.txt &
time ./gen/bin/inception_client --server_port="107.xxx.xxx.xxx:9000" --image_file="grace_hopper.jpg" &> inception_client_batch_test02.txt &
time ./gen/bin/inception_client --server_port="107.xxx.xxx.xxx:9000" --image_file="grace_hopper.jpg" &> inception_client_batch_test03.txt &
time ./gen/bin/inception_client --server_port="107.xxx.xxx.xxx:9000" --image_file="grace_hopper.jpg" &> inception_client_batch_test04.txt &
time ./gen/bin/inception_client --server_port="107.xxx.xxx.xxx:9000" --image_file="grace_hopper.jpg" &> inception_client_batch_test05.txt &
time ./gen/bin/inception_client --server_port="107.xxx.xxx.xxx:9000" --image_file="grace_hopper.jpg" &> inception_client_batch_test06.txt &
time ./gen/bin/inception_client --server_port="107.xxx.xxx.xxx:9000" --image_file="grace_hopper.jpg" &> inception_client_batch_test07.txt &
time ./gen/bin/inception_client --server_port="107.xxx.xxx.xxx:9000" --image_file="grace_hopper.jpg" &> inception_client_batch_test08.txt &
time ./gen/bin/inception_client --server_port="107.xxx.xxx.xxx:9000" --image_file="grace_hopper.jpg" &> inception_client_batch_test09.txt &
time ./gen/bin/inception_client --server_port="107.xxx.xxx.xxx:9000" --image_file="grace_hopper.jpg" &> inception_client_batch_test10.txt &
```

The server simply ran one request at a time. If a timeout was set on the clients, some of the clients most likely would have timed out waiting. So, at least in the simple case, you don't need to worry about resources being exhausted and crashing your server. Assuming your server can handle a single request.

A more real world scenario would likely include at least one of batching, load balancing or async server/client.

**Comment by gautamvasudevan** [comment] 2018-08-03 19:58
Closing due to staleness. If this is still an issue, please file a new updated issue with current steps to reproduce the bug. If this is a question, please ask it on: 

https://stackoverflow.com/questions/tagged/tensorflow-serving

Thanks!

**Closed by gautamvasudevan** 2018-08-03 19:58 UTC
